### ISSUE TITLE
RPM build fail: Wrongs in specfile Source fields, testscript p2p-fullblocktest.py fail

### ISSUE THREAD

**Issue by voanhcuoc** [bitcoin/bitcoin#10312]
### Describe
1. The specfile declare `Version: 0.12.0` and inject it to the source URLs to get some files which haven't added yet in tag `v0.12.0`
2. The specfile still declare `Version: 0.12.0` when changes breaking the build process for v0.12.0 are committed. (#9956)
3. testscript p2p-fullblocktest.py fail (with specfile in d34995a, just before #9956 mess up the directory structure)
### Reproduce
1. 
```markdown
spectool -g -f ~/rpmbuild/SPECS/bitcoin.spec
Getting https://bitcoin.org/bin/bitcoin-core-0.12.0/bitcoin-0.12.0.tar.gz to ./bitcoin-0.12.0.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 5272k  100 5272k    0     0   193k      0  0:00:27  0:00:27 --:--:--  205k
Getting http://download.oracle.com/berkeley-db/db-4.8.30.NC.tar.gz to ./db-4.8.30.NC.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 21.7M  100 21.7M    0     0  3728k      0  0:00:05  0:00:05 --:--:-- 3970k
Getting https://raw.githubusercontent.com/bitcoin/bitcoin/v0.12.0/contrib/debian/examples/bitcoin.conf to ./bitcoin.conf
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  4617  100  4617    0     0   6599      0 --:--:-- --:--:-- --:--:--  6595
Getting https://upload.wikimedia.org/wikipedia/commons/4/46/Bitcoin.svg to ./Bitcoin.svg
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100  1498  100  1498    0     0   1606      0 --:--:-- --:--:-- --:--:--  1607
Getting https://raw.githubusercontent.com/bitcoin/bitcoin/v0.12.0/doc/man/bitcoind.1 to ./bitcoind.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl: (22) The requested URL returned error: 404 Not Found**
Getting https://raw.githubusercontent.com/bitcoin/bitcoin/v0.12.0/doc/man/bitcoin-cli.1 to ./bitcoin-cli.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl: (22) The requested URL returned error: 404 Not Found**
Getting https://raw.githubusercontent.com/bitcoin/bitcoin/v0.12.0/doc/man/bitcoin-qt.1 to ./bitcoin-qt.1
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl: (22) The requested URL returned error: 404 Not Found**
Getting https://raw.githubusercontent.com/bitcoin/bitcoin/v0.12.0/contrib/rpm/bitcoin.te to ./bitcoin.te
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl: (22) The requested URL returned error: 404 Not Found**
Getting https://raw.githubusercontent.com/bitcoin/bitcoin/v0.12.0/contrib/rpm/bitcoin.fc to ./bitcoin.fc
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl: (22) The requested URL returned error: 404 Not Found**
Getting https://raw.githubusercontent.com/bitcoin/bitcoin/v0.12.0/contrib/rpm/bitcoin.if to ./bitcoin.if
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
  0     0    0     0    0     0      0      0 --:--:-- --:--:-- --:--:--     0
**curl: (22) The requested URL returned error: 404 Not Found**
```
2. Execute rpmbuild with specfiles from *master HEAD* or *0.12 HEAD* result in `test/bitcoin-util-test.py: No such file or directory` . In `v0.12.0` , the specfile haven't been added.
3. With specfile from d34995a, the build run smooth and fail in this test:
```
Running testscript p2p-fullblocktest.py ...
Traceback (most recent call last):
  File "qa/pull-tester/rpc-tests.py", line 260, in <module>
    runtests()
  File "qa/pull-tester/rpc-tests.py", line 160, in runtests
    rpcTestDir + testScripts[i] + flags, shell=True)
  File "/usr/lib64/python2.7/subprocess.py", line 542, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '/home/khoa/rpmbuild/BUILD/bitcoin-0.12.0/qa/rpc-tests/p2p-fullblocktest.py --srcdir /home/khoa/rpmbuild/BUILD/bitcoin-0.12.0/src  ' returned non-zero exit status -11
error: Bad exit status from /var/tmp/rpm-tmp.HqT4St (%check)


RPM build errors:
    Bad exit status from /var/tmp/rpm-tmp.HqT4St (%check)
```
/var/tmp/rpm-tmp.HqT4St
```
#!/bin/sh

  RPM_SOURCE_DIR="/home/khoa/rpmbuild/SOURCES"
  RPM_BUILD_DIR="/home/khoa/rpmbuild/BUILD"
  RPM_OPT_FLAGS="-O2 -g -pipe -Wall -Wp,-D_FORTIFY_SOURCE=2 -fexceptions -fstack-protector-strong --param=ssp-buffer-size=4 -grecord-gcc-switches   -m64 -mtune=generic"
  RPM_LD_FLAGS="-Wl,-z,relro "
  RPM_ARCH="x86_64"
  RPM_OS="linux"
  export RPM_SOURCE_DIR RPM_BUILD_DIR RPM_OPT_FLAGS RPM_LD_FLAGS RPM_ARCH RPM_OS
  RPM_DOC_DIR="/usr/share/doc"
  export RPM_DOC_DIR
  RPM_PACKAGE_NAME="bitcoin"
  RPM_PACKAGE_VERSION="0.12.0"
  RPM_PACKAGE_RELEASE="2.el7.local"
  export RPM_PACKAGE_NAME RPM_PACKAGE_VERSION RPM_PACKAGE_RELEASE
  LANG=C
  export LANG
  unset CDPATH DISPLAY ||:
  RPM_BUILD_ROOT="/home/khoa/rpmbuild/BUILDROOT/bitcoin-0.12.0-2.el7.local.x86_64"
  export RPM_BUILD_ROOT
  
  PKG_CONFIG_PATH="${PKG_CONFIG_PATH}:/usr/lib64/pkgconfig:/usr/share/pkgconfig"
  export PKG_CONFIG_PATH
  
  set -x
  umask 022
  cd "/home/khoa/rpmbuild/BUILD"
cd 'bitcoin-0.12.0'
make check
pushd src
srcdir=. test/bitcoin-util-test.py
popd
qa/pull-tester/rpc-tests.py -extended


```
### Expected behaviour
1. The files is available for fetching with spectool (hardcode a commit with appropriate files).
2. Commits with backward-incompatible changes with a version should not declare that version anymore, or clearly point out a commit in which packager can find appropriate specfile.
3. The test pass.

**Comment by MarcoFalke** [comment]
The RPM spec file was removed in commit https://github.com/bitcoin-core/packaging/commit/fa7c698cb24bab350b40ee2d825c443dabdd9633, because is was unmaintained and outdated.
