### ISSUE TITLE
bitcoind aborts at shutdown

### ISSUE THREAD

**Issue by janstary** [bitcoin/bitcoin#10850]
This is 0.14.2 on OpenBSD 6.1-current.

```
env AUTOCONF_VERSION=2.69  AUTOMAKE_VERSION=1.15 sh autogen.sh
./configure --prefix=$HOME --mandir=$HOME/man --disable-tests --disable-gui-tests --enable-wallet --with-gui=no CC=egcc CXX=eg++  BDB_CFLAGS='-I/usr/local/db48/include/' BDB_LIBS='-L/usr/local/db48/lib/ -ldb_cxx' 
gmake
gmake install
```

bitcoind seems to run just fine, until I try to stop it with `bitcoin-cli stop`,
when it goes to shutdown, which ends with `Abort trap (core dumped)`.

The debug.log (full log at bottom) ends with:

```
2017-07-17 12:17:54 tor: Thread interrupt      
2017-07-17 12:17:54 addcon thread exit         
2017-07-17 12:17:54 torcontrol thread exit     
```

The backtrace of the dumped core says:

```
hans@dell:~$ gdbi/home/hans/bin/bitcoind bitcoind.core
GNU gdb 6.3
Copyright 2004 Free Software Foundation, Inc.
GDB is free software, covered by the GNU General Public License, and you are
welcome to change it and/or distribute copies of it under certain conditions.
Type "show copying" to see the conditions.
There is absolutely no warranty for GDB.  Type "show warranty" for details.
This GDB was configured as "amd64-unknown-openbsd6.1"...
Core was generated by `bitcoind'.
Program terminated with signal 6, Aborted.
Reading symbols from /usr/lib/libpthread.so.23.0...done.
Loaded symbols for /usr/lib/libpthread.so.23.0
Loaded symbols for /home/hans/bin/bitcoind
Reading symbols from /usr/local/lib/libboost_system.so.6.0...done.
Loaded symbols for /usr/local/lib/libboost_system.so.6.0
Reading symbols from /usr/local/lib/libboost_filesystem.so.6.0...done.
Loaded symbols for /usr/local/lib/libboost_filesystem.so.6.0
Reading symbols from /usr/local/lib/libboost_program_options-mt.so.6.0...done.
Loaded symbols for /usr/local/lib/libboost_program_options-mt.so.6.0
Reading symbols from /usr/local/lib/libboost_thread-mt.so.6.0...done.
Loaded symbols for /usr/local/lib/libboost_thread-mt.so.6.0
Reading symbols from /usr/local/lib/libboost_chrono-mt.so.6.0...done.
Loaded symbols for /usr/local/lib/libboost_chrono-mt.so.6.0
Reading symbols from /usr/lib/libssl.so.43.3...done.
Loaded symbols for /usr/lib/libssl.so.43.3
Reading symbols from /usr/lib/libcrypto.so.41.2...done.
Loaded symbols for /usr/lib/libcrypto.so.41.2
Reading symbols from /usr/local/lib/libevent_pthreads.so.0.0...done.
Loaded symbols for /usr/local/lib/libevent_pthreads.so.0.0
Reading symbols from /usr/local/lib/libevent_extra.so.0.1...done.
Loaded symbols for /usr/local/lib/libevent_extra.so.0.1
Reading symbols from /usr/local/lib/libevent_core.so.1.1...done.
Loaded symbols for /usr/local/lib/libevent_core.so.1.1
Reading symbols from /usr/local/lib/libestdc++.so.17.1...done.
Loaded symbols for /usr/local/lib/libestdc++.so.17.1
Reading symbols from /usr/lib/libm.so.10.0...done.
Loaded symbols for /usr/lib/libm.so.10.0
Symbols already loaded for /usr/lib/libpthread.so.23.0
Reading symbols from /usr/lib/libc.so.89.6...done.
Loaded symbols for /usr/lib/libc.so.89.6
Reading symbols from /usr/lib/libstdc++.so.57.0...done.
Loaded symbols for /usr/lib/libstdc++.so.57.0
Reading symbols from /usr/local/lib/libboost_system-mt.so.6.0...done.
Loaded symbols for /usr/local/lib/libboost_system-mt.so.6.0
Reading symbols from /usr/libexec/ld.so...done.
Loaded symbols for /usr/libexec/ld.so
#0  0x00001855ceec65aa in thrkill () at {standard input}:5
5	{standard input}: No such file or directory.
	in {standard input}
(gdb) backtrace
#0  0x00001855ceec65aa in thrkill () at {standard input}:5
#1  0x00001855ceec0e19 in *_libc_abort () at /usr/src/lib/libc/stdlib/abort.c:52
#2  0x00001855c22c4875 in _Unwind_Resume (exc=0x1855cacea860) at unwind.inc:238
#3  0x0000185593fb9989 in boost::this_thread::hiden::sleep_for () from /usr/local/lib/libboost_thread-mt.so.6.0
Die: DW_TAG_unspecified_type (abbrev = 154, offset = 33422577)
	has children: FALSE
	attributes:
		DW_AT_name (DW_FORM_strp) string: "decltype(nullptr)"
Dwarf Error: Cannot find type of die [in module /home/hans/bin/bitcoind]
(gdb) quit
```

This does not happen when the wallet is not compiled in.
When configure as above, except `--enable-wallet` is replace with `--disable-wallet`,
the shutdown happens correctly:

```
2017-07-17 09:54:47 tor: Thread interrupt
2017-07-17 09:54:47 torcontrol thread exit
2017-07-17 09:54:47 addcon thread exit
2017-07-17 09:54:47 net thread exit
2017-07-17 09:54:47 scheduler thread interrupt
2017-07-17 09:54:47 Shutdown: In progress...
2017-07-17 09:54:48 msghand thread exit
2017-07-17 09:54:48 opencon thread exit
2017-07-17 09:54:48 Dumped mempool: 4e-06s to copy, 0.000674s to dump
2017-07-17 09:54:49 Shutdown: done
```

What I describe above seem to be some premature termination of that sequence.

Here is a debug.log a a good run (`--disable-wallet`) and a bad run (`--enable-wallet`),
with the best block updates snipped out (too long). I am not sure it is the wallet that makes the difference, but that's what I have observed three times now (with and without wallet).

```
2017-07-17 09:54:30 Bitcoin version v0.14.2.0-gfc61c83
2017-07-17 09:54:30 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2017-07-17 09:54:30 Assuming ancestors of block 00000000000000000013176bf8d7dfeab4e1db31dc93bc311b436e82ab226b90 have valid signatures.
2017-07-17 09:54:30 Default data directory /home/hans/.bitcoin
2017-07-17 09:54:30 Using data directory /home/hans/.bitcoin
2017-07-17 09:54:30 Using config file /home/hans/.bitcoin/bitcoin.conf
2017-07-17 09:54:30 Using at most 125 automatic connections (512 file descriptors available)
2017-07-17 09:54:30 Using 32 MiB out of 32 requested for signature cache, able to store 1048576 elements
2017-07-17 09:54:30 Using 4 threads for script verification
2017-07-17 09:54:30 scheduler thread start
2017-07-17 09:54:30 HTTP: creating work queue of depth 16
2017-07-17 09:54:30 No rpcpassword set - using random cookie authentication
2017-07-17 09:54:30 Generated RPC authentication cookie /home/hans/.bitcoin/.cookie
2017-07-17 09:54:30 HTTP: starting 4 worker threads
2017-07-17 09:54:30 Bound to [::]:8333
2017-07-17 09:54:30 Bound to 0.0.0.0:8333
2017-07-17 09:54:30 Cache configuration:
2017-07-17 09:54:30 * Using 2.0MiB for block index database
2017-07-17 09:54:30 * Using 8.0MiB for chain state database
2017-07-17 09:54:30 * Using 440.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2017-07-17 09:54:30 init message: Loading block index...
2017-07-17 09:54:30 Opening LevelDB in /home/hans/.bitcoin/blocks/index
2017-07-17 09:54:30 Opened LevelDB successfully
2017-07-17 09:54:30 Using obfuscation key for /home/hans/.bitcoin/blocks/index: 0000000000000000
2017-07-17 09:54:30 Opening LevelDB in /home/hans/.bitcoin/chainstate
2017-07-17 09:54:30 Opened LevelDB successfully
2017-07-17 09:54:30 Using obfuscation key for /home/hans/.bitcoin/chainstate: 848037f655fda875
2017-07-17 09:54:34 LoadBlockIndexDB: last block file = 2
2017-07-17 09:54:34 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=1359, size=28629265, heights=130943...132608, time=2011-06-15...2011-06-22)
2017-07-17 09:54:34 Checking all blk files are present...
2017-07-17 09:54:34 LoadBlockIndexDB: transaction index disabled
2017-07-17 09:54:34 LoadBlockIndexDB: hashBestChain=0000000000000ac50efb937c3166209c45fcd9b2cfb36e6b483c6bfcd221750a height=132420 date=2011-06-21 23:52:12 progress=0.003427
2017-07-17 09:54:34 init message: Rewinding blocks...
2017-07-17 09:54:35 init message: Verifying blocks...
2017-07-17 09:54:35 Verifying last 6 blocks at level 3
2017-07-17 09:54:35 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2017-07-17 09:54:35 No coin database inconsistencies in last 7 blocks (407 transactions)
2017-07-17 09:54:35  block index            4279ms
2017-07-17 09:54:35 No wallet support compiled in!
2017-07-17 09:54:35 mapBlockIndex.size() = 476203
2017-07-17 09:54:35 nBestHeight = 132420
2017-07-17 09:54:35 init message: Loading addresses...
2017-07-17 09:54:35 torcontrol thread start
2017-07-17 09:54:35 Imported mempool transactions from disk: 0 successes, 0 failed, 0 expired
2017-07-17 09:54:35 Loaded 11489 addresses from peers.dat  40ms
2017-07-17 09:54:35 init message: Loading banlist...
2017-07-17 09:54:35 init message: Starting network threads...
2017-07-17 09:54:35 init message: Done loading
2017-07-17 09:54:35 dnsseed thread start
2017-07-17 09:54:35 msghand thread start
2017-07-17 09:54:35 opencon thread start
2017-07-17 09:54:35 addcon thread start
2017-07-17 09:54:35 net thread start
2017-07-17 09:54:35 connect() to 77.247.182.247:8333 failed after select(): Connection refused (61)
2017-07-17 09:54:41 receive version message: /Satoshi:0.14.1/: version 70015, blocks=476203, us=79.98.77.229:57132, peer=0
2017-07-17 09:54:42 UpdateTip: new best=0000000000000b52398be4a6f883f72862612fb8a01749ada9e7e519501d609e height=132421 version=0x00000001 log2_work=64.324136 tx=816713 date='2011-06-21 23:53:29' progress=0.003427 cache=0.0MiB(21tx)
2017-07-17 09:54:42 UpdateTip: new best=000000000000097688bb2ea7d3507bdb0e0a5874a607f0b31ec682e7e6911c92 height=132422 version=0x00000001 log2_work=64.324371 tx=816765 date='2011-06-22 00:08:27' progress=0.003428 cache=0.0MiB(118tx)
2017-07-17 09:54:42 receive version message: /Satoshi:0.14.1/: version 70015, blocks=476203, us=79.98.77.229:55217, peer=1
2017-07-17 09:54:42 UpdateTip: new best=00000000000006d9d032cb124a5448dadf9cfe5ac8f13ab12abedda6b3ccb993 height=132423 version=0x00000001 log2_work=64.324607 tx=816975 date='2011-06-22 00:15:33' progress=0.003428 cache=0.1MiB(387tx)
2017-07-17 09:54:42 UpdateTip: new best=00000000000012e7ee1105f3be74bfdd10b1935e0458847517d3de4bed6985f7 height=132424 version=0x00000001 log2_work=64.324842 tx=816979 date='2011-06-22 00:16:25' progress=0.003428 cache=0.1MiB(392tx)
2017-07-17 09:54:42 UpdateTip: new best=0000000000000acf80422379bcab69a1193fbac690cd199e405e6d103c561d6e height=132425 version=0x00000001 log2_work=64.325077 tx=816995 date='2011-06-22 00:19:08' progress=0.003428 cache=0.1MiB(416tx)
2017-07-17 09:54:42 UpdateTip: new best=0000000000000dd039d9d305c7bb980ce92f9243d5683ad54161168e9c61e4c9 height=132426 version=0x00000001 log2_work=64.325312 tx=817005 date='2011-06-22 00:20:11' progress=0.003429 cache=0.1MiB(432tx)
2017-07-17 09:54:42 UpdateTip: new best=0000000000000daab330d4f0fb652bd809719f9fa745e204004c85aaa36d8dd3 height=132427 version=0x00000001 log2_work=64.325547 tx=817017 date='2011-06-22 00:32:51' progress=0.003429 cache=0.1MiB(457tx)
2017-07-17 09:54:42 UpdateTip: new best=00000000000001ef5962e06c250b01c13698143de645fdaf7256b5f473931970 best=000000000000093809a3c04fdc41ea4656d8fdbe7387dbd27c104c30100f5156 height=133245 version=0x00000001 log2_work=64.528453 tx=856257 date='2011-06-25 17:47:49' progress=0.003593 cache=13.6MiB(40787tx)
[snip a lot of UpdateTips]
2017-07-17 09:54:47 UpdateTip: new best=0000000000000bf2bfd7af96efa3dd268b237d45b8cdda97ab6dd07fca26ff1b height=133246 version=0x00000001 log2_work=64.528774 tx=856283 date='2011-06-25 17:52:29' progress=0.003593 cache=13.6MiB(40807tx)
2017-07-17 09:54:47 UpdateTip: new best=0000000000000520deb239b4e42beb94343750d2fa9f5acd59fbb79a65ee0634 height=133247 version=0x00000001 log2_work=64.529095 tx=856284 date='2011-06-25 17:52:35' progress=0.003593 cache=13.6MiB(40808tx)
2017-07-17 09:54:47 UpdateTip: new best=00000000000000b11eda1cd4136ba1490cd01585c4541bf0c2b95368c05beb90 height=133248 version=0x00000001 log2_work=64.529416 tx=856476 date='2011-06-25 18:26:35' progress=0.003594 cache=13.6MiB(40961tx)
2017-07-17 09:54:47 UpdateTip: new best=000000000000072fbd3eb595b2dd89114a59b3587c15cffe955bcd8758e45a34 height=133249 version=0x00000001 log2_work=64.529737 tx=856496 date='2011-06-25 18:28:59' progress=0.003594 cache=13.6MiB(40979tx)
2017-07-17 09:54:47 UpdateTip: new best=0000000000000a568a6461ef3f9e6dd0f0124ec28dcc703737f4b1a288bbb5c2 height=133250 version=0x00000001 log2_work=64.530058 tx=856599 date='2011-06-25 18:47:37' progress=0.003595 cache=13.6MiB(41050tx)
2017-07-17 09:54:47 UpdateTip: new best=000000000000094c8a5b02eb698c65451c45b6ec821c1b4b02e24cfdb5553b59 height=133251 version=0x00000001 log2_work=64.530378 tx=856627 date='2011-06-25 19:10:09' progress=0.003595 cache=13.6MiB(41080tx)
2017-07-17 09:54:47 UpdateTip: new best=000000000000097786dc347c7cbef94ee08b5faf20e40820a63e526b8ef81f85 height=133252 version=0x00000001 log2_work=64.530699 tx=856732 date='2011-06-25 19:11:38' progress=0.003595 cache=13.6MiB(41186tx)
2017-07-17 09:54:47 tor: Thread interrupt
2017-07-17 09:54:47 torcontrol thread exit
2017-07-17 09:54:47 addcon thread exit
2017-07-17 09:54:47 net thread exit
2017-07-17 09:54:47 scheduler thread interrupt
2017-07-17 09:54:47 Shutdown: In progress...
2017-07-17 09:54:48 msghand thread exit
2017-07-17 09:54:48 opencon thread exit
2017-07-17 09:54:48 Dumped mempool: 4e-06s to copy, 0.000674s to dump
2017-07-17 09:54:49 Shutdown: done
2017-07-17 12:17:36 



















2017-07-17 12:17:36 Bitcoin version v0.14.2.0-gfc61c83
2017-07-17 12:17:36 InitParameterInteraction: parameter interaction: -whitelistforcerelay=1 -> setting -whitelistrelay=1
2017-07-17 12:17:36 Assuming ancestors of block 00000000000000000013176bf8d7dfeab4e1db31dc93bc311b436e82ab226b90 have valid signatures.
2017-07-17 12:17:36 Default data directory /home/hans/.bitcoin
2017-07-17 12:17:36 Using data directory /home/hans/.bitcoin
2017-07-17 12:17:36 Using config file /home/hans/.bitcoin/bitcoin.conf
2017-07-17 12:17:36 Using at most 125 automatic connections (512 file descriptors available)
2017-07-17 12:17:36 Using 32 MiB out of 32 requested for signature cache, able to store 1048576 elements
2017-07-17 12:17:36 Using 4 threads for script verification
2017-07-17 12:17:36 HTTP: creating work queue of depth 16
2017-07-17 12:17:36 scheduler thread start
2017-07-17 12:17:36 No rpcpassword set - using random cookie authentication
2017-07-17 12:17:36 Generated RPC authentication cookie /home/hans/.bitcoin/.cookie
2017-07-17 12:17:36 HTTP: starting 4 worker threads
2017-07-17 12:17:36 Using BerkeleyDB version Berkeley DB 4.8.30: (April  9, 2010)
2017-07-17 12:17:36 Using wallet wallet.dat
2017-07-17 12:17:36 init message: Verifying wallet...
2017-07-17 12:17:36 CDBEnv::Open: LogDir=/home/hans/.bitcoin/database ErrorFile=/home/hans/.bitcoin/db.log
2017-07-17 12:17:36 Bound to [::]:8333
2017-07-17 12:17:36 Bound to 0.0.0.0:8333
2017-07-17 12:17:36 Cache configuration:
2017-07-17 12:17:36 * Using 2.0MiB for block index database
2017-07-17 12:17:36 * Using 8.0MiB for chain state database
2017-07-17 12:17:36 * Using 440.0MiB for in-memory UTXO set (plus up to 286.1MiB of unused mempool space)
2017-07-17 12:17:36 init message: Loading block index...
2017-07-17 12:17:36 Opening LevelDB in /home/hans/.bitcoin/blocks/index
2017-07-17 12:17:36 Opened LevelDB successfully
2017-07-17 12:17:36 Using obfuscation key for /home/hans/.bitcoin/blocks/index: 0000000000000000
2017-07-17 12:17:36 Opening LevelDB in /home/hans/.bitcoin/chainstate
2017-07-17 12:17:36 Opened LevelDB successfully
2017-07-17 12:17:36 Using obfuscation key for /home/hans/.bitcoin/chainstate: 848037f655fda875
2017-07-17 12:17:40 LoadBlockIndexDB: last block file = 2
2017-07-17 12:17:40 LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=2060, size=42956951, heights=130943...133300, time=2011-06-15...2011-06-26)
2017-07-17 12:17:40 Checking all blk files are present...
2017-07-17 12:17:40 LoadBlockIndexDB: transaction index disabled
2017-07-17 12:17:40 LoadBlockIndexDB: hashBestChain=000000000000097786dc347c7cbef94ee08b5faf20e40820a63e526b8ef81f85 height=133252 date=2011-06-25 19:11:38 progress=0.003595
2017-07-17 12:17:40 init message: Rewinding blocks...
2017-07-17 12:17:40 init message: Verifying blocks...
2017-07-17 12:17:40 Verifying last 6 blocks at level 3
2017-07-17 12:17:40 [0%]...[16%]...[33%]...[50%]...[66%]...[83%]...[99%]...[DONE].
2017-07-17 12:17:41 No coin database inconsistencies in last 7 blocks (475 transactions)
2017-07-17 12:17:41  block index            4430ms
2017-07-17 12:17:41 init message: Loading wallet...
2017-07-17 12:17:41 nFileVersion = 140200
2017-07-17 12:17:41 Keys: 102 plaintext, 0 encrypted, 102 w/ metadata, 102 total
2017-07-17 12:17:41  wallet                    3ms
2017-07-17 12:17:41 setKeyPool.size() = 100
2017-07-17 12:17:41 mapWallet.size() = 0
2017-07-17 12:17:41 mapAddressBook.size() = 1
2017-07-17 12:17:41 mapBlockIndex.size() = 476204
2017-07-17 12:17:41 nBestHeight = 133252
2017-07-17 12:17:41 torcontrol thread start
2017-07-17 12:17:41 init message: Loading addresses...
2017-07-17 12:17:41 UpdateTip: new best=00000000000005b85bb6b728471731deda57765f9bcbe7244f84818592103d71 height=133253 version=0x00000001 log2_work=64.53102 tx=856881 date='2011-06-25 19:14:30' progress=0.003595 cache=0.0MiB(191tx)
2017-07-17 12:17:41 UpdateTip: new best=00000000000001cc70f7b70f636af98f422782bcadbeff10abeb9123fe681e18 height=133254 version=0x00000001 log2_work=64.53134 tx=856947 date='2011-06-25 19:30:37' progress=0.003596 cache=0.2MiB(352tx)
2017-07-17 12:17:41 UpdateTip: new best=000000000000063b209aea0733b509c9664606ed82d22eb7db5089477620def1 height=133255 version=0x00000001 log2_work=64.531661 tx=857071 date='2011-06-25 19:34:33' progress=0.003596 cache=0.3MiB(645tx)
2017-07-17 12:17:41 UpdateTip: new best=000000000000098d27eeb055a0bbc0d46c7689aab157159b7e4ad556f0babe53 height=133256 version=0x00000001 log2_work=64.531981 tx=857097 date='2011-06-25 19:38:22' progress=0.003596 cache=0.3MiB(688tx)
2017-07-17 12:17:41 UpdateTip: new best=00000000000000a83f6231ad27536b2517793d3774404dce9b10b5638d67e254 height=133257 version=0x00000001 log2_work=64.532302 tx=857167 date='2011-06-25 19:53:32' progress=0.003597 cache=0.4MiB(822tx)
2017-07-17 12:17:41 UpdateTip: new best=00000000000008cf559aedcc4090c906c16c55976fe4df2d8110d4a9da2e126f height=133258 version=0x00000001 log2_work=64.532622 tx=857357 date='2011-06-25 21:07:46' progress=0.003597 cache=0.8MiB(1236tx)
2017-07-17 12:17:41 Loaded 11489 addresses from peers.dat  49ms
2017-07-17 12:17:41 init message: Loading banlist...
2017-07-17 12:17:41 init message: Starting network threads...
2017-07-17 12:17:41 init message: Done loading
2017-07-17 12:17:41 opencon thread start
2017-07-17 12:17:41 net thread start
2017-07-17 12:17:41 msghand thread start
2017-07-17 12:17:41 dnsseed thread start
2017-07-17 12:17:41 addcon thread start
2017-07-17 12:17:41 UpdateTip: new best=0000000000000ad887d09569f22eab1b5e8412f4c2b192f1b066b5c2fbfedafe height=133259 version=0x00000001 log2_work=64.532942 tx=857457 date='2011-06-25 21:19:40' progress=0.003598 cache=1.0MiB(1498tx)
2017-07-17 12:17:41 UpdateTip: new best=0000000000000a281e6575be233952d7381a3432bea6794670e92dafe4a10c26 height=133260 version=0x00000001 log2_work=64.533262 tx=857499 date='2011-06-25 21:30:26' progress=0.003598 cache=1.0MiB(1593tx)
2017-07-17 12:17:41 UpdateTip: new best=0000000000000b02ea67e5895e42bae766aca6aa6dd7dde993b7ba661d1d7c4c height=133261 version=0x00000001 log2_work=64.533583 tx=857554 date='2011-06-25 21:40:04' progress=0.003598 cache=1.1MiB(1677tx)
[snip a lot of UpdateTips]
2017-07-17 12:17:53 UpdateTip: new best=00000000000006e805964efae523cf3b36bf9be081c39af2889f7f50c295dc35 height=133490 version=0x00000001 log2_work=64.605074 tx=873339 date='2011-06-27 07:59:02' progress=0.003665 cache=9.4MiB(21532tx)
2017-07-17 12:17:53 UpdateTip: new best=00000000000004c21915f667b8f58fcd3b6fb908d51641a6d7ed3bf597f32a29 height=133491 version=0x00000001 log2_work=64.605378 tx=873364 date='2011-06-27 08:22:17' progress=0.003665 cache=9.5MiB(21554tx)
2017-07-17 12:17:54 tor: Thread interrupt
2017-07-17 12:17:54 addcon thread exit
2017-07-17 12:17:54 torcontrol thread exit
```

BTW, what is the big gap between the `2017-07-17 12:17:36` line
and the next one where it actually starts logging something?

**Comment by TheBlueMatt** [comment]
Hmm, thats a somewhat strange backtrace, can you get a bt from all threads out of the dump?

**Comment by Sjors** [comment]
Are you still seeing this?
