### ISSUE TITLE
p2p-fullblocktest.py fails when using ./configure --enable-debug

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#11876]
Tested with master ad1820cb (but the issue is older):

Test passes:
```
./configure --with-incompatible-bdb --disable-wallet --without-gui
make
test/functional/p2p-fullblocktest.py
```

Test fails:

```
make clean
./configure --enable-debug --with-incompatible-bdb --without-gui --disable-qt
make
test/functional/p2p-fullblocktest.py

2017-12-12 12:46:23.112000 TestFramework.comptool (INFO): Running test 99: test/functional/p2p-fullblocktest.py line 1283
2017-12-12 12:47:25.092000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File ".../test/functional/test_framework/test_framework.py", line 118, in main
    self.run_test()
  File "test/functional/p2p-fullblocktest.py", line 73, in run_test
    self.test.run()
  File ".../test/functional/test_framework/comptool.py", line 341, in run
    self.sync_blocks(block.sha256, 1)
  File "..../test/functional/test_framework/comptool.py", line 211, in sync_blocks
    self.wait_for_pings(self.ping_counter)
  File ".../test/functional/test_framework/comptool.py", line 191, in wait_for_pings
    wait_until(received_pongs, lock=mininode_lock)
  File ".../test/functional/test_framework/util.py", line 222, in wait_until
    assert_greater_than(timeout, time.time())
  File ".../test/functional/test_framework/util.py", line 42, in assert_greater_than
    raise AssertionError("%s <= %s" % (str(thing1), str(thing2)))
AssertionError: 1513082845.0654101 <= 1513082845.092903
```

Added `--disable-wallet --without-gui` to create a simpler scenario to reproduce, but it happens without those flags too.

**Comment by fanquake** [comment]
Can you please combine this with #11632, as we don't need multiple issues open for the same failing test.
