### ISSUE TITLE
[qa] wallet_address_types.py failed with AssertionError

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#12389]
Example:

```
stdout:
2018-02-08 12:58:50.911000 TestFramework (INFO): Initializing test directory /tmp/bitcoin_test_runner_20180208_125641/wallet_address_types_418
2018-02-08 12:58:57.211000 TestFramework (INFO): Sending from node 0 (['-addresstype=legacy']) without multisig using default
2018-02-08 12:59:00.483000 TestFramework (INFO): Sending from node 1 (['-addresstype=p2sh-segwit']) without multisig using default
2018-02-08 12:59:01.780000 TestFramework (INFO): Sending from node 2 (['-addresstype=p2sh-segwit', '-changetype=bech32']) without multisig using default
2018-02-08 12:59:04.075000 TestFramework (INFO): Sending from node 3 (['-addresstype=bech32']) without multisig using default
2018-02-08 12:59:06.421000 TestFramework (INFO): Sending from node 0 (['-addresstype=legacy']) with multisig using default
2018-02-08 12:59:09.901000 TestFramework (INFO): Sending from node 1 (['-addresstype=p2sh-segwit']) with multisig using default
2018-02-08 12:59:11.435000 TestFramework (INFO): Sending from node 2 (['-addresstype=p2sh-segwit', '-changetype=bech32']) with multisig using default
2018-02-08 12:59:12.772000 TestFramework (INFO): Sending from node 3 (['-addresstype=bech32']) with multisig using default
2018-02-08 12:59:14.274000 TestFramework (INFO): Sending from node 0 (['-addresstype=legacy']) without multisig using p2sh-segwit
2018-02-08 12:59:16.474000 TestFramework (INFO): Sending from node 1 (['-addresstype=p2sh-segwit']) without multisig using bech32
2018-02-08 12:59:17.684000 TestFramework (INFO): Sending from node 2 (['-addresstype=p2sh-segwit', '-changetype=bech32']) without multisig using legacy
2018-02-08 12:59:19.916000 TestFramework (INFO): Sending from node 3 (['-addresstype=bech32']) without multisig using p2sh-segwit
2018-02-08 12:59:21.100000 TestFramework (INFO): Sending from node 0 (['-addresstype=legacy']) with multisig using default
2018-02-08 12:59:22.403000 TestFramework (INFO): Sending from node 1 (['-addresstype=p2sh-segwit']) with multisig using default
2018-02-08 12:59:24.156000 TestFramework (INFO): Sending from node 2 (['-addresstype=p2sh-segwit', '-changetype=bech32']) with multisig using default
2018-02-08 12:59:26.465000 TestFramework (INFO): Sending from node 3 (['-addresstype=bech32']) with multisig using default
2018-02-08 12:59:28.950000 TestFramework (INFO): Nodes with addresstype=legacy never use a P2WPKH change output
2018-02-08 12:59:28.981000 TestFramework (INFO): Nodes with addresstype=p2sh-segwit only use a P2WPKH change output if any destination address is bech32:
2018-02-08 12:59:29.074000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 123, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/wallet_address_types.py", line 269, in run_test
    self.test_change_output_type(1, [to_address_p2sh, to_address_bech32_1], 'bech32')
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/wallet_address_types.py", line 151, in test_change_output_type
    assert_equal(len(tx["vout"]), len(destinations) + 1)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/util.py", line 38, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(1 == 3)
2018-02-08 12:59:29.075000 TestFramework (INFO): Stopping nodes
2018-02-08 12:59:29.443000 TestFramework (WARNING): Not cleaning up dir /tmp/bitcoin_test_runner_20180208_125641/wallet_address_types_418
2018-02-08 12:59:29.443000 TestFramework (ERROR): Test failed. Test logging available at /tmp/bitcoin_test_runner_20180208_125641/wallet_address_types_418/test_framework.log
2018-02-08 12:59:29.444000 TestFramework (ERROR): Hint: Call /home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/combine_logs.py '/tmp/bitcoin_test_runner_20180208_125641/wallet_address_types_418' to consolidate all logs
```

https://travis-ci.org/bitcoin/bitcoin/jobs/338962227

**Comment by jnewbery** [comment]
This is a very odd failure. The test is calling the `sendmany` RPC with two destinations, and then asserting that the tx has three outputs (two payments + one change output). The assert is failing because the tx has only one output.

Marco, was this just a one-off or have you seen this several times?

**Comment by MarcoFalke** [comment]
This was an one-off, but imo a one-off is still one too many off. ;)
