### ISSUE TITLE
Deterministic failure in feature_bip68_sequence.py

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#12456]
```
$ ./test/functional/feature_bip68_sequence.py 
2018-02-16 19:05:51.568000 TestFramework (INFO): Initializing test directory /tmp/test1hz4o29p
2018-02-16 19:05:57.956000 TestFramework (INFO): Running test disable flag
2018-02-16 19:05:57.974000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "////bitcoin/test/functional/test_framework/util.py", line 112, in try_rpc
    fun(*args, **kwds)
  File "////bitcoin/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "////bitcoin/test/functional/test_framework/authproxy.py", line 138, in __call__
    raise JSONRPCException(response['error'])
test_framework.authproxy.JSONRPCException: non-BIP68-final (code 64) (-26)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "////bitcoin/test/functional/test_framework/test_framework.py", line 125, in main
    self.run_test()
  File "./test/functional/feature_bip68_sequence.py", line 31, in run_test
    self.test_disable_flag()
  File "./test/functional/feature_bip68_sequence.py", line 86, in test_disable_flag
    assert_raises_rpc_error(-26, NOT_FINAL_ERROR, self.nodes[0].sendrawtransaction, ToHex(tx2))
  File "////bitcoin/test/functional/test_framework/util.py", line 104, in assert_raises_rpc_error
    assert try_rpc(code, message, fun, *args, **kwds), "No exception raised"
  File "////bitcoin/test/functional/test_framework/util.py", line 118, in try_rpc
    raise AssertionError("Expected substring not found:" + e.error['message'])
AssertionError: Expected substring not found:non-BIP68-final (code 64)

**Comment by MarcoFalke** [comment]
See #12455
