### ISSUE TITLE
Segmentation fault in util: ScheduleBatchPriority

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#12915]
Steps to reproduce:

```
git checkout 7e23972d1f715f596e61e6e3775a3ada75604497
./configure --with-sanitizers=address --disable-wallet
make
./test/functional/wallet_disable.py 
2018-04-08T14:57:23.371000Z TestFramework (INFO): Initializing test directory /tmp/testuzxdpst_
ASAN:DEADLYSIGNAL
=================================================================
==5106==ERROR: AddressSanitizer: SEGV on unknown address 0x0000000002d0 (pc 0x7f72043a1d38 bp 0x7f71f1578cd0 sp 0x7f71f1578c70 T14)
==5106==The signal is caused by a READ memory access.
==5106==Hint: address points to the zero page.
    #0 0x7f72043a1d37 in __pthread_setschedparam (/lib64/libpthread.so.0+0x8d37)
    #1 0x555fc43c5577 in ScheduleBatchPriority() /home/marco/workspace/bitcoin/src/util.cpp:1048
    #2 0x555fc3a2cca1 in ThreadImport(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >) /home/marco/workspace/bitcoin/src/init.cpp:635
    #3 0x555fc3a9fd50 in void boost::_bi::list1<boost::_bi::value<std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> > > >::operator()<void (*)(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >), boost::_bi::list0>(boost::_bi::type<void>, void (*&)(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >), boost::_bi::list0&, int) /usr/include/boost/bind/bind.hpp:259
    #4 0x555fc3a9fd50 in boost::_bi::bind_t<void, void (*)(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >), boost::_bi::list1<boost::_bi::value<std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> > > > >::operator()() /usr/include/boost/bind/bind.hpp:1294
    #5 0x555fc3a9fd50 in boost::detail::thread_data<boost::_bi::bind_t<void, void (*)(std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >), boost::_bi::list1<boost::_bi::value<std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> > > > > >::run() /usr/include/boost/thread/detail/thread.hpp:116
    #6 0x7f7205bf730c  (/lib64/libboost_thread.so.1.64.0+0x1330c)
    #7 0x7f72043a050a in start_thread (/lib64/libpthread.so.0+0x750a)
    #8 0x7f72040d816e in clone (/lib64/libc.so.6+0xf516e)

AddressSanitizer can not provide additional info.
SUMMARY: AddressSanitizer: SEGV (/lib64/libpthread.so.0+0x8d37) in __pthread_setschedparam
Thread T14 (bitcoin-loadblk) created by T0 here:
    #0 0x7f72064d9a2f in pthread_create (/lib64/libasan.so.4+0x37a2f)
    #1 0x7f7205bf5fd9 in boost::thread::start_thread_noexcept() (/lib64/libboost_thread.so.1.64.0+0x11fd9)

==5106==ABORTING

**Comment by MarcoFalke** [comment]
Calling "git revert d54874d" seems to work around the issue
