### ISSUE TITLE
qa: Intermittent failure in rpc_psbt

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#13738]
travis run: https://travis-ci.org/bitcoin/bitcoin/jobs/406813397

```
rpc_psbt.py failed, Duration: 4 s
stdout:
2018-07-22T13:28:57.765000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_test_runner_20180722_132530/rpc_psbt_49
2018-07-22T13:29:00.531000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 160, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/rpc_psbt.py", line 101, in run_test
    assert_raises_rpc_error(-22, "TX decode failed", self.nodes[0].converttopsbt, signedtx['hex'])
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/util.py", line 105, in assert_raises_rpc_error
    assert try_rpc(code, message, fun, *args, **kwds), "No exception raised"
AssertionError: No exception raised

**Comment by MarcoFalke** [comment]
Going to create a new issue when I see this again.

**Comment by MarcoFalke** [comment]
Still happens.

Steps to reproduce:

```sh
while ./test/functional/rpc_psbt.py ; do true; done

**Comment by MarcoFalke** [comment]
8cca1fbea9

**Comment by MarcoFalke** [comment]
This still exists:

```
while ./test/functional/rpc_psbt.py ; do true; done


2019-04-25T22:02:28.771000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_hiius8kc
2019-04-25T22:02:30.500000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "./test/functional/test_framework/test_framework.py", line 175, in main
    self.run_test()
  File "./test/functional/rpc_psbt.py", line 156, in run_test
    assert_raises_rpc_error(-22, "", self.nodes[0].converttopsbt, signedtx['hex'])
  File "./test/functional/test_framework/util.py", line 105, in assert_raises_rpc_error
    assert try_rpc(code, message, fun, *args, **kwds), "No exception raised"
AssertionError: No exception raised
