### ISSUE TITLE
qa: p2p_invalid_messages occasionally fails with "Memory usage increased over threshold"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#14710]
log (on macos)

```
64/106 - p2p_invalid_messages.py failed, Duration: 16 s
stdout:
2018-11-12T15:54:06.887000Z TestFramework (INFO): Initializing test directory /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/test_runner_₿_🏃_20181112_154734/p2p_invalid_messages_46
2018-11-12T15:54:07.944000Z TestFramework (INFO): Sending a bunch of large, junk messages to test memory exhaustion. May take a bit...
2018-11-12T15:54:22.578000Z TestFramework (INFO): Waiting for node to drop junk messages.
2018-11-12T15:54:22.670000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "./test_framework/test_framework.py", line 171, in main
    self.run_test()
  File "./test/functional/p2p_invalid_messages.py", line 86, in run_test
    assert node.p2p.is_connected
  File "/usr/local/Cellar/python/3.6.5_1/Frameworks/Python.framework/Versions/3.6/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "./test_framework/test_node.py", line 314, in assert_memory_usage_stable
    perc_increase_memory_usage * 100))
  File "./test_framework/test_node.py", line 143, in _raise_assertion_error
    raise AssertionError(self._node_msg(msg))
AssertionError: [node 0] Memory usage increased over threshold of 3.000% from 71220 to 81216 (14.035%)
2018-11-12T15:54:22.758000Z TestFramework (INFO): Stopping nodes
2018-11-12T15:54:23.111000Z TestFramework (WARNING): Not cleaning up dir /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/test_runner_₿_🏃_20181112_154734/p2p_invalid_messages_46
2018-11-12T15:54:23.111000Z TestFramework (ERROR): Test failed. Test logging available at /var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/test_runner_₿_🏃_20181112_154734/p2p_invalid_messages_46/test_framework.log
2018-11-12T15:54:23.112000Z TestFramework (ERROR): Hint: Call ./combine_logs.py '/var/folders/nz/vv4_9tw56nv9k3tkvyszvwg80000gn/T/test_runner_₿_🏃_20181112_154734/p2p_invalid_messages_46' to consolidate all logs

**Comment by MarcoFalke** [comment]
This fails rather consistently on macos. Might want to remove the test again for now?

**Comment by kallewoof** [comment]
Failing for me as well on 10.13.6 MacBook Pro (15-inch, 2017).

**Comment by MarcoFalke** [comment]
@jamesob Any thoughts?
