### ISSUE TITLE
test/functional/test_runner.py wallet_listtransactions.py fails when run individually

### ISSUE THREAD

**Issue by kristapsk** [bitcoin/bitcoin#14732]
When I run complete functional tests using `test/functional/test_runner.py`, all tests pass. Also, when I run `test/functional/wallet_listtransactions.py` individually, it is successfull.
```
$ test/functional/wallet_listtransactions.py 
2018-11-15T22:08:25.288000Z TestFramework (INFO): Initializing test directory /tmp/test60gysa60
2018-11-15T22:08:51.034000Z TestFramework (INFO): Stopping nodes
2018-11-15T22:08:51.998000Z TestFramework (INFO): Cleaning up /tmp/test60gysa60 on exit
2018-11-15T22:08:51.998000Z TestFramework (INFO): Tests successful
```
But when I run `test/functional/test_runner.py wallet_listtransactions.py`, it always fails with the "AssertionError: Mempool sync timed out".
```
$ LC_ALL=lv_LV.UTF-8 test/functional/test_runner.py wallet_listtransactions.py
Temporary test directory at /tmp/test_runner_₿_🏃_20181116_001822
WARNING! There is already a bitcoind process running on this system. Tests may fail unexpectedly due to resource contention!
1/1 - wallet_listtransactions.py failed, Duration: 84 s                                                                                                                 

stdout:
2018-11-15T22:18:22.640000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20181116_001822/wallet_listtransactions_0
2018-11-15T22:19:45.625000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "XXX/bitcoin/test/functional/test_framework/test_framework.py", line 171, in main
    self.run_test()
  File "XXX/bitcoin/test/functional/wallet_listtransactions.py", line 36, in run_test
    self.sync_all()
  File "XXX/bitcoin/test/functional/test_framework/test_framework.py", line 372, in sync_all
    sync_mempools(group)
  File "XXX/bitcoin/test/functional/test_framework/util.py", line 408, in sync_mempools
    raise AssertionError("Mempool sync timed out:{}".format("".join("\n  {!r}".format(m) for m in pool)))
AssertionError: Mempool sync timed out:
  {'88a5f9e47a8617c29eb2330d06cb8af84e30dbcf8276c018b522af9d2cfbf297'}
  set()
2018-11-15T22:19:45.682000Z TestFramework (INFO): Stopping nodes
2018-11-15T22:19:46.646000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20181116_001822/wallet_listtransactions_0
2018-11-15T22:19:46.646000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20181116_001822/wallet_listtransactions_0/test_framework.log
2018-11-15T22:19:46.648000Z TestFramework (ERROR): Hint: Call XXX/bitcoin/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20181116_001822/wallet_listtransactions_0' to consolidate all logs


stderr:



TEST                       | STATUS    | DURATION

wallet_listtransactions.py | ✖ Failed  | 84 s

ALL                        | ✖ Failed  | 84 s (accumulated) 
Runtime: 84 s
```

Looked at logs mentioned in output, but could not find anything suspicous there.

Is it a bug or feature? :) Any ideas?

It is with current master.

**Comment by MarcoFalke** [comment]
This is a weird interaction when not creating the cache with the listtransactions script (test runner running all scripts or running script by hand) vs creating the cache with the listtransactions script (test runner running only the listtransactions script). Creating the cache with the listtransactions script would disable mocktime, whereas it should stay enabled.

Simple fix:

```diff
diff --git a/test/functional/wallet_listtransactions.py b/test/functional/wallet_listtransactions.py
index 8ca0387268..3fb25b1382 100755
--- a/test/functional/wallet_listtransactions.py
+++ b/test/functional/wallet_listtransactions.py
@@ -22,15 +22,17 @@ def tx_from_hex(hexstring):
     tx.deserialize(f)
     return tx
 
+
 class ListTransactionsTest(BitcoinTestFramework):
     def set_test_params(self):
         self.num_nodes = 2
-        self.enable_mocktime()
 
     def skip_test_if_missing_module(self):
         self.skip_if_no_wallet()
 
     def run_test(self):
+        self.nodes[0].generate(1)  # Get out of IBD
+        self.sync_all()
         # Simple send, 0 to 1:
         txid = self.nodes[0].sendtoaddress(self.nodes[1].getnewaddress(), 0.1)
         self.sync_all()
```
