### ISSUE TITLE
test: feature_config_args and feature_includeconf fail on native windows

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#15542]
Current master.

Sample excerpt:

```
2019-03-05T23:09:14.790000Z TestFramework (INFO): -includeconf works from config file. subversion should end with 'main; relative)/'
2019-03-05T23:09:14.826000Z TestFramework (INFO): -includeconf cannot be used as command-line arg
2019-03-05T23:09:24.495000Z TestFramework (INFO): -includeconf cannot be used recursively. subversion should end with 'main; relative)/'
2019-03-05T23:09:27.626000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "test\functional\test_framework\test_framework.py", line 175, in main
    self.run_test()
  File "test/functional/feature_includeconf.py", line 55, in run_test
    self.stop_node(0, expected_stderr="warning: -includeconf cannot be used from included files; ignoring -includeconf=relative2.conf")
  File "test\functional\test_framework\test_framework.py", line 372, in stop_node
    self.nodes[i].stop_node(expected_stderr, wait=wait)
  File "functional\test_framework\test_node.py", line 266, in stop_node
    raise AssertionError("Unexpected stderr {} != {}".format(stderr, expected_stderr))
AssertionError: Unexpected stderr  != warning: -includeconf cannot be used from included files; ignoring -includeconf=relative2.conf

**Comment by MarcoFalke** [comment]
This was fixed by 

*  Refactor: Replace fprintf with tfm::format #16205
