### ISSUE TITLE
Sporadic example_test.py failure

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#15636]
I've seen this error in appveyor on #15629:
```
68/118 - example_test.py failed, Duration: 12 s
stdout:
2019-03-21T18:12:43.380000Z TestFramework (INFO): Initializing test directory C:\Users\appveyor\AppData\Local\Temp\1\test_runner_₿_🏃_20190321_180343\example_test_50
2019-03-21T18:12:48.510000Z TestFramework (INFO): Starting test!
2019-03-21T18:12:48.511000Z TestFramework (INFO): Calling a custom function
2019-03-21T18:12:48.511000Z TestFramework (INFO): Calling a custom method
2019-03-21T18:12:48.511000Z TestFramework (INFO): Running custom_method
2019-03-21T18:12:48.511000Z TestFramework (INFO): Create some blocks
2019-03-21T18:12:48.528000Z TestFramework (INFO): Wait for node1 to reach current tip (height 11) using RPC
2019-03-21T18:12:48.582000Z TestFramework (INFO): Connect node2 and node1
2019-03-21T18:12:48.792000Z TestFramework (INFO): Add P2P connection to node2
2019-03-21T18:12:48.847000Z TestFramework (INFO): Wait for node2 reach current tip. Test that it has propagated all the blocks to us
2019-03-21T18:12:53.987000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: (['        wait_until(lambda: sorted(blocks) == sorted(list(self.nodes[2].p2p.block_receive_map.keys())), timeout=5, lock=mininode_lock)\n'], 203)
2019-03-21T18:12:53.988000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "C:\projects\bitcoin\test\functional\test_framework\test_framework.py", line 175, in main
    self.run_test()
  File "C:\projects\bitcoin/test/functional/example_test.py", line 203, in run_test
    wait_until(lambda: sorted(blocks) == sorted(list(self.nodes[2].p2p.block_receive_map.keys())), timeout=5, lock=mininode_lock)
  File "C:\projects\bitcoin\test\functional\test_framework\util.py", line 224, in wait_until
    raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
AssertionError: Predicate (['        wait_until(lambda: sorted(blocks) == sorted(list(self.nodes[2].p2p.block_receive_map.keys())), timeout=5, lock=mininode_lock)\n'], 203) not true after 5 seconds
2019-03-21T18:12:54.174000Z TestFramework (INFO): Stopping nodes
2019-03-21T18:12:55.024000Z TestFramework (WARNING): Not cleaning up dir C:\Users\appveyor\AppData\Local\Temp\1\test_runner_₿_🏃_20190321_180343\example_test_50
2019-03-21T18:12:55.101000Z TestFramework (ERROR): Test failed. Test logging available at C:\Users\appveyor\AppData\Local\Temp\1\test_runner_₿_🏃_20190321_180343\example_test_50/test_framework.log
2019-03-21T18:12:55.101000Z TestFramework (ERROR): Hint: Call C:\projects\bitcoin\test\functional\combine_logs.py 'C:\Users\appveyor\AppData\Local\Temp\1\test_runner_₿_🏃_20190321_180343\example_test_50' to consolidate all logs
```

**Comment by MarcoFalke** [comment]
I think there are still some sporadic block sync failures on appveyor (and travis). Haven't looked into them, but we should start collecting the dumped debug logs.
