### ISSUE TITLE
Sporadic feature_segwit.py failure

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#15653]
```
7/118 - feature_segwit.py failed, Duration: 40 s
stdout:
2019-03-23T10:22:43.824000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20190323_102023/feature_segwit_109
2019-03-23T10:22:48.099000Z TestFramework (INFO): Verify sigops are counted in GBT with pre-BIP141 rules before the fork
2019-03-23T10:22:58.446000Z TestFramework (INFO): Verify witness txs are skipped for mining before the fork
2019-03-23T10:22:58.639000Z TestFramework (INFO): Verify unsigned p2sh witness txs without a redeem script are invalid
2019-03-23T10:22:58.743000Z TestFramework (INFO): Verify previous witness txs skipped for mining can now be mined
2019-03-23T10:22:58.786000Z TestFramework (INFO): Verify default node can't accept txs with missing witness
2019-03-23T10:22:58.845000Z TestFramework (INFO): Verify block and transaction serialization rpcs return differing serializations depending on rpc serialization flag
2019-03-23T10:22:58.974000Z TestFramework (INFO): Verify witness txs without witness data are invalid after the fork
2019-03-23T10:22:58.992000Z TestFramework (INFO): Verify default node can now use witness txs
2019-03-23T10:22:59.267000Z TestFramework (INFO): Verify sigops are counted in GBT with BIP141 rules after the fork
2019-03-23T10:22:59.984000Z TestFramework (INFO): Non-segwit miners are able to use GBT response after activation.
2019-03-23T10:23:00.252000Z TestFramework (INFO): Verify behaviour of importaddress and listunspent
2019-03-23T10:23:23.263000Z TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 175, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/feature_segwit.py", line 527, in run_test
    self.start_node(1)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 345, in start_node
    node.wait_for_rpc_connection()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_node.py", line 210, in wait_for_rpc_connection
    'bitcoind exited with status {} during initialization'.format(self.process.returncode)))
test_framework.test_node.FailedToStartError: [node 1] bitcoind exited with status -6 during initialization
2019-03-23T10:23:23.266000Z TestFramework (INFO): Stopping nodes
stderr:
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/feature_segwit.py", line 597, in <module>
    SegWitTest().main()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 200, in main
    self.stop_nodes()
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 379, in stop_nodes
    node.stop_node(wait=wait)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_node.py", line 254, in stop_node
    self.stop(wait=wait)
  File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_node.py", line 168, in __getattr__
    assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")
AssertionError: [node 1] Error: no RPC connection
```
Observed in #15652.

**Comment by promag** [comment]
It isn't sporadic failure, my bad, it was due to `POTENTIAL DEADLOCK DETECTED`.
