### ISSUE TITLE
Failure in wallet_import_rescan.py

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#15865]
Appveyor build failed for #15849 in https://ci.appveyor.com/project/DrahtBot/bitcoin/builds/23959262:

```
 test  2019-04-19T01:01:12.401000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "C:\projects\bitcoin\test\functional\test_framework\test_framework.py", line 175, in main
                                       self.run_test()
                                     File "C:\projects\bitcoin/test/functional/wallet_import_rescan.py", line 185, in run_test
                                       variant.check()
                                     File "C:\projects\bitcoin/test/functional/wallet_import_rescan.py", line 78, in check
                                       assert_equal(len(txs), self.expected_txs)
                                     File "C:\projects\bitcoin\test\functional\test_framework\util.py", line 39, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(1 == 0)
 test  2019-04-19T01:01:12.405000Z TestFramework (DEBUG): Closing down network thread 
 test  2019-04-19T01:01:12.455000Z TestFramework (INFO): Stopping nodes 
 test  2019-04-19T01:01:12.455000Z TestFramework.node0 (DEBUG): Stopping node 
```

**Comment by MarcoFalke** [comment]
Would be nice if the test said which variant failed
