### ISSUE TITLE
BECH32 address signmessage failed

### ISSUE THREAD

**Issue by LongShao007** [bitcoin/bitcoin#16082]
I am testing test/functional/rpc_signmessage.py.
test code:
>         
        self.log.info('test signing with an address with wallet')
        address = self.nodes[0].getnewaddress("", "bech32")
        signature = self.nodes[0].signmessage(address, message)

report error: Address does not refer to key (-3)

> stdout:
2019-05-24T11:48:36.964000Z TestFramework (INFO): Initializing test directory /var/folders/jd/c9npkg1x7t75h7v3ctbgnpbh0000gn/T/test_runner_₿_🏃_20190524_194836/rpc_signmessage_0
2019-05-24T11:48:38.147000Z TestFramework (INFO): test signing with priv_key
2019-05-24T11:48:38.153000Z TestFramework (INFO): test signing with an address with wallet
2019-05-24T11:48:38.304000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/Users/longshao/layercoin/layercoin/test/functional/test_framework/test_framework.py", line 194, in main
    self.run_test()
  File "/Users/longshao/layercoin/layercoin/test/functional/rpc_signmessage.py", line 32, in run_test
    signature = self.nodes[0].signmessage(address, message)
  File "/Users/longshao/layercoin/layercoin/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/Users/longshao/layercoin/layercoin/test/functional/test_framework/authproxy.py", line 141, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Address does not refer to key (-3)
2019-05-24T11:48:38.364000Z TestFramework (INFO): Stopping nodes
2019-05-24T11:48:38.679000Z TestFramework (WARNING): Not cleaning up dir /var/folders/jd/c9npkg1x7t75h7v3ctbgnpbh0000gn/T/test_runner_₿_🏃_20190524_194836/rpc_signmessage_0
2019-05-24T11:48:38.679000Z TestFramework (ERROR): Test failed. Test logging available at /var/folders/jd/c9npkg1x7t75h7v3ctbgnpbh0000gn/T/test_runner_₿_🏃_20190524_194836/rpc_signmessage_0/test_framework.log
2019-05-24T11:48:38.680000Z TestFramework (ERROR): Hint: Call /Users/longshao/layercoin/layercoin/test/functional/combine_logs.py '/var/folders/jd/c9npkg1x7t75h7v3ctbgnpbh0000gn/T/test_runner_₿_🏃_20190524_194836/rpc_signmessage_0' to consolidate all logs

**Comment by MarcoFalke** [comment]
How is this different from #10542
