### ISSUE TITLE
p2p_sendheaders intermittent assert failure

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#16511]
On current master:

https://travis-ci.org/bitcoin/bitcoin/jobs/566158943#L4229

```
[0;36m test  2019-07-31T20:25:52.638000Z TestFramework (DEBUG): Part 3.0: starting... [0m
[0;36m test  2019-07-31T20:25:52.658000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_inv(inv=[CInv(type=Block hash=3ac0b282214dbd9f3df359970e6866211a6520b5b43af399adadc22d803eba71)]) [0m
[0;36m test  2019-07-31T20:25:52.659000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_headers(headers=[CBlockHeader(nVersion=536870912 hashPrevBlock=5c3baebd28e1571e7dbb555d881c948483d9088aa861125b824acbad53c28343 hashMerkleRoot=ebaaaaec33cd2173d02b6f872b0d6554c8f3cb9b0565c0b12e4107b777c5de39 nTime=Wed Jul 31 20:28:01 2019 nBits=207fffff nNonce=00000002)]) [0m
[0;36m test  2019-07-31T20:25:52.711000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_inv(inv=[CInv(type=Block hash=39990c4872eda3d6eae48702d19e03f53f78ac0f414798654bd425588c8260b1)]) [0m
[0;36m test  2019-07-31T20:25:52.711000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_headers(headers=[CBlockHeader(nVersion=536870912 hashPrevBlock=3ac0b282214dbd9f3df359970e6866211a6520b5b43af399adadc22d803eba71 hashMerkleRoot=24b8935b8a35515750727253705c6d212d825ade820c679d5537e4dffd4e17d4 nTime=Wed Jul 31 20:28:01 2019 nBits=207fffff nNonce=00000001), CBlockHeader(nVersion=536870912 hashPrevBlock=333d93df4d276020f7ad5afbc78306b65720d442ff96a6d10c116ba19ed16d41 hashMerkleRoot=12e4e72d8de49339870f50f4d13b31a54cb39b301cce51e0ebb686dee1d9a23f nTime=Wed Jul 31 20:28:02 2019 nB... (msg truncated) [0m
[0;36m test  2019-07-31T20:25:52.738000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_inv(inv=[CInv(type=Block hash=5cab461a6ae9f611e74425c8e8f7b40c4014bde3d94a21d8c878bd2184e7b78d)]) [0m
[0;36m test  2019-07-31T20:25:52.739000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_headers(headers=[CBlockHeader(nVersion=536870912 hashPrevBlock=39990c4872eda3d6eae48702d19e03f53f78ac0f414798654bd425588c8260b1 hashMerkleRoot=26835ce53b32410839073a4c782d8ffaa65b0008810ef4705d8e7f9dea96f04e nTime=Wed Jul 31 20:28:02 2019 nBits=207fffff nNonce=00000001)]) [0m
[0;36m test  2019-07-31T20:25:52.823000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_inv(inv=[CInv(type=Block hash=70b106fed18037728a76ccd381ded27a805c2603ce3b482076be784efa531be4)]) [0m
[0;36m test  2019-07-31T20:25:52.824000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_headers(headers=[CBlockHeader(nVersion=536870912 hashPrevBlock=5cab461a6ae9f611e74425c8e8f7b40c4014bde3d94a21d8c878bd2184e7b78d hashMerkleRoot=39553288127c7e8800c78859da8478e0b651fad39bcb05754c1c7b81973f411c nTime=Wed Jul 31 20:28:02 2019 nBits=207fffff nNonce=00000002), CBlockHeader(nVersion=805306369 hashPrevBlock=51df1ac285d81a5ae9e3d14ef2096c7a761b9ec9385968506b8924aa8aea0933 hashMerkleRoot=6033bc8c64cc42320e9165dff90f86dbdba1f815de2a0582718309b979f26196 nTime=Wed Jul 31 20:28:03 2019 nB... (msg truncated) [0m
[0;36m test  2019-07-31T20:25:53.131000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_inv(inv=[CInv(type=Block hash=5b8ce7ec0020c86202d5e9be290d9042e4de8f8e8f15eedcf0ac287c8133e5d7)]) [0m
[0;36m test  2019-07-31T20:25:53.131000Z TestFramework (ERROR): Assertion failed [0m
[0;36m                                   Traceback (most recent call last):[0m
[0;36m                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 194, in main[0m
[0;36m                                       self.run_test()[0m
[0;36m                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/p2p_sendheaders.py", line 251, in run_test[0m
[0;36m                                       self.test_nonnull_locators(test_node, inv_node)[0m
[0;36m                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/p2p_sendheaders.py", line 391, in test_nonnull_locators[0m
[0;36m                                       inv_node.check_last_inv_announcement(inv=[tip])[0m
[0;36m                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/p2p_sendheaders.py", line 201, in check_last_inv_announcement[0m
[0;36m                                       assert_equal(compare_inv, inv)[0m
[0;36m                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-unknown-linux-gnu/test/functional/test_framework/util.py", line 40, in assert_equal[0m
[0;36m                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))[0m
[0;36m                                   AssertionError: not([41409428476113223255192969369482679161918128667860769936355059641104093930967] == [32595223059935184488573604912883429905813935033258460853993330943583545499636])[0m
[0;36m test  2019-07-31T20:25:53.133000Z TestFramework (DEBUG): Closing down network thread [0m
[0;36m test  2019-07-31T20:25:53.134000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_headers(headers=[CBlockHeader(nVersion=536870912 hashPrevBlock=5c3baebd28e1571e7dbb555d881c948483d9088aa861125b824acbad53c28343 hashMerkleRoot=7456136c7fef4df871dbf15e3f3be1f97185ceecbc5290c645855ffc7918a4bf nTime=Wed Jul 31 20:28:01 2019 nBits=207fffff nNonce=00000000), CBlockHeader(nVersion=536870912 hashPrevBlock=0f26c8444a9a76592402f7b21ec7fe974954ae76369afeab4f7a02ab5d84dfc0 hashMerkleRoot=0f57d3f446560a9b1112d7385fc99464b8c539526aff809adf710175e05314a6 nTime=Wed Jul 31 20:28:01 2019 nB... (msg truncated) [0m
[0;36m test  2019-07-31T20:25:53.134000Z TestFramework.mininode (DEBUG): Received message from 127.0.0.1:12296: msg_inv(inv=[CInv(type=Block hash=48103e1291c43c92c25ab7fedc43f70d1d6df9162e10928b8a63fc0203f09ff4)]) [0m
[0;36m test  2019-07-31T20:25:53.183000Z TestFramework (INFO): Stopping nodes [0m

**Comment by adamjonas** [comment]
Checking in on this. Looking over the last two weeks of broken builds, this doesn't seem to be a culprit. Should this remain open?

**Comment by MarcoFalke** [comment]
Yeah, let's revisit the next time this is seen.

**Comment by MarcoFalke** [comment]
Still an issue https://travis-ci.org/github/bitcoin/bitcoin/jobs/694214009#L7009
