### ISSUE TITLE
Bus error (core dumped) after "Using obfuscation key for" log line

### ISSUE THREAD

**Issue by alevchuk** [bitcoin/bitcoin#16904]
bitcoind is crashing on startup

**Expected behavior**

It worked fine on this same hardware for years

**Actual behavior**
```
2019-09-18T12:43:58Z LevelDB using max_open_files=1000 (default=1000)
2019-09-18T12:43:58Z Opening LevelDB in /home/bitcoin/.bitcoin/blocks/index
2019-09-18T12:43:58Z leveldb: Recovering log #1159
2019-09-18T12:44:00Z leveldb: Delete type=0 #1159
2019-09-18T12:44:00Z leveldb: Delete type=3 #1158
2019-09-18T12:44:00Z Opened LevelDB successfully
2019-09-18T12:44:00Z Using obfuscation key for /home/bitcoin/.bitcoin/blocks/index: 0000000000000000
Bus error (core dumped)
```

**System information**

self-compiled from this github repo from b3067f4338d901394fb0237567cb5e19ccee5f8a

2019-09-18T02:44:13Z Bitcoin Core version v0.18.99.0-b3067f4 (release build)

Linux 4.15.0-42-generic #45~16.04.1+8.0trisquel3 SMP Tue Dec 4 11:28:55 UTC 2018 x86_64 x86_64 x86_64 GNU/Linux

I have bitcoind and the data on BTRFS mirrored across two drives. BTFS Scrub found errors yet all were correctable. When re-running BTRFS scrub 0 errors are reported.

```
gdb bitcoind
...
Reading symbols from bitcoind...done.
(gdb) r
Starting program: /mnt/btrfs/bitcoin/bin/bin/bitcoind
[Thread debugging using libthread_db enabled]
...
2019-09-18T03:28:55Z Opened LevelDB successfully
2019-09-18T12:43:58Z Opening LevelDB in /home/bitcoin/.bitcoin/blocks/index
2019-09-18T12:43:58Z leveldb: Recovering log #1159
2019-09-18T12:44:00Z leveldb: Delete type=0 #1159
2019-09-18T12:44:00Z leveldb: Delete type=3 #1158

2019-09-18T03:28:55Z Using obfuscation key for /home/bitcoin/.bitcoin/blocks/index: 0000000000000000

Thread 1 "bitcoin-init" received signal SIGBUS, Bus error.
leveldb::ReadBlock (file=0x55555dadb740, options=..., handle=..., result=result@entry=0x7fffffffa100) at leveldb/table/format.cc:91
91          const uint32_t crc = crc32c::Unmask(DecodeFixed32(data + n + 1));

(gdb) bt
#0  leveldb::crc32c::Unmask (masked_crc=<optimized out>) at ./leveldb/util/crc32c.h:39
#1  leveldb::ReadBlock (file=0x55555dadb740, options=..., handle=..., result=result@entry=0x7fffffffa100) at leveldb/table/format.cc:91
#2  0x000055555590854c in leveldb::Table::BlockReader (arg=0x55555a0ef0d0, options=..., index_value=...) at leveldb/table/table.cc:189
#3  0x000055555590b2c6 in leveldb::(anonymous namespace)::TwoLevelIterator::InitDataBlock (this=this@entry=0x55555dadb930)
    at leveldb/table/two_level_iterator.cc:165
#4  0x000055555590b370 in leveldb::(anonymous namespace)::TwoLevelIterator::SkipEmptyDataBlocksForward (this=0x55555dadb930)
    at leveldb/table/two_level_iterator.cc:133
#5  0x000055555590b545 in leveldb::IteratorWrapper::Next (this=0x555555e15b30) at ./leveldb/table/iterator_wrapper.h:45
#6  leveldb::(anonymous namespace)::TwoLevelIterator::Next (this=0x555555e15ac0) at leveldb/table/two_level_iterator.cc:114
#7  0x0000555555905d47 in leveldb::IteratorWrapper::Next (this=<optimized out>) at ./leveldb/table/iterator_wrapper.h:45
#8  leveldb::(anonymous namespace)::MergingIterator::Next (this=0x555555e15b80) at leveldb/table/merger.cc:81
#9  0x00005555558f2540 in leveldb::(anonymous namespace)::DBIter::FindNextUserEntry (this=0x555555e15c70, skipping=true, skip=0x555555e15cc0)
    at leveldb/db/db_iter.cc:199
#10 0x00005555556dc32b in CBlockTreeDB::LoadBlockIndexGuts(Consensus::Params const&, std::function<CBlockIndex* (uint256 const&)>) (this=<optimized out>,
    consensusParams=..., insertBlockIndex=...) at txdb.cpp:280
#11 0x000055555572f3ee in BlockManager::LoadBlockIndex (this=this@entry=0x555555c77ee0 <(anonymous namespace)::g_blockman>, consensus_params=...,
    blocktree=..., block_index_candidates=std::set with 0 elements) at validation.cpp:3820
#12 0x000055555572fa71 in LoadBlockIndexDB (chainparams=...) at validation.cpp:3883
#13 0x0000555555730445 in LoadBlockIndex (chainparams=...) at validation.cpp:4344
#14 0x00005555555a6ca9 in AppInitMain (interfaces=...) at init.cpp:1497
#15 0x000055555558c1e9 in AppInit (argc=<optimized out>, argv=<optimized out>) at bitcoind.cpp:164
#16 0x000055555558436f in main (argc=1, argv=0x7fffffffe648) at bitcoind.cpp:194
````

**Comment by MarcoFalke** [comment]
I could imagine that the disk errors corrupted (other parts of) the database earlier. So while some of them could be fixed, the db might stay corrupted.

**Comment by alevchuk** [comment]
Would a friendlier message be useful, e.g. "leveldb database is corrupted, go to wiki page X"?

**Comment by MarcoFalke** [comment]
Yeah, but I am not sure if SIGBUS from leveldb can be caught and thrown as an error message instead.

**Comment by laanwj** [comment]
I'm sure it's possible for leveldb to recognize this kind of corruption, instead of blindly trusting what is on disk. However this is an upstream problem.

I'd suggest creating a minimum reproducible example and filing an issue with leveldb/leveldb.
