### ISSUE TITLE
gui: RPC responses should not be translated

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17072]
Steps to reproduce:

```
$ XDG_SESSION_TYPE=""  QT_QPA_PLATFORM=minimal LC_ALL=de_DE.UTF-8 BITCOIND=bitcoin-qt ./test/functional/wallet_basic.py 
2019-10-07T14:43:13.778000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_or0h2c7y
2019-10-07T14:43:15.630000Z TestFramework (INFO): Mining blocks...
2019-10-07T14:43:17.819000Z TestFramework (INFO): test gettxout
2019-10-07T14:43:17.842000Z TestFramework (INFO): test gettxout (second part)
2019-10-07T14:43:18.896000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/marco/workspace/btc_bitcoin_core/test/functional/test_framework/util.py", line 122, in try_rpc
    fun(*args, **kwds)
  File "/home/marco/workspace/btc_bitcoin_core/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/marco/workspace/btc_bitcoin_core/test/functional/test_framework/authproxy.py", line 141, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Ungenügendes Guthaben (-4)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/marco/workspace/btc_bitcoin_core/test/functional/test_framework/test_framework.py", line 194, in main
    self.run_test()
  File "./test/functional/wallet_basic.py", line 120, in run_test
    assert_raises_rpc_error(-4, "Insufficient funds", self.nodes[2].sendtoaddress, self.nodes[2].getnewaddress(), 20)
  File "/home/marco/workspace/btc_bitcoin_core/test/functional/test_framework/util.py", line 114, in assert_raises_rpc_error
    assert try_rpc(code, message, fun, *args, **kwds), "No exception raised"
  File "/home/marco/workspace/btc_bitcoin_core/test/functional/test_framework/util.py", line 130, in try_rpc
    message, e.error['message']))
AssertionError: Expected substring not found in error message:
substring: 'Insufficient funds'
error message: 'Ungenügendes Guthaben'.

**Comment by laanwj** [comment]
Crap. Does the bilingual message stuff help to address this?

**Comment by MarcoFalke** [comment]
> Crap. Does the bilingual message stuff help to address this?

It does.

I have fixes for it locally, but I won't submit them before #17070 is merged, as both bugfixes conflict with each other.
