### ISSUE TITLE
intermittent functional test failure in wallet_bumpfee

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17716]
https://travis-ci.org/bitcoin/bitcoin/jobs/623304089#L8090

```
 test  2019-12-10T18:32:57.082000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-s390x-unknown-linux-gnu/test/functional/test_framework/test_framework.py", line 112, in main
                                       self.run_test()
                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-s390x-unknown-linux-gnu/test/functional/wallet_bumpfee.py", line 90, in run_test
                                       test_small_output_with_feerate_succeeds(rbf_node, dest_address)
                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-s390x-unknown-linux-gnu/test/functional/wallet_bumpfee.py", line 224, in test_small_output_with_feerate_succeeds
                                       assert_equal(len(input_list), 1)
                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-s390x-unknown-linux-gnu/test/functional/test_framework/util.py", line 46, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(16 == 1)

**Comment by MarcoFalke** [comment]
Another one: https://travis-ci.org/bitcoin/bitcoin/jobs/660197025#L4359

**Comment by MarcoFalke** [comment]
The test has been written in d08becff853 and 38516f90784 by @instagibbs 

For me it is hard to dig through the combined logs, because the test has zero logging (Other than `self.log.info("Running tests")`). It would be nice if at least this function got a debug or info log statement to explain what is going on.

**Comment by instagibbs** [comment]
I'll take a look this week.

**Comment by instagibbs** [comment]
@MarcoFalke I believe I've figured it out. Apologies for the sloppy test: https://github.com/bitcoin/bitcoin/pull/18311
