### ISSUE TITLE
test: rpc_bind.py --ipv4 fails when run on s390x or arm in debian

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#17765]
Commit fa52a2c7b81817694c3aeddb7f6909334b8c9132

Steps to reproduce:

```
FILE_ENV="./ci/test/00_setup_env_arm.sh" MAKEJOBS="-j9" ./ci/test_run_all.sh
```

```
 node0 2019-12-17T20:54:35.953253Z [] ThreadRPCServer method=getblockcount user=__cookie__ 
 test  2019-12-17T20:54:35.959000Z TestFramework.node0 (DEBUG): RPC successfully started 
 test  2019-12-17T20:54:35.966000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/home/marco/bitcoin/build/bitcoin-arm-linux-gnueabihf/test/functional/test_framework/test_framework.py", line 112, in main
                                       self.run_test()
                                     File "/home/marco/bitcoin/build/bitcoin-arm-linux-gnueabihf/test/functional/rpc_bind.py", line 89, in run_test
                                       self._run_loopback_tests()
                                     File "/home/marco/bitcoin/build/bitcoin-arm-linux-gnueabihf/test/functional/rpc_bind.py", line 97, in _run_loopback_tests
                                       [('127.0.0.1', self.defaultport)])
                                     File "/home/marco/bitcoin/build/bitcoin-arm-linux-gnueabihf/test/functional/rpc_bind.py", line 43, in run_bind_test
                                       assert_equal(set(get_bind_addrs(pid)), set(expected))
                                     File "/home/marco/bitcoin/build/bitcoin-arm-linux-gnueabihf/test/functional/test_framework/util.py", line 46, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(set() == {('7f000001', 16456)})

**Comment by MarcoFalke** [comment]
Same without qemu: https://travis-ci.org/bitcoin/bitcoin/jobs/626507536#L17592

**Comment by MarcoFalke** [comment]
Same for arm: https://travis-ci.org/bitcoin/bitcoin/jobs/626507535#L18242

**Comment by laanwj** [comment]
This gives me the suspicion that some container-ism prevents `get_bind_addrs` from working (which relies on `/proc` being accessible, for one)

**Comment by MarcoFalke** [comment]
Jup, I think docker is to blame. However, I can't reproduce locally:

```
# ls /.dockerenv && uname -a && cat /etc/debian_version && ./test/functional/rpc_bind.py --ipv4
/.dockerenv
Linux e5c4bf14a0c2 4.15.0-1049-raspi2 #53-Ubuntu SMP PREEMPT Wed Oct 2 01:04:00 UTC 2019 aarch64 GNU/Linux
bullseye/sid
2019-12-18T18:20:14.319000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_7xx50ox6
2019-12-18T18:20:14.323000Z TestFramework (INFO): Check for linux
2019-12-18T18:20:14.323000Z TestFramework (INFO): Check for ipv6
2019-12-18T18:20:14.325000Z TestFramework (INFO): Check for non-loopback interface
2019-12-18T18:20:14.327000Z TestFramework (INFO): Bind test for ['127.0.0.1']
2019-12-18T18:20:15.587000Z TestFramework (INFO): Bind test for ['127.0.0.1:32171']
2019-12-18T18:20:16.482000Z TestFramework (INFO): Bind test for ['127.0.0.1:32171', '127.0.0.1:32172']
2019-12-18T18:20:17.332000Z TestFramework (INFO): Stopping nodes
2019-12-18T18:20:17.333000Z TestFramework (INFO): Cleaning up /tmp/bitcoin_func_test_7xx50ox6 on exit
2019-12-18T18:20:17.335000Z TestFramework (INFO): Tests successful

**Comment by MarcoFalke** [comment]
This was caused by running qemu in docker in lxd for the native platform. Fixed in https://github.com/bitcoin/bitcoin/pull/17767/commits/fa762775db8c26df0106f5b1fa79862fbb41c6c2

**Comment by MarcoFalke** [comment]
Same happens in valgrind: https://travis-ci.org/github/bitcoin/bitcoin/jobs/665198660#L2913
