### ISSUE TITLE
test feature_backwards_compatibility fails with "Transaction not eligible for abandonment"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18161]
https://travis-ci.org/bitcoin/bitcoin/jobs/651074136#L4185

**Comment by ryanofsky** [comment]
I saw this error again in #15937 on what appears to be the same line `self.nodes[1].abandontransaction(tx3_id)` of the same `feature_backwards_compatibility.py` test and same travis target "x86_64 Linux [GOAL: install] [bionic] [previous releases, uses qt5 dev package and some depends packages] [unsigned char]":

https://travis-ci.org/github/bitcoin/bitcoin/jobs/711190846#L8819

Unfortunately I restarted the job and lost the complete log, but captured:

```
test  2020-07-23T18:24:53.367000Z TestFramework (ERROR): JSONRPC error 
                                   Traceback (most recent call last):
                                     File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 118, in main
                                       self.run_test()
                                     File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_backwards_compatibility.py", line 106, in run_test
                                       self.nodes[1].abandontransaction(tx3_id)
                                     File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 47, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                     File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 146, in __call__
                                       raise JSONRPCException(response['error'], status)
                                   test_framework.authproxy.JSONRPCException: Transaction not eligible for abandonment (-5)
```
