### ISSUE TITLE
wallet_bumpfee fails with AssertionError in test_dust_to_fee

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18511]
Example:

* https://travis-ci.org/github/bitcoin/bitcoin/jobs/670311100#L8042

```
test  2020-04-02T21:26:28.988000Z TestFramework (ERROR): Assertion failed 

                                   Traceback (most recent call last):

                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 112, in main

                                       self.run_test()

                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_bumpfee.py", line 84, in run_test

                                       test_dust_to_fee(self, rbf_node, dest_address)

                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_bumpfee.py", line 257, in test_dust_to_fee

                                       assert_equal(fulltx["vsize"], 141)

                                     File "/home/travis/build/bitcoin/bitcoin/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 46, in assert_equal

                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))

                                   AssertionError: not(140 == 141)

**Comment by MarcoFalke** [comment]
@jonatack The assertion has been added by you.  While unlikely, the witness might sometimes be smaller and thus give a lower tx vsize. So that test should probably be relaxed.

**Comment by MarcoFalke** [comment]
The bump feerate might have to be increased to `350200` or so, because of the smaller tx size, but I haven't checked.

**Comment by jonatack** [comment]
On it :+1:
