### ISSUE TITLE
Multiple bitcoind instances can point to the same -walletdir on Windows

### ISSUE THREAD

**Issue by mtrycz** [bitcoin/bitcoin#18622]
I was building Bitcoin Core on my Windows machine, on WSL/Ubuntu. I tried to run the tests and ran into a problem. The test in `test/functional/wallet_multiwallet.py` failed. Follows the output of the test: 

```
mtrycz@LAPTOP-00AACAV2:~/git/bitcoin/test/functional$ ./test_runner.py wallet_multiwallet.py
Temporary test directory at /tmp/test_runner_₿_🏃_20200413_152720
Remaining jobs: [wallet_multiwallet.py]
1/1 - wallet_multiwallet.py failed, Duration: 9 s

stdout:
2020-04-13T13:27:20.407000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20200413_152720/wallet_multiwallet_0
2020-04-13T13:27:24.947000Z TestFramework (INFO): Do not allow -zapwallettxes with multiwallet
2020-04-13T13:27:25.745000Z TestFramework (INFO): Do not allow -salvagewallet with multiwallet
2020-04-13T13:27:26.278000Z TestFramework (INFO): Do not allow -upgradewallet with multiwallet
2020-04-13T13:27:29.060000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/mtrycz/git/bitcoin/test/functional/test_framework/test_framework.py", line 112, in main
    self.run_test()
  File "/home/mtrycz/git/bitcoin/test/functional/wallet_multiwallet.py", line 152, in run_test
    self.nodes[1].assert_start_raises_init_error(['-walletdir=' + competing_wallet_dir], exp_stderr, match=ErrorMatch.PARTIAL_REGEX)
  File "/home/mtrycz/git/bitcoin/test/functional/test_framework/test_node.py", line 460, in assert_start_raises_init_error
    self._raise_assertion_error(assert_msg)
  File "/home/mtrycz/git/bitcoin/test/functional/test_framework/test_node.py", line 157, in _raise_assertion_error
    raise AssertionError(self._node_msg(msg))
AssertionError: [node 1] bitcoind should have exited with expected error Error: Error initializing wallet database environment \"\S+competing_walletdir\"!
2020-04-13T13:27:29.113000Z TestFramework (INFO): Stopping nodes
2020-04-13T13:27:29.215000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20200413_152720/wallet_multiwallet_0
2020-04-13T13:27:29.215000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20200413_152720/wallet_multiwallet_0/test_framework.log
2020-04-13T13:27:29.215000Z TestFramework (ERROR): Hint: Call /home/mtrycz/git/bitcoin/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20200413_152720/wallet_multiwallet_0' to consolidate all logs


stderr:



TEST                  | STATUS    | DURATION

wallet_multiwallet.py | ✖ Failed  | 9 s

ALL                   | ✖ Failed  | 9 s (accumulated)
Runtime: 9 s
```

I traced the cause to a node being able to open a wallet that is already open by another node. 

To the best of my understanding mutliple bitcoind instances shouldn't be able to point to the same datadirs or walletdirs. On Windows it is possible to have multiple bitcoind instances to point to the same walletdir, leading to possible data corruption. To the best of my understanding this is not possible on Linux (can't confirm atm).

Manual test plan:
1. Download the latest Windows release binaries (version v.0.19.1)
1. Create two directories, for example `C:\node0` and `C:\node1`; create a `bitcoin.conf` file in `C:\node1` with a single line `rpcport=8333` (otherwise the second node will fail for an unrelated reason)
1. Open a command prompt and run `bitcoind.exe -datadir=C:\node0 -walletdir=D:\bchwallettest`
2. Open a second prompt and run `bitcoind.exe -datadir=C:\node1 -walletdir=D:\bchwallettest`
3. Expect the second node to fail at startup

I've run this test myself and can confirm that the second node erroneously starts. The bug was reproduced on Windows 10 Pro, both in cmd and in WSL shell, with the latest release v.0.19.1.

**Comment by emilengler** [comment]
Having a bitcoin.conf with only rpcport set will fail anyway

**Comment by emilengler** [comment]
Can't reproduce on Debian 10.
I get the following error when I start the second node:
```
2020-04-15T10:04:42Z ERROR: Error while attempting to lock directory /home/eengler/walletdir: Resource temporarily unavailable
2020-04-15T10:04:42Z Cannot obtain a lock on wallet directory /home/eengler/walletdir. Another instance of bitcoin may be using it.
2020-04-15T10:04:42Z Error: Error initializing wallet database environment "/home/eengler/walletdir"!
Error: Error initializing wallet database environment "/home/eengler/walletdir"!
```
which is good

**Comment by meshcollider** [comment]
I can reproduce the `wallet_multiwallet.py` test failure on WSL. I can also start two nodes pointing to the same data directory with no issue. `feature_filelock.py` and `tool_wallet.py` fail for apparently the same reason. Seems like the `.lock` file is created but is being ignored.

**Comment by meshcollider** [comment]
Seems this is the cause : https://github.com/microsoft/WSL/issues/1927
