### ISSUE TITLE
Intermittent failure in feature_backwards_compatibility "Transaction not eligible for abandonment"

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#18831]
https://travis-ci.org/github/bitcoin/bitcoin/jobs/679885530#L8791

**Comment by dongcarl** [comment]
Ran into this intermittently here: https://cirrus-ci.com/task/5461065460875264

**Comment by fanquake** [comment]
Have just seen this again in https://cirrus-ci.com/task/6443435432345600?command=ci#L1122.

Full log: https://gist.github.com/fanquake/42b629f3bf621b21e9f1b7faf5ecaab4.

**Comment by practicalswift** [comment]
Adding another data point.

Observed yesterday:

"Transaction not eligible for abandonment (-5)" when running `feature_backwards_compatibility.py --descriptors`.

See [Cirrus CI log](https://cirrus-ci.com/task/4642640135192576?command=ci#L1067) for details.

```
…
2021-03-03T15:48:25.376000Z TestFramework (INFO): Test wallet backwards compatibility...
2021-03-03T15:49:20.236000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 128, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_backwards_compatibility.py", line 109, in run_test
    self.nodes[1].abandontransaction(tx3_id)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 146, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Transaction not eligible for abandonment (-5)
```
