### ISSUE TITLE
Small memory leak when BerkeleyEnvironment::Open fails

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#19034]
Originally reported https://github.com/bitcoin/bitcoin/pull/18907#issuecomment-631153346

This happens when trying to load a wallet with corrupt logs. It can be reproduced running the wallet_db.py test from #18907@[`c6a2c26`](https://github.com/bitcoin/bitcoin/commits/c6a2c265f5d0b424fc8226c2f3426e82856779d0). From https://travis-ci.org/github/bitcoin/bitcoin/jobs/689013660#L4659: 

```
==2504==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 65840 byte(s) in 2 object(s) allocated from:
    #0 0x55b144d4adb3 in __interceptor_malloc (/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/bitcoind+0x1c75db3)
    #1 0x7f0207036cc4 in __os_malloc (/usr/lib/x86_64-linux-gnu/libdb_cxx-5.3.so+0x162cc4)
    #2 0x19f3b1afb25218ff  (<unknown module>)
SUMMARY: AddressSanitizer: 65840 byte(s) leaked in 2 allocation(s). 
```

The leak is known to happen at commits 274b9909f64aa617eb322850b799bc38c04f5f0c (initial commit) and e78c6820232865f21777bfeefadac0a1aea1fde2 (attempted fix) from #18907

This is probaby not a very severe issue, but it'd be good to track down the leak, fix it, and add the wallet_db test to have some test coverage for log recovery. All of this can be done independently of #18907, before or after it is merged.

**Comment by ryanofsky** [comment]
Opened #20974 to test this. Leak does still happen https://cirrus-ci.com/task/5428735379767296?command=ci#L4680

```
==36296==ERROR: LeakSanitizer: detected memory leaks
Direct leak of 65840 byte(s) in 2 object(s) allocated from:
    #0 0x55fe2c45d3bd in malloc (/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/src/bitcoind+0x17733bd)
    #1 0x7f03e35788c4 in __os_malloc (/lib/x86_64-linux-gnu/libdb_cxx-5.3.so+0x1698c4)
SUMMARY: AddressSanitizer: 65840 byte(s) leaked in 2 allocation(s). 
```
