### ISSUE TITLE
qa: Intermittent AssertionError in `wallet_address_types.py`

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#19139]
https://travis-ci.org/github/bitcoin/bitcoin/jobs/692067912#L5040

**Comment by hebasto** [comment]
One more: https://travis-ci.org/github/bitcoin/bitcoin/jobs/721444891#L3297

**Comment by meshcollider** [comment]
Do we have any more recent failures? Both logs linked have expired. If this hasn't been seen recently then I think this can be closed.

**Comment by MarcoFalke** [comment]
It would be good to include an excerpt the next time this is seen

**Comment by meshcollider** [comment]
There is a failure in this test here: https://cirrus-ci.com/task/5241926094946304

But it isn't an AssertionError so it is likely a different issue.

```
 test  2021-09-24T01:58:57.531000Z TestFramework (ERROR): Unexpected exception caught during testing 
                                   Traceback (most recent call last):
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 131, in main
                                       self.run_test()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\wallet_address_types.py", line 299, in run_test
                                       self.sync_mempools()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 673, in sync_mempools
                                       r.syncwithvalidationinterfacequeue()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\coverage.py", line 49, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\authproxy.py", line 144, in __call__
                                       response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\authproxy.py", line 107, in _request
                                       self.__conn.request(method, path, postdata, headers)
                                     File "C:\Python39\lib\http\client.py", line 1257, in request
                                       self._send_request(method, url, body, headers, encode_chunked)
                                     File "C:\Python39\lib\http\client.py", line 1303, in _send_request
                                       self.endheaders(body, encode_chunked=encode_chunked)
                                     File "C:\Python39\lib\http\client.py", line 1252, in endheaders
                                       self._send_output(message_body, encode_chunked=encode_chunked)
                                     File "C:\Python39\lib\http\client.py", line 1012, in _send_output
                                       self.send(msg)
                                     File "C:\Python39\lib\http\client.py", line 952, in send
                                       self.connect()
                                     File "C:\Python39\lib\http\client.py", line 923, in connect
                                       self.sock = self._create_connection(
                                     File "C:\Python39\lib\socket.py", line 843, in create_connection
                                       raise err
                                     File "C:\Python39\lib\socket.py", line 831, in create_connection
                                       sock.connect(sa)
                                   OSError: [WinError 10048] Only one usage of each socket address (protocol/network address/port) is normally permitted
```

**Comment by MarcoFalke** [comment]
Maybe https://github.com/bitcoin/bitcoin/pull/23089#discussion_r716001089

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?
