### ISSUE TITLE
Three UBSan warnings when loading corrupt mempool.dat files

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#19278]
I noticed three UBSan warnings that are reachable when loading corrupt `mempool.dat` files.

```
$ xxd -p -r > mempool.dat-crashes-in-validation.cpp-5064 <<EOF
0100000000000000000000000004000000000000000000000000ffffffff
ffffff7f00000000000000000000000000
EOF
$ cp mempool.dat-crashes-in-validation.cpp-5064 ~/.bitcoin/regtest/mempool.dat
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1:report_error_type=1" src/bitcoind -regtest
validation.cpp:5064:23: runtime error: signed integer overflow: 9223372036854775807 + 1209600 cannot be represented in type 'long'
    #0 0x5573a5a07a8b in LoadMempool(CTxMemPool&, std::function<_IO_FILE* (boost::filesystem::path const&, char const*)>) src/validation.cpp:5064:23
    #1 0x5573a52cce12 in ThreadImport(ChainstateManager&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >) src/init.cpp:750:9
    #2 0x5573a52cbef7 in AppInitMain(util::Ref const&, NodeContext&)::$_9::operator()() const src/init.cpp:1845:48
```

```
$ xxd -p -r > mempool.dat-crashes-in-util-moneystr.cpp-16a <<EOF
010000000000000000050900000000000509000000000000800000000000
0000000000000000000000800000000000
EOF
$ cp mempool.dat-crashes-in-util-moneystr.cpp-16a ~/.bitcoin/regtest/mempool.dat
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1:report_error_type=1" src/bitcoind -regtest
util/moneystr.cpp:16:34: runtime error: negation of -9223372036854775808 cannot be represented in type 'CAmount' (aka 'long'); cast to an unsigned type to negate this value to itself
    #0 0x5641ce3e0aec in FormatMoney[abi:cxx11](long const&) src/util/moneystr.cpp:16:34
    #1 0x5641cd98a001 in CTxMemPool::PrioritiseTransaction(uint256 const&, long const&) src/txmempool.cpp:850:77
    #2 0x5641cdb117b4 in LoadMempool(CTxMemPool&, std::function<_IO_FILE* (boost::filesystem::path const&, char const*)>) src/validation.cpp:5061:22
    #3 0x5641cd3d6e12 in ThreadImport(ChainstateManager&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >) src/init.cpp:750:9
    #4 0x5641cd3d5ef7 in AppInitMain(util::Ref const&, NodeContext&)::$_9::operator()() const src/init.cpp:1845:48
```

```
$ xxd -p -r > mempool.dat-crashes-in-util-moneystr.cpp-16b <<EOF
0100000000000000000000000000000001253d8c0000000000000000006b
00000000f7000000ff00f7000000ff0000000000000000000000800000ff
0000
EOF
$ cp mempool.dat-crashes-in-util-moneystr.cpp-16b ~/.bitcoin/regtest/mempool.dat
$ UBSAN_OPTIONS="print_stacktrace=1:halt_on_error=1:report_error_type=1" src/bitcoind -regtest
util/moneystr.cpp:16:34: runtime error: negation of -9223372036854775808 cannot be represented in type 'CAmount' (aka 'long'); cast to an unsigned type to negate this value to itself
    #0 0x55987d51daec in FormatMoney[abi:cxx11](long const&) src/util/moneystr.cpp:16:34
    #1 0x55987cac7001 in CTxMemPool::PrioritiseTransaction(uint256 const&, long const&) src/txmempool.cpp:850:77
    #2 0x55987cc4ed6f in LoadMempool(CTxMemPool&, std::function<_IO_FILE* (boost::filesystem::path const&, char const*)>) src/validation.cpp:5092:18
    #3 0x55987c513e12 in ThreadImport(ChainstateManager&, std::vector<boost::filesystem::path, std::allocator<boost::filesystem::path> >) src/init.cpp:750:9
    #4 0x55987c512ef7 in AppInitMain(util::Ref const&, NodeContext&)::$_9::operator()() const src/init.cpp:1845:48
```

The signed integer overflow can probably be avoided simply by re-arranging the terms in the conditional (`nTime > nNow - nExpiryTimeout` instead of `nTime + nExpiryTimeout > nNow`), and the invalid negation can likely be avoided by simply checking that the delta amount is valid before calling `PrioritiseTransaction`.

**Comment by MarcoFalke** [comment]
> The signed integer overflow can probably be avoided simply by re-arranging the terms in the conditional (nTime > nNow - nExpiryTimeout

Seems reasonable. Mind creating a pr?

**Comment by practicalswift** [comment]
@MarcoFalke Actually I think this one is a good candidate for "good first issue" :)

It is a good learning opportunity for someone who is interested in UBSan and fuzzing :)  I'd be glad to coach any volunteer.

**Comment by MarcoFalke** [comment]
Ok, I've assigned good first issue to one of the fixes (https://github.com/bitcoin/bitcoin/issues/19278#issuecomment-644055262)

**Comment by MarcoFalke** [comment]
#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by rajarshimaitra** [comment]
Hi @practicalswift i have been meaning to learn fuzzing for some time. Have basic ideas, where do i start to understand it better for core? 
Willing to work on this issue.

**Comment by MarcoFalke** [comment]
See `doc/fuzzing.md`

**Comment by practicalswift** [comment]
@rajarshimaitra Great! I would suggest starting by trying to reproduce the three issues reported here by using the `LoadMempool` fuzzer from #19259 using the `libFuzzer` instructions in [`doc/fuzzing.md`](https://github.com/bitcoin/bitcoin/blob/master/doc/fuzzing.md). Are you able to hit the three issues when fuzzing? :)

**Comment by jonatack** [comment]
@rajarshimaitra You might find these informative. Marco hosted two fuzzing sessions. The third session discusses other techniques as well.
 
https://bitcoincore.reviews/17860
https://bitcoincore.reviews/18521
https://bitcoincore.reviews/17639

**Comment by rajarshimaitra** [comment]
Great, thanks for all the help guys. Will start looking into these.

**Comment by rajarshimaitra** [comment]
Hi, I have been able too reproduce the bug so far. Heres the libfuzzer log.
```
INFO: Seed: 3179298610
INFO: Loaded 1 modules   (521164 inline 8-bit counters): 521164 [0x3392d28, 0x34120f4), 
INFO: Loaded 1 PC tables (521164 PCs): 521164 [0x34120f8,0x3c05db8), 
INFO:     4602 files found in /home/raj/github-repo/qa-assets/fuzz_seed_corpus/validation_load_mempool/
INFO: -max_len is not provided; libFuzzer will not generate inputs larger than 4096 bytes
INFO: seed corpus: files: 4602 min: 1b max: 4096b total: 2882876b rss: 105Mb
util/moneystr.cpp:16:34: runtime error: negation of -9223372036854775808 cannot be represented in type 'CAmount' (aka 'long'); cast to an unsigned type to negate this value to itself
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior util/moneystr.cpp:16:34 in 
validation.cpp:5064:23: runtime error: signed integer overflow: 9223372036854775806 + 1209600 cannot be represented in type 'long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior validation.cpp:5064:23 in 
txmempool.cpp:828:15: runtime error: signed integer overflow: 1224979098644774912 + 8969489304443158649 cannot be represented in type 'long'
SUMMARY: UndefinedBehaviorSanitizer: undefined-behavior txmempool.cpp:828:15 in 
#2048	pulse  cov: 7029 ft: 26938 corp: 471/63Kb exec/s: 1024 rss: 220Mb
#4096	pulse  cov: 7053 ft: 35505 corp: 789/272Kb exec/s: 682 rss: 306Mb
```
Though it seems there's one more signed integer overflow happening at `txmempool` (new one?). I need to look further into why they are occurinng. 
My question is how do I extract these seeds from the corpus directory to investigate them further?

**Comment by rajarshimaitra** [comment]
Hi. I have successfully reproduced the bugs and fixed the relevant locations. Should I create a fresh PR or should I push it to [#19529](https://github.com/bitcoin/bitcoin/pull/19259)?

**Comment by practicalswift** [comment]
@rajarshimaitra That's excellent news! Please create a fresh PR. I'll review it right away! :)

**Comment by rajarshimaitra** [comment]
Done. :)

**Comment by MarcoFalke** [comment]
Duplicate of #20626
