### ISSUE TITLE
Intermittent CI failure: "ProcessNewBlock, block not accepted" when running feature_dersig.py

### ISSUE THREAD

**Issue by promag** [bitcoin/bitcoin#19435]
Happened with #19434 but I think it's unrelated.

From https://travis-ci.org/github/bitcoin/bitcoin/jobs/704520345#L2980-L3006
```
124/159 - feature_dersig.py failed, Duration: 34 s
stdout:
2020-07-03T02:40:05.420000Z TestFramework (INFO): Initializing test directory /home/travis/build/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20200703_021716/feature_dersig_33
2020-07-03T02:40:08.581000Z TestFramework (INFO): Mining 1249 blocks
2020-07-03T02:40:38.685000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 117, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_dersig.py", line 67, in run_test
    self.coinbase_txids = [self.nodes[0].getblock(b)['tx'][0] for b in self.nodes[0].generate(DERSIG_HEIGHT - 2)]
  File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py", line 298, in generate
    return self.generatetoaddress(nblocks=nblocks, address=self.get_deterministic_priv_key().address, maxtries=maxtries)
  File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 146, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: ProcessNewBlock, block not accepted (-32603)
2020-07-03T02:40:38.737000Z TestFramework (INFO): Stopping nodes
2020-07-03T02:40:39.291000Z TestFramework (WARNING): Not cleaning up dir /home/travis/build/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20200703_021716/feature_dersig_33
2020-07-03T02:40:39.291000Z TestFramework (ERROR): Test failed. Test logging available at /home/travis/build/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20200703_021716/feature_dersig_33/test_framework.log
2020-07-03T02:40:39.292000Z TestFramework (ERROR): 
2020-07-03T02:40:39.292000Z TestFramework (ERROR): Hint: Call /home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/combine_logs.py '/home/travis/build/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20200703_021716/feature_dersig_33' to consolidate all logs
2020-07-03T02:40:39.292000Z TestFramework (ERROR): 
2020-07-03T02:40:39.292000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2020-07-03T02:40:39.292000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2020-07-03T02:40:39.292000Z TestFramework (ERROR): 
```

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by educob** [comment]
I just installed regtest with docker. 
I use bitcoin-core javascript to generateToAddress 110 blocks.
Sometimes it runs ok other times is gives ProcessNewBlock, block not accepted
