### ISSUE TITLE
wallet_bumpfee fails with JSONRPCException: Insufficient funds

### ISSUE THREAD

**Issue by amitiuttarwar** [bitcoin/bitcoin#19615]
Looks like an intermittent failure 
Example: https://cirrus-ci.com/task/5658232037310464?command=ci#L1230

```
2020-07-23T21:59:49.107000Z TestFramework (INFO): Test that PSBT is returned for bumpfee in watchonly wallets
2020-07-23T21:59:57.738000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 118, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_bumpfee.py", line 83, in run_test
    test_watchonly_psbt(self, peer_node, rbf_node, dest_address)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_bumpfee.py", line 387, in test_watchonly_psbt
    psbt = watcher.walletcreatefundedpsbt([], {dest_address: 0.0005}, 0, {"feeRate": 0.00001}, True)['psbt']
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 146, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Insufficient funds (-4)
```

**Comment by MarcoFalke** [comment]
Let us know if this still an issue
