### ISSUE TITLE
qa: Intermittent "JSONRPCException: Transaction not eligible for abandonment" in feature_backwards_compatibility.py

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#20270]
https://travis-ci.org/github/bitcoin/bitcoin/jobs/739933963#L5172:

```
2020-10-29T17:51:09.579000Z TestFramework (INFO): Test wallet backwards compatibility...
2020-10-29T17:51:49.677000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_backwards_compatibility.py", line 108, in run_test
    self.nodes[1].abandontransaction(tx3_id)
  File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/home/travis/build/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 146, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Transaction not eligible for abandonment (-5)
2020-10-29T17:51:49.732000Z TestFramework (INFO): Stopping nodes
```

**Comment by MarcoFalke** [comment]
#18831

**Comment by hebasto** [comment]
#18161
