### ISSUE TITLE
running test/functional/feature_rbf.py

### ISSUE THREAD

**Issue by maektwain** [bitcoin/bitcoin#20501]
Initializing test directory /var/folders/2_/szwq0ctj18lbv0r9r9l0l5gw0000gn/T/bitcoin_func_test_d1dpvbes
2020-11-26T05:32:17.317000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/Users/maektwain/bitcoin/test/functional/test_framework/test_framework.py", line 125, in main
    self.setup()
  File "/Users/maektwain/bitcoin/test/functional/test_framework/test_framework.py", line 262, in setup
    self.setup_network()
  File "/Users/maektwain/bitcoin/test/functional/test_framework/test_framework.py", line 356, in setup_network
    self.setup_nodes()
  File "/Users/maektwain/bitcoin/test/functional/test_framework/test_framework.py", line 383, in setup_nodes
    self.import_deterministic_coinbase_privkeys()
  File "/Users/maektwain/bitcoin/test/functional/test_framework/test_framework.py", line 400, in import_deterministic_coinbase_privkeys
    self.init_wallet(i)
  File "/Users/maektwain/bitcoin/test/functional/test_framework/test_framework.py", line 407, in init_wallet
    n.createwallet(wallet_name=wallet_name, descriptors=self.options.descriptors, load_on_startup=True)
  File "/Users/maektwain/bitcoin/test/functional/test_framework/test_node.py", line 647, in createwallet
    return self.__getattr__('createwallet')(wallet_name, disable_private_keys, blank, passphrase, avoid_reuse, descriptors, load_on_startup)
  File "/Users/maektwain/bitcoin/test/functional/test_framework/coverage.py", line 47, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/Users/maektwain/bitcoin/test/functional/test_framework/authproxy.py", line 146, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Wallet  already exists. (-4)
2020-11-26T05:32:17.372000Z TestFramework (INFO): Stopping nodes
2020-11-26T05:32:17.745000Z TestFramework (WARNING): Not cleaning up dir /var/folders/2_/szwq0ctj18lbv0r9r9l0l5gw0000gn/T/bitcoin_func_test_d1dpvbes
2020-11-26T05:32:17.746000Z TestFramework (ERROR): Test failed. Test logging available at /var/folders/2_/szwq0ctj18lbv0r9r9l0l5gw0000gn/T/bitcoin_func_test_d1dpvbes/test_framework.log
2020-11-26T05:32:17.746000Z TestFramework (ERROR): 
2020-11-26T05:32:17.746000Z TestFramework (ERROR): Hint: Call /Users/maektwain/bitcoin/test/functional/combine_logs.py '/var/folders/2_/szwq0ctj18lbv0r9r9l0l5gw0000gn/T/bitcoin_func_test_d1dpvbes' to consolidate all logs
2020-11-26T05:32:17.746000Z TestFramework (ERROR): 
2020-11-26T05:32:17.747000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2020-11-26T05:32:17.747000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2020-11-26T05:32:17.747000Z TestFramework (ERROR): 

#### Want to work on this issue?

For guidance on contributing, please read [CONTRIBUTING.md](https://github.com/bitcoin/bitcoin/blob/master/CONTRIBUTING.md) before opening your pull request.

**Comment by MarcoFalke** [comment]
Did you run `make distclean` and re-compile before running the tests? The tests are only expected to pass for the exact commit and not other versions of Core

**Comment by maektwain** [comment]
Yeah `make distclean` did the work I am running the commits
