### ISSUE TITLE
qa: AssertionError in p2p_timeouts.py

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#20654]
https://cirrus-ci.com/task/5169692799139840?command=ci#L2606
```
18/194 - p2p_timeouts.py failed, Duration: 85 s
stdout:
2020-12-13T14:43:46.904000Z TestFramework (INFO): Initializing test directory /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20201213_064114/p2p_timeouts_177
2020-12-13T14:43:51.058000Z TestFramework.p2p (WARNING): Connection lost to 127.0.0.1:16124 due to [Errno 54] Connection reset by peer
2020-12-13T14:43:51.059000Z TestFramework.p2p (WARNING): Connection lost to 127.0.0.1:16124 due to [Errno 54] Connection reset by peer
2020-12-13T14:45:11.200000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin18/test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "/private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin18/test/functional/p2p_timeouts.py", line 90, in run_test
    assert not no_send_node.is_connected
  File "/Applications/Xcode-12.1.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.8/lib/python3.8/contextlib.py", line 120, in __exit__
    next(self.gen)
  File "/private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin18/test/functional/test_framework/test_node.py", line 393, in assert_debug_log
    self._raise_assertion_error('Expected messages "{}" does not partially match log:\n\n{}\n\n'.format(str(expected_msgs), print_log))
  File "/private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin18/test/functional/test_framework/test_node.py", line 162, in _raise_assertion_error
    raise AssertionError(self._node_msg(msg))
AssertionError: [node 0] Expected messages "['version handshake timeout from 0', 'socket no message in first 3 seconds, 1 0 from 1', 'socket no message in first 3 seconds, 0 0 from 2']" does not partially match log:
 - 2020-12-13T14:43:52.092111Z [net] socket no message in first 3 seconds, 0 0 from 2
 - 2020-12-13T14:43:52.092180Z [net] disconnecting peer=2
 - 2020-12-13T14:43:52.092300Z [net] Cleared nodestate for peer=2
 - 2020-12-13T14:44:47.321086Z [scheduler] Feeding 308 bytes of dynamic environment data into RNG
 - 2020-12-13T14:44:48.003043Z [opencon] Adding fixed seed nodes as DNS doesn't seem to be available.
2020-12-13T14:45:11.257000Z TestFramework (INFO): Stopping nodes
2020-12-13T14:45:11.959000Z TestFramework (WARNING): Not cleaning up dir /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20201213_064114/p2p_timeouts_177
2020-12-13T14:45:11.960000Z TestFramework (ERROR): Test failed. Test logging available at /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20201213_064114/p2p_timeouts_177/test_framework.log
2020-12-13T14:45:11.960000Z TestFramework (ERROR): 
2020-12-13T14:45:11.961000Z TestFramework (ERROR): Hint: Call /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin18/test/functional/combine_logs.py '/private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20201213_064114/p2p_timeouts_177' to consolidate all logs
2020-12-13T14:45:11.961000Z TestFramework (ERROR): 
2020-12-13T14:45:11.961000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2020-12-13T14:45:11.962000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2020-12-13T14:45:11.962000Z TestFramework (ERROR): 
```

**Comment by adamjonas** [comment]
For context, this has accounted for 12 of the last 571 failures (2.1%).

**Comment by Kixunil** [comment]
Do I understand correctly that this test fails because bitcoind didn't start soon enough? So it could be [same problem](https://github.com/bitcoin/bitcoin/pull/15367#issuecomment-762681497) I have?
