### ISSUE TITLE
Intermittent CI failure in interface_zmq: "Unexpected exception caught during testing" (zmq.error.Again)"

### ISSUE THREAD

**Issue by practicalswift** [bitcoin/bitcoin#20672]
```
58/194 - interface_zmq.py failed, Duration: 70 s

stdout:
2020-12-16T12:23:44.997000Z TestFramework (INFO): Initializing test directory /private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20201216_041718/interface_zmq_150
2020-12-16T12:23:48.524000Z TestFramework (INFO): Generate 5 blocks (and 5 coinbase txes)
2020-12-16T12:23:49.666000Z TestFramework (INFO): Wait for tx from second node
2020-12-16T12:23:52.478000Z TestFramework (INFO): Test the getzmqnotifications RPC
2020-12-16T12:23:52.481000Z TestFramework (INFO): Testing 'sequence' publisher
2020-12-16T12:24:53.816000Z TestFramework (ERROR): Unexpected exception caught during testing
Traceback (most recent call last):
  File "/private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin18/test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "/private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin18/test/functional/interface_zmq.py", line 74, in run_test
    self.test_sequence()
  File "/private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin18/test/functional/interface_zmq.py", line 260, in test_sequence
    assert_equal((self.nodes[0].getbestblockhash(), "C", None), seq.receive_sequence())
  File "/private/var/folders/3y/l0z1x3693dl_8n0qybp4dqwh0000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin18/test/functional/interface_zmq.py", line 46, in receive_sequence
    topic, body, seq = self.socket.recv_multipart()
  File "/Users/anka/Library/Python/3.8/lib/python/site-packages/zmq/sugar/socket.py", line 566, in recv_multipart
    parts = [self.recv(flags, copy=copy, track=track)]
  File "zmq/backend/cython/socket.pyx", line 783, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 819, in zmq.backend.cython.socket.Socket.recv
  File "zmq/backend/cython/socket.pyx", line 191, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/socket.pyx", line 186, in zmq.backend.cython.socket._recv_copy
  File "zmq/backend/cython/checkrc.pxd", line 22, in zmq.backend.cython.checkrc._check_rc
zmq.error.Again: Resource temporarily unavailable
```

Full context: https://cirrus-ci.com/task/6182559350521856

**Comment by MarcoFalke** [comment]
#20618  
#20590 
#20538
