### ISSUE TITLE
EstimateMedianVal returns higher fee for higher confTarget

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#20725]
Running on recent master, commit f1dbf92ff0475a01d20170ea422c1d086acbbc57

If I run:
```
test/functional/feature_fee_estimation.py --randomseed 108574360997204915
```

I get:
```
2020-12-19T20:14:06.175000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_bcwexp78
2020-12-19T20:14:07.738000Z TestFramework (INFO): This test is time consuming, please be patient
2020-12-19T20:14:07.738000Z TestFramework (INFO): Splitting inputs so we can generate tx's
2020-12-19T20:14:10.870000Z TestFramework (INFO): Finished splitting
2020-12-19T20:14:12.104000Z TestFramework (INFO): Will output estimates for 1/2/3/6/15/25 blocks
2020-12-19T20:14:12.104000Z TestFramework (INFO): Creating transactions and mining them with a block size that can't keep up
2020-12-19T20:14:15.879000Z TestFramework (INFO): Creating transactions and mining them at a block size that is just big enough
2020-12-19T20:14:21.104000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/sdaftuar/ccl-bitcoin/2020-12-latest-master/test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "test/functional/feature_fee_estimation.py", line 256, in run_test
    check_estimates(self.nodes[1], self.fees_per_kb)
  File "test/functional/feature_fee_estimation.py", line 140, in check_estimates
    check_smart_estimates(node, fees_seen)
  File "test/functional/feature_fee_estimation.py", line 130, in check_smart_estimates
    % (feerate, last_feerate))
AssertionError: Estimated fee (0.000565) larger than last fee (0.000479) for lower number of confirms

```

**Comment by MarcoFalke** [comment]
Thanks for finding the random seed that triggers this reliably

**Comment by sapdoi** [comment]
sapdoi

**Comment by sapdoi** [comment]
sapdoi

**Comment by MarcoFalke** [comment]
With `--tracerpc` shows that this is really an issue with `estimatesmartfee`, not the test:

```
...
-4469-> estimatesmartfee [1]
<-4469- [0.001963] {"feerate": "0.00067579", "blocks": 2}
-4470-> estimatesmartfee [2]
<-4470- [0.002432] {"feerate": "0.00067579", "blocks": 2}
-4471-> estimatesmartfee [3]
<-4471- [0.002226] {"feerate": "0.00047895", "blocks": 3}
-4472-> estimatesmartfee [4]
<-4472- [0.002212] {"feerate": "0.00056521", "blocks": 4}
...

**Comment by MarcoFalke** [comment]
The incorrect return values (for target `3` and `4`) are calculated in this line (short horizon): https://github.com/bitcoin/bitcoin/blob/e9efb64a0772777f2ce88c491101550b931a21d6/src/policy/fees.cpp#L736

the values are:
* `confTarget=3  successThreshold=0.85  estimate=47894.7  nBestSeenHeight=230`
* `confTarget=4  successThreshold=0.85  estimate=56521    nBestSeenHeight=230`

**Comment by MarcoFalke** [comment]
Changed title

**Comment by MarcoFalke** [comment]
Related #11800?

**Comment by practicalswift** [comment]
Unfortunately this larger than life^H^H^Hast fee issue in `feature_fee_estimation.py` keeps popping up.

From https://cirrus-ci.com/task/4756253495787520:

```
AssertionError: Estimated fee (0.000400) larger than last fee (0.000338) for lower number of confirms
```

**Comment by ajtowns** [comment]
Fix in #21161 I think. I think what's going on is that the bucket ranges weren't consistent between confirmation targets, because `newBucketRange = true` is only set when the threshold is met, and buckets are extended otherwise. Not quite sure what the arrangement needs to be for that to result in a higher target giving a higher fee though.

**Comment by morcos** [comment]
> Related #11800?

I think its an unrelated different bug

**Comment by ismaelsadeeq** [comment]
I  try recreating this issue on master HEAD bc4f6b13feb29146b7e10e86f93dc7f6fb6937f2  
with the same command `test/functional/feature_fee_estimation.py --randomseed 108574360997204915`

The tests passed.

**Comment by mzumsande** [comment]
> @ismaelsadeeq Can you try with the commit specified in OP as well? If it fails, can you try bisecting?

Maybe not necessary:
There are newer crashes reported in #23165 (which seems to be the same problem). The seed `7288975409214300634` from https://api.cirrus-ci.com/v1/task/6110951150190592/logs/ci.log leads to a crash on current master (the test passes with #21161 rebased on master).
