### ISSUE TITLE
Intermittent issue in create_raw_transaction                                        assert_equal(final_psbt["complete"], True) fails

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#20975]
https://cirrus-ci.com/task/4904241892425728?command=ci#L5098

```
 test  2021-01-20T23:39:58.801000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 126, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_nulldummy.py", line 94, in run_test
                                       test4tx = create_transaction(self.nodes[0], test2tx.hash, self.address, amount=46)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/blocktools.py", line 164, in create_transaction
                                       raw_tx = create_raw_transaction(node, txid, to_address, amount=amount)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/blocktools.py", line 180, in create_raw_transaction
                                       assert_equal(final_psbt["complete"], True)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 50, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(False == True)

**Comment by MarcoFalke** [comment]
I've seen this for at least two months

**Comment by hebasto** [comment]
The same error in the recent "Linux32" build on https://bitcoinbuilds.org/?job=a67a5e50-f422-436f-b173-54a4765094db:
```
...
2021-05-29T13:54:49.294000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20210529_093535/feature_nulldummy_72
2021-05-29T13:54:51.887000Z TestFramework (INFO): Test 1: NULLDUMMY compliant base transactions should be accepted to mempool and mined before activation [103]
2021-05-29T13:54:51.908000Z TestFramework (INFO): Test 2: Non-NULLDUMMY base multisig transaction should not be accepted to mempool before activation
2021-05-29T13:54:51.914000Z TestFramework (INFO): Test 3: Non-NULLDUMMY base transactions should be accepted in a block before activation [104]
2021-05-29T13:54:51.917000Z TestFramework (INFO): Test 4: Non-NULLDUMMY base multisig transaction is invalid after activation
2021-05-29T13:54:51.920000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/ubuntu/src/test/functional/test_framework/test_framework.py", line 128, in main
    self.run_test()
  File "/home/ubuntu/src/test/functional/feature_nulldummy.py", line 95, in run_test
    test4tx = create_transaction(self.nodes[0], test2tx.hash, self.address, amount=46)
  File "/home/ubuntu/src/test/functional/test_framework/blocktools.py", line 165, in create_transaction
    raw_tx = create_raw_transaction(node, txid, to_address, amount=amount)
  File "/home/ubuntu/src/test/functional/test_framework/blocktools.py", line 181, in create_raw_transaction
    assert_equal(final_psbt["complete"], True)
  File "/home/ubuntu/src/test/functional/test_framework/util.py", line 50, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(False == True)
2021-05-29T13:54:51.971000Z TestFramework (INFO): Stopping nodes
...
```

**Comment by MarcoFalke** [comment]
@achow101 What info would be useful to debug this? Maybe log the full psbt?

**Comment by achow101** [comment]
I think the full psbts and `listunspent` would help.

**Comment by ryanofsky** [comment]
I saw this same issue yesterday: `assert_equal(final_psbt["complete"], True)` failing in `feature_nulldummy.py`) causing a spurious failure. Restarting cirrus got around the problem.

- Failure: https://cirrus-ci.com/task/5801234834653184
- Successful restart: https://cirrus-ci.com/task/4603201723826176

```
feature_nulldummy.py --descriptors

Checked out 33af67edbd902e9b9c3862c3a3066798cac1a33d on pull/22100 branch.

Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 128, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_nulldummy.py", line 100, in run_test
    test4tx = create_transaction(self.nodes[0], test2tx.hash, self.address, amount=46)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/blocktools.py", line 168, in create_transaction
    raw_tx = create_raw_transaction(node, txid, to_address, amount=amount)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/blocktools.py", line 189, in create_raw_transaction
    assert_equal(final_psbt["complete"], True)
```

**Comment by MarcoFalke** [comment]
Looks like a missing BlockUntilSyncedToCurrentChain in walletprocesspsbt and other methods
