### ISSUE TITLE
Failure in test/functional/interface_zmq.py

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#21216]
I don't think this can be my bug, as I pushed a comment only change to my PR and then got a test failure:

https://cirrus-ci.com/task/5869686954917888?command=ci#L5219

```
 test  2021-02-16T19:08:03.550000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 127, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_zmq.py", line 82, in run_test
                                       self.test_sequence()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/interface_zmq.py", line 277, in test_sequence
                                       assert_equal((self.nodes[0].getbestblockhash(), "C", None), seq.receive_sequence())
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 50, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(('5d2daef0df4c3f8af7d33f350253d3c5b3eab0154803f0f9dff228512ce6ced3', 'C', None) == ('3bd98765bf07cc72a921a5c6fad95b13dac7c80100f0b295f29681e0e3c6e856', 'C', None))
```

The PR in question needs a rebase anyway now, so I'll try that and see if this goes away.

**Comment by jonatack** [comment]
Hopefully the just-merged #21008 will help here.

**Comment by MarcoFalke** [comment]
#21008 was merged 20 hours ago and the failure was 19 hours ago, so  #21008 might be causing it

**Comment by theStack** [comment]
Yes, unfortunately it seems like #21008 didn't improve anything at all (or more likely, fixed one problem but caused another) :/ https://github.com/bitcoin/bitcoin/pull/21250/checks?check_run_id=1946002862
Will try to find out within the next days what is the problem.
