### ISSUE TITLE
qa: Intermittent failure in `wallet_balance.py --descriptors`

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#21536]
https://bitcoinbuilds.org/?job=c60949ea-d764-497f-97a7-3d7711bb7496

<details><summary>log excerpt</summary>
<p>

```
2021-03-28T04:46:34.623000Z TestFramework (INFO): Test replacement and reorg of non-mempool tx
2021-03-28T04:46:36.833000Z TestFramework (INFO): Put txs back into mempool of node 1 (not node 0)
2021-03-28T04:46:40.133000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/ubuntu/src/test/functional/test_framework/test_framework.py", line 128, in main
    self.run_test()
  File "/home/ubuntu/src/test/functional/wallet_balance.py", line 268, in run_test
    assert_equal(self.nodes[0].getbalance(minconf=0), 0)  # wallet txs not in the mempool are untrusted
  File "/home/ubuntu/src/test/functional/test_framework/util.py", line 50, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(98.85983340 == 0)
2021-03-28T04:46:40.139000Z TestFramework (INFO): Stopping nodes
```

</p>
</details>

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

(The link in OP redirects to an ad+tracker)
