### ISSUE TITLE
qa: feature_notifications fails with "IndexError: string index out of range"

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#21776]
https://cirrus-ci.com/task/5737232834232320?logs=ci#L3345
```
 node0 2021-04-25T19:08:05.681303Z [http] [httpserver.cpp:238] [http_request_cb] Received a POST request for / from 127.0.0.1:33768 
 node0 2021-04-25T19:08:05.681424Z [httpworker.1] [rpc/request.cpp:174] [parse] ThreadRPCServer method=getrawmempool user=__cookie__ 
 node1 2021-04-25T19:08:05.682485Z [http] [httpserver.cpp:238] [http_request_cb] Received a POST request for / from 127.0.0.1:57040 
 node1 2021-04-25T19:08:05.682592Z [httpworker.1] [rpc/request.cpp:174] [parse] ThreadRPCServer method=getrawmempool user=__cookie__ 
 node0 2021-04-25T19:08:05.683502Z [http] [httpserver.cpp:238] [http_request_cb] Received a POST request for / from 127.0.0.1:33768 
 node0 2021-04-25T19:08:05.683593Z [httpworker.2] [rpc/request.cpp:174] [parse] ThreadRPCServer method=syncwithvalidationinterfacequeue user=__cookie__ 
 node1 2021-04-25T19:08:05.684285Z [http] [httpserver.cpp:238] [http_request_cb] Received a POST request for / from 127.0.0.1:57040 
 node1 2021-04-25T19:08:05.684366Z [httpworker.2] [rpc/request.cpp:174] [parse] ThreadRPCServer method=syncwithvalidationinterfacequeue user=__cookie__ 
 test  2021-04-25T19:08:05.685000Z TestFramework (ERROR): Unexpected exception caught during testing 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 128, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_notifications.py", line 144, in run_test
                                       self.expect_wallet_notify([(tx2, -1, UNCONFIRMED_HASH_STRING)])
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_notifications.py", line 172, in expect_wallet_notify
                                       assert_equal(text[-1], '\n')
                                   IndexError: string index out of range
 test  2021-04-25T19:08:05.685000Z TestFramework (DEBUG): Closing down network thread 
 test  2021-04-25T19:08:05.736000Z TestFramework (INFO): Stopping nodes 
```

**Comment by jonatack** [comment]
Maybe duplicate of https://github.com/bitcoin/bitcoin/issues/21683

**Comment by hebasto** [comment]
> Maybe duplicate of #21683

RIght.
