### ISSUE TITLE
CI timeout in test/functional/p2p_addr_relay.py::L184

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#22449]
Cirrus link: https://cirrus-ci.com/task/6054661070258176

```bash
test/functional/p2p_addr_relay.py", line 184, in getaddr_tests
                                       inbound_peer.wait_until(lambda: inbound_peer.addr_received() is True)
```

```bash
37.1.1:8333 timed out 
 node0 2021-07-14T16:52:07.055283Z (mocktime: 2021-07-14T17:17:09Z) [opencon] [net.cpp:402] [ConnectNode] trying connection 2.163.1.1:8333 lastseen=0.1hrs 
 node0 2021-07-14T16:52:10.043553Z (mocktime: 2021-07-14T17:17:09Z) [scheduler] [random.cpp:523] [SeedPeriodic] Feeding 33046 bytes of dynamic environment data into RNG 
 node0 2021-07-14T16:52:12.060196Z (mocktime: 2021-07-14T17:17:09Z) [opencon] [netbase.cpp:571] [ConnectSocketDirectly] connection attempt to 2.163.1.1:8333 timed out 
 node0 2021-07-14T16:52:12.561757Z (mocktime: 2021-07-14T17:17:09Z) [opencon] [net.cpp:402] [ConnectNode] trying connection 2.143.1.1:8333 lastseen=0.1hrs 
 node0 2021-07-14T16:52:16.048761Z (mocktime: 2021-07-14T17:17:09Z) [net] [net.cpp:1313] [InactivityCheck] socket sending timeout: 1201s peer=12 
 node0 2021-07-14T16:52:16.048809Z (mocktime: 2021-07-14T17:17:09Z) [net] [net.cpp:1313] [InactivityCheck] socket sending timeout: 1201s peer=13 
 node0 2021-07-14T16:52:16.048824Z (mocktime: 2021-07-14T17:17:09Z) [net] [net.cpp:1313] [InactivityCheck] socket sending timeout: 1201s peer=14 
 node0 2021-07-14T16:52:16.048858Z (mocktime: 2021-07-14T17:17:09Z) [net] [net.cpp:505] [CloseSocketDisconnect] disconnecting peer=12 
 node0 2021-07-14T16:52:16.048920Z (mocktime: 2021-07-14T17:17:09Z) [net] [net.cpp:505] [CloseSocketDisconnect] disconnecting peer=13 
 node0 2021-07-14T16:52:16.048948Z (mocktime: 2021-07-14T17:17:09Z) [net] [net.cpp:505] [CloseSocketDisconnect] disconnecting peer=14 
 test  2021-07-14T16:52:16.049000Z TestFramework.p2p (DEBUG): Closed connection to: 0:0 
 test  2021-07-14T16:52:16.049000Z TestFramework.p2p (DEBUG): Closed connection to: 0:0 
 test  2021-07-14T16:52:16.049000Z TestFramework.p2p (DEBUG): Closed connection to: 127.0.0.1:15440 
 node0 2021-07-14T16:52:16.049171Z (mocktime: 2021-07-14T17:17:09Z) [net] [net_processing.cpp:1190] [FinalizeNode] Cleared nodestate for peer=12 
 node0 2021-07-14T16:52:16.049336Z (mocktime: 2021-07-14T17:17:09Z) [net] [net_processing.cpp:1190] [FinalizeNode] Cleared nodestate for peer=13 
 node0 2021-07-14T16:52:16.049444Z (mocktime: 2021-07-14T17:17:09Z) [net] [net_processing.cpp:1190] [FinalizeNode] Cleared nodestate for peer=14 
 test  2021-07-14T16:52:16.050000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 128, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_addr_relay.py", line 60, in run_test
                                       self.getaddr_tests()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_addr_relay.py", line 184, in getaddr_tests
                                       inbound_peer.wait_until(lambda: inbound_peer.addr_received() is True)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/p2p.py", line 450, in wait_until
                                       wait_until_helper(test_function, timeout=timeout, lock=p2p_lock, timeout_factor=self.timeout_factor)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 247, in wait_until_helper
                                       if predicate():
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/p2p.py", line 447, in test_function
                                       assert self.is_connected
                                   AssertionError
 test  2021-07-14T16:52:16.051000Z TestFramework (DEBUG): Closing down network thread 
 test  2021-07-14T16:52:16.101000Z TestFramework (INFO): Stopping nodes 
 test  2021-07-14T16:52:16.101000Z TestFramework.node0 (DEBUG): Stopping node 
```

**Comment by jonatack** [comment]
Had a look in the issues and did not see this already reported.

**Comment by fanquake** [comment]
Can you link to the actual cirrus job, otherwise it's not clear what code failed. Was it master, a PR etc.

**Comment by jonatack** [comment]
Right, sorry about that.  It was a multiprocess CI run of #22437, which is based on current master and only changes a different functional test.  Updated the issue description.  I'll add a link if I see it again.

**Comment by jonatack** [comment]
Added the cirrus job link.
