### ISSUE TITLE
[0.21] test: assertion failed in feature_taproot.py

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#22581]
Seeing the same failure on a number of the 0.21 backport PRs. i.e https://cirrus-ci.com/task/5497683654737920:

```bash
168/194 - feature_taproot.py failed, Duration: 1248 s
stdout:
2021-07-29T09:23:04.366000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210729_091956/feature_taproot_172
2021-07-29T09:23:07.475000Z TestFramework (INFO): Post-activation tests...
2021-07-29T09:23:16.879000Z TestFramework (INFO): - Constructing addresses for returning coins
2021-07-29T09:23:17.297000Z TestFramework (INFO): - Creating test UTXOs...
2021-07-29T09:23:18.643000Z TestFramework (INFO): - Running 2740 spending tests
2021-07-29T09:23:44.188000Z TestFramework (INFO):   - 201 tests done
2021-07-29T09:24:12.165000Z TestFramework (INFO):   - 401 tests done
2021-07-29T09:25:01.751000Z TestFramework (INFO):   - 601 tests done
2021-07-29T09:25:39.542000Z TestFramework (INFO):   - 800 tests done
2021-07-29T09:26:23.207000Z TestFramework (INFO):   - 1001 tests done
2021-07-29T09:27:14.258000Z TestFramework (INFO):   - 1201 tests done
2021-07-29T09:28:12.163000Z TestFramework (INFO):   - 1402 tests done
2021-07-29T09:29:06.211000Z TestFramework (INFO):   - 1601 tests done
2021-07-29T09:29:49.906000Z TestFramework (INFO):   - 1800 tests done
2021-07-29T09:30:48.693000Z TestFramework (INFO):   - 2000 tests done
2021-07-29T09:32:02.797000Z TestFramework (INFO):   - 2201 tests done
2021-07-29T09:33:25.161000Z TestFramework (INFO):   - 2401 tests done
2021-07-29T09:34:37.826000Z TestFramework (INFO):   - 2601 tests done
2021-07-29T09:35:35.910000Z TestFramework (INFO):   - Done
2021-07-29T09:43:46.969000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 126, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_taproot.py", line 1466, in run_test
    self.sync_blocks()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 615, in sync_blocks
    assert (all([len(x.getpeerinfo()) for x in rpc_connections]))
AssertionError
2021-07-29T09:43:46.975000Z TestFramework (INFO): Stopping nodes
2021-07-29T09:43:51.344000Z TestFramework (WARNING): Not cleaning up dir /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210729_091956/feature_taproot_172
2021-07-29T09:43:51.344000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210729_091956/feature_taproot_172/test_framework.log
2021-07-29T09:43:51.344000Z TestFramework (ERROR): 
2021-07-29T09:43:51.344000Z TestFramework (ERROR): Hint: Call /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/combine_logs.py '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210729_091956/feature_taproot_172' to consolidate all logs
2021-07-29T09:43:51.344000Z TestFramework (ERROR): 
2021-07-29T09:43:51.345000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2021-07-29T09:43:51.345000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2021-07-29T09:43:51.345000Z TestFramework (ERROR): 
```

**Comment by MarcoFalke** [comment]
#20535

**Comment by fanquake** [comment]
Thought it might have been that, although both the cirrus links in the PR give me a white screen, so couldn't compare logs.

**Comment by MarcoFalke** [comment]
I've also included the disconnect message in the description ("Timeout downloading block"). The same error also appears in your failed run.

**Comment by fanquake** [comment]
> The same error also appears in your failed run.

I can't see for looking.

**Comment by MarcoFalke** [comment]
![Screenshot 2021-07-29 at 14-42-32 Cirrus CI](https://user-images.githubusercontent.com/6399679/127493745-62ac1fe0-bec8-41be-adea-989922e09566.png)
