### ISSUE TITLE
ci: failure in feature_asmap

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#23078]
Seen in #23074. https://github.com/bitcoin/bitcoin/pull/23074#issuecomment-925995340.
```bash
2021-09-23T14:53:38.217000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20210923_145026/feature_asmap_26
2021-09-23T14:53:39.000000Z TestFramework (INFO): Test bitcoind with no -asmap arg passed
2021-09-23T14:53:39.442000Z TestFramework (INFO): Test bitcoind -asmap=<absolute path>
2021-09-23T14:53:40.286000Z TestFramework (INFO): Test bitcoind -asmap=<relative path>
2021-09-23T14:53:40.859000Z TestFramework (INFO): Test bitcoind -asmap (using default map file)
2021-09-23T14:53:41.404000Z TestFramework (INFO): Test bitcoind -asmap= (using default map file)
2021-09-23T14:53:42.007000Z TestFramework (INFO): Test bitcoind -asmap restart with addrman containing new and tried entries
2021-09-23T14:55:03.894000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_asmap.py", line 124, in run_test
    self.test_asmap_interaction_with_addrman_containing_entries()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_asmap.py", line 96, in test_asmap_interaction_with_addrman_containing_entries
    self.node.getnodeaddresses()  # getnodeaddresses re-runs the addrman checks
  File "/usr/lib/python3.6/contextlib.py", line 88, in __exit__
    next(self.gen)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py", line 400, in assert_debug_log
    self._raise_assertion_error('Expected messages "{}" does not partially match log:\n\n{}\n\n'.format(str(expected_msgs), print_log))
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py", line 166, in _raise_assertion_error
    raise AssertionError(self._node_msg(msg))
AssertionError: [node 0] Expected messages "['Addrman checks started: new 2, tried 2, total 4', 'Addrman checks completed successfully']" does not partially match log:
 - 2021-09-23T14:53:43.886617Z [http] [httpserver.cpp:237] [http_request_cb] Received a POST request for / from 127.0.0.1:52652
 - 2021-09-23T14:53:43.886733Z [httpworker.3] [rpc/request.cpp:174] [parse] ThreadRPCServer method=getnodeaddresses user=__cookie__
 - 2021-09-23T14:53:43.886809Z [httpworker.3] [addrman.cpp:770] [ForceCheckAddrman] Addrman checks started: new 3, tried 1, total 4
 - 2021-09-23T14:53:43.886870Z [httpworker.3] [addrman.cpp:48] [GetTriedBucket] IP 101.0.0.0 mapped to AS1 belongs to tried bucket 113
 - 2021-09-23T14:53:43.886980Z [httpworker.3] [addrman.cpp:850] [ForceCheckAddrman] Addrman checks completed successfully
 - 2021-09-23T14:53:43.886991Z [httpworker.3] [addrman.cpp:770] [ForceCheckAddrman] Addrman checks started: new 3, tried 1, total 4
 - 2021-09-23T14:53:43.887016Z [httpworker.3] [addrman.cpp:48] [GetTriedBucket] IP 101.0.0.0 mapped to AS1 belongs to tried bucket 113
 - 2021-09-23T14:53:43.887102Z [httpworker.3] [addrman.cpp:850] [ForceCheckAddrman] Addrman checks completed successfully
 - 2021-09-23T14:54:28.662861Z [scheduler] [net.h:865] [StartExtraBlockRelayPeers] net: enabling extra block-relay-only peers
 - 2021-09-23T14:54:43.321822Z [scheduler] [random.cpp:523] [SeedPeriodic] Feeding 33048 bytes of dynamic environment data into RNG
 - 
```

**Comment by jonatack** [comment]
Thanks @darosior and @fanquake for reporting.  I was unable to reproduce locally on current master with `(for i in {1..1200}; do test/functional/feature_asmap.py --pdbonfailure ; done)` or `test/functional/feature_asmap.py --valgrind`.  However, asserting on the debug log isn't essential to this regression test. Proposed asserting on the result instead in #23084.
