### ISSUE TITLE
ci: `test_runner` uses a UNIX-only Python function (`os.killpg`)

### ISSUE THREAD

**Issue by darosior** [bitcoin/bitcoin#23085]
Encountered by the Win64 CI in #23074

```
Traceback (most recent call last):
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_runner.py", line 797, in <module>
    main()
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_runner.py", line 446, in main
    run_tests(
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_runner.py", line 567, in run_tests
    os.killpg(os.getpgid(0), signal.SIGKILL)
AttributeError: module 'os' has no attribute 'killpg'
```

**Comment by hebasto** [comment]
See:
- #22936
- #22980

**Comment by MarcoFalke** [comment]
Thanks for the report, however I am going to close this bug, as it has been removed from ci in #23513.

The bug still does exist on Windows, but I don't think we have any users on Windows that run the tests with --failfast. If I am wrong, please let me know and this bug can be reopened or a new one be opened.
