### ISSUE TITLE
Intermittent failure in wallet_backup.py

### ISSUE THREAD

**Issue by meshcollider** [bitcoin/bitcoin#23131]
https://cirrus-ci.com/task/5490054542917632?logs=ci#L3249

```
 test  2021-09-26T02:50:26.725000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_backup.py", line 220, in run_test
                                       assert_equal(self.nodes[2].getbalance(), 0)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 49, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(50.00000000 == 0)
```

Not sure if this has been seen before, I've only seen it happen once.

**Comment by meshcollider** [comment]
Haven't seen this again and no reports of it from others so I'll close this.
