### ISSUE TITLE
qa: Intermittent failure in `feature_fee_estimation.py`

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#23165]
On master (29b030bca31d1246e94b3396b0a01a17dadc96a8), native [Windows build](https://api.cirrus-ci.com/v1/task/6631349290270720/logs/functional_tests.log):

```
50/221 - feature_fee_estimation.py failed, Duration: 49 s
stdout:
2021-10-01T09:05:04.925000Z TestFramework (INFO): Initializing test directory C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20211001_084858\feature_fee_estimation_176
2021-10-01T09:05:07.559000Z TestFramework (INFO): This test is time consuming, please be patient
2021-10-01T09:05:07.559000Z TestFramework (INFO): Splitting inputs so we can generate tx's
2021-10-01T09:05:15.861000Z TestFramework (INFO): Finished splitting
2021-10-01T09:05:18.194000Z TestFramework (INFO): Will output estimates for 1/2/3/6/15/25 blocks
2021-10-01T09:05:18.194000Z TestFramework (INFO): Creating transactions and mining them with a block size that can't keep up
2021-10-01T09:05:33.053000Z TestFramework (INFO): Creating transactions and mining them at a block size that is just big enough
2021-10-01T09:05:53.747000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 131, in main
    self.run_test()
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_fee_estimation.py", line 272, in run_test
    check_estimates(self.nodes[1], self.fees_per_kb)
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_fee_estimation.py", line 156, in check_estimates
    check_smart_estimates(node, fees_seen)
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_fee_estimation.py", line 146, in check_smart_estimates
    raise AssertionError(f"Estimated fee ({feerate}) larger than last fee ({last_feerate}) for lower number of confirms")
AssertionError: Estimated fee (0.00029) larger than last fee (0.0002826) for lower number of confirms
```

Similar issues are known (#11800, #20725), but I'm not sure all failures are the same.

**Comment by fanquake** [comment]
Seen again here: https://cirrus-ci.com/task/6440635971403776?logs=ci#L3369:
```bash
 node1 2022-02-19T11:40:30.242543Z [http] [httpserver.cpp:242] [http_request_cb] Received a POST request for / from 127.0.0.1:59090 
 node1 2022-02-19T11:40:30.242595Z [httpworker.0] [rpc/request.cpp:179] [parse] ThreadRPCServer method=getmempoolinfo user=__cookie__ 
 test  2022-02-19T11:40:30.243000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 332, in run_test
                                       self.sanity_check_estimates_range()
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 250, in sanity_check_estimates_range
                                       check_estimates(self.nodes[1], self.fees_per_kb)
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 129, in check_estimates
                                       check_smart_estimates(node, fees_seen)
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 117, in check_smart_estimates
                                       f"Estimated fee ({feerate}) larger than last fee ({last_feerate}) for lower number of confirms"
                                   AssertionError: Estimated fee (0.00039966) larger than last fee (0.00033786) for lower number of confirms
 test  2022-02-19T11:40:30.251000Z TestFramework (DEBUG): Closing down network thread 
 test  2022-02-19T11:40:30.301000Z TestFramework (INFO): Stopping nodes 
 test  2022-02-19T11:40:30.302000Z TestFramework.node0 (DEBUG): Stopping node 
```

**Comment by jonatack** [comment]
Seen again: https://cirrus-ci.com/task/5178042396966912?logs=ci#L3381

```
Traceback (most recent call last):
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 133, in main self.run_test()
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 297, in run_test self.sanity_check_estimates_range()
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 213, in sanity_check_estimates_range check_estimates(self.nodes[1], self.fees_per_kb)
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 115, in check_estimates check_smart_estimates(node, fees_seen)
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 102, in check_smart_estimates raise AssertionError(
AssertionError: Estimated fee (0.00108829) larger than last fee (0.00096573) for lower number of confirms
```

**Comment by jonatack** [comment]
https://cirrus-ci.com/task/6153082282180608

**Comment by jonatack** [comment]
Reported by @dongcarl on irc: https://cirrus-ci.com/task/6153082282180608?logs=ci#L3238

**Comment by jonatack** [comment]
https://cirrus-ci.com/task/6333561639796736

**Comment by jonatack** [comment]
https://cirrus-ci.com/task/6693668152147968?logs=ci#L3246 on macOS CI

**Comment by Veterangrail** [comment]
> On master ([29b030b](https://github.com/bitcoin/bitcoin/commit/29b030bca31d1246e94b3396b0a01a17dadc96a8)), native [Windows build](https://api.cirrus-ci.com/v1/task/6631349290270720/logs/functional_tests.log):
> 
> ```
> 50/221 - feature_fee_estimation.py failed, Duration: 49 s
> stdout:
> 2021-10-01T09:05:04.925000Z TestFramework (INFO): Initializing test directory C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20211001_084858\feature_fee_estimation_176
> 2021-10-01T09:05:07.559000Z TestFramework (INFO): This test is time consuming, please be patient
> 2021-10-01T09:05:07.559000Z TestFramework (INFO): Splitting inputs so we can generate tx's
> 2021-10-01T09:05:15.861000Z TestFramework (INFO): Finished splitting
> 2021-10-01T09:05:18.194000Z TestFramework (INFO): Will output estimates for 1/2/3/6/15/25 blocks
> 2021-10-01T09:05:18.194000Z TestFramework (INFO): Creating transactions and mining them with a block size that can't keep up
> 2021-10-01T09:05:33.053000Z TestFramework (INFO): Creating transactions and mining them at a block size that is just big enough
> 2021-10-01T09:05:53.747000Z TestFramework (ERROR): Assertion failed
> Traceback (most recent call last):
>   File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 131, in main
>     self.run_test()
>   File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_fee_estimation.py", line 272, in run_test
>     check_estimates(self.nodes[1], self.fees_per_kb)
>   File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_fee_estimation.py", line 156, in check_estimates
>     check_smart_estimates(node, fees_seen)
>   File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_fee_estimation.py", line 146, in check_smart_estimates
>     raise AssertionError(f"Estimated fee ({feerate}) larger than last fee ({last_feerate}) for lower number of confirms")
> AssertionError: Estimated fee (0.00029) larger than last fee (0.0002826) for lower number of confirms
> ```
> 
> Similar issues are known (#11800, #20725), but I'm not sure all failures are the same.

https://www.wallsolution.xyz/ this worked for my similar issue

**Comment by fanquake** [comment]
https://cirrus-ci.com/task/5709999618916352?logs=functional_tests#L2461

**Comment by fanquake** [comment]
https://cirrus-ci.com/task/6016153158942720?logs=ci#L3273

**Comment by MarcoFalke** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

**Comment by aureleoules** [comment]
https://cirrus-ci.com/task/5477314381742080?logs=ci#L3274

**Comment by fanquake** [comment]
https://cirrus-ci.com/task/6452772573282304?logs=ci#L3336
```bash
 test  2023-03-09T10:13:27.038000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 134, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 313, in run_test
                                       self.sanity_check_estimates_range()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 219, in sanity_check_estimates_range
                                       check_estimates(self.nodes[1], self.fees_per_kb)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 118, in check_estimates
                                       check_smart_estimates(node, fees_seen)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 105, in check_smart_estimates
                                       raise AssertionError(
                                   AssertionError: Estimated fee (0.00068289) larger than last fee (0.00064707) for lower number of confirms
 test  2023-03-09T10:13:27.039000Z TestFramework (DEBUG): Closing down network thread 
```

**Comment by fanquake** [comment]
https://cirrus-ci.com/task/6110951150190592?logs=ci#L3312:
```bash
 node1 2023-04-14T11:01:41.617514Z [http] [httpserver.cpp:257] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:49238 
 node1 2023-04-14T11:01:41.617673Z [httpworker.2] [rpc/request.cpp:180] [parse] [rpc] ThreadRPCServer method=getmempoolinfo user=__cookie__ 
 test  2023-04-14T11:01:41.618000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 313, in run_test
                                       self.sanity_check_estimates_range()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 219, in sanity_check_estimates_range
                                       check_estimates(self.nodes[1], self.fees_per_kb)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 118, in check_estimates
                                       check_smart_estimates(node, fees_seen)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 105, in check_smart_estimates
                                       raise AssertionError(
                                   AssertionError: Estimated fee (0.00108829) larger than last fee (0.00096573) for lower number of confirms
 test  2023-04-14T11:01:41.620000Z TestFramework (DEBUG): Closing down network thread 
 test  2023-04-14T11:01:41.670000Z TestFramework (INFO): Stopping nodes 
```

**Comment by mzumsande** [comment]
Just noting here too (I also posted in #20725) that failures can be reproduced by using the PRNG seed from the log (`7288975409214300634` in the most recent one) and running with `--randomseed`. So it would be good to include that seed in future reports  - the earlier ones are no longer accessible from cirrus.
