### ISSUE TITLE
CI failure: TestFramework.utils (ERROR): wait_until() failed. Predicate: '''' 

### ISSUE THREAD

**Issue by lsilva01** [bitcoin/bitcoin#23399]
The error below occurred in the `Cirrus CI / [previous releases, uses qt5 dev package and some depends packages, DEBUG] [unsigned char] [bionic]` check in PR #23398.

Unable to reproduce the same error on the Ubuntu local machine.
The `p2p_feefilter.py` worked as expected.
Maybe it's something intermittent.

Link to error: https://cirrus-ci.com/task/5898721704542208?logs=ci#L3589

```
 test  2021-10-30T19:29:36.048000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: '''' 
                                           def test_function():
                                               if check_connected:
                                                   assert self.is_connected
                                               return test_function_in()
                                   '''
 test  2021-10-30T19:29:36.048000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_feefilter.py", line 64, in run_test
                                       self.test_feefilter()
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_feefilter.py", line 91, in test_feefilter
                                       conn.wait_for_invs_to_match(txids)
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_feefilter.py", line 40, in wait_for_invs_to_match
                                       self.wait_until(lambda: invs_expected == sorted(self.txinvs))
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/p2p.py", line 451, in wait_until
                                       wait_until_helper(test_function, timeout=timeout, lock=p2p_lock, timeout_factor=self.timeout_factor)
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 257, in wait_until_helper
                                       raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
                                   AssertionError: Predicate ''''
                                           def test_function():
                                               if check_connected:
                                                   assert self.is_connected
                                               return test_function_in()
                                   ''' not true after 2400.0 seconds
 test  2021-10-30T19:29:36.051000Z TestFramework (DEBUG): Closing down network thread 
 test  2021-10-30T19:29:36.101000Z TestFramework (INFO): Stopping nodes 
 test  2021-10-30T19:29:36.102000Z TestFramework.node0 (DEBUG): Stopping node 
```

**Comment by brunoerg** [comment]
When I run some tests alone, they run successfully. However, when I execute: `./test/functional/test_runner.py` some tests give the same error you are reporting.

**Comment by lsilva01** [comment]
Perhaps is this issue related to #23300 ?

**Comment by brunoerg** [comment]
> Perhaps is this issue related to #23300 ?

I think so.
