### ISSUE TITLE
test: failure in test/functional/feature_rbf.py with `--without-bdb`

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#23563]
master @ cf06c9b35c30512ede8f7dc323340bd9cfb2d0b9

```bash
./autogen.sh
./configure --without-bdb
make -j9

./test/functional/feature_rbf.py                  
2021-11-21T09:25:15.472000Z TestFramework (INFO): Initializing test directory /var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/bitcoin_func_test_dzacmtp6
2021-11-21T09:25:16.098000Z TestFramework (INFO): Running test simple doublespend...
2021-11-21T09:25:16.104000Z TestFramework (INFO): Running test doublespend chain...
2021-11-21T09:25:16.152000Z TestFramework (INFO): Running test doublespend tree...
2021-11-21T09:25:16.770000Z TestFramework (INFO): Running test replacement feeperkb...
2021-11-21T09:25:16.841000Z TestFramework (INFO): Running test spends of conflicting outputs...
2021-11-21T09:25:16.860000Z TestFramework (INFO): Running test new unconfirmed inputs...
2021-11-21T09:25:16.869000Z TestFramework (INFO): Running test too many replacements...
2021-11-21T09:25:16.959000Z TestFramework (INFO): Running test opt-in...
2021-11-21T09:25:16.978000Z TestFramework (INFO): Running test RPC...
2021-11-21T09:25:16.999000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/Users/michael/github/fanquake-bitcoin/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "./test/functional/feature_rbf.py", line 79, in run_test
    self.test_rpc()
  File "./test/functional/feature_rbf.py", line 544, in test_rpc
    frawtx2a = self.nodes[0].fundrawtransaction(rawtx2, {"replaceable": True})
  File "/Users/michael/github/fanquake-bitcoin/test/functional/test_framework/coverage.py", line 49, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/Users/michael/github/fanquake-bitcoin/test/functional/test_framework/authproxy.py", line 144, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Insufficient funds (-4)
2021-11-21T09:25:17.056000Z TestFramework (INFO): Stopping nodes
2021-11-21T09:25:17.216000Z TestFramework (WARNING): Not cleaning up dir /var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/bitcoin_func_test_dzacmtp6
2021-11-21T09:25:17.216000Z TestFramework (ERROR): Test failed. Test logging available at /var/folders/z2/cn877pxd3czdfh47mfkmbwgm0000gn/T/bitcoin_func_test_dzacmtp6/test_framework.log
```

**Comment by MarcoFalke** [comment]
Can be worked around by:


```diff
diff --git a/test/functional/feature_rbf.py b/test/functional/feature_rbf.py
index e540cc157..a2f07ca46 100755
--- a/test/functional/feature_rbf.py
+++ b/test/functional/feature_rbf.py
@@ -540,6 +540,7 @@ class ReplaceByFeeTest(BitcoinTestFramework):
 
         if self.is_wallet_compiled():
             self.init_wallet(node=0)
+            self.nodes[0].rescanblockchain()
             rawtx2 = self.nodes[0].createrawtransaction([], outs)
             frawtx2a = self.nodes[0].fundrawtransaction(rawtx2, {"replaceable": True})
             frawtx2b = self.nodes[0].fundrawtransaction(rawtx2, {"replaceable": False})
