### ISSUE TITLE
test:                                    AssertionError: not(59.99992540 == 59.999928) in interface_bitcoin_cli

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#23684]
https://cirrus-ci.com/task/4605959170424832?logs=ci#L3654

```
 test  2021-12-06T12:29:34.522000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/interface_bitcoin_cli.py", line 176, in run_test
                                       assert_equal(Decimal(cli_get_info['Balance']), amounts[i])
                                     File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/util.py", line 50, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(59.99992540 == 59.999928)

**Comment by MarcoFalke** [comment]
This is a build without bdb, to clarify

**Comment by mzumsande** [comment]
I get a similar looking error (some wrong trailing decimals) in `feature_coinstatsindex.py` when building without bdb.
