### ISSUE TITLE
test: failure in `interface_bitcoin_cli.py --legacy-wallet` with `--without-bdb`

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#23701]
Mentioned in #23686 which added the `interface_bitcoin_cli.py --legacy-wallet` test. If we are compiled without bdb, then we shouldn't be trying to create and/test anything involving legacy wallets.

```bash
46/228 - interface_bitcoin_cli.py --legacy-wallet failed, Duration: 1 s
stdout:
2021-12-07T08:49:36.678000Z TestFramework (INFO): Initializing test directory /private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20211207_004607/interface_bitcoin_cli_180
2021-12-07T08:49:36.946000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/test_framework.py", line 131, in main
    self.setup()
  File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/test_framework.py", line 288, in setup
    self.setup_network()
  File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/test_framework.py", line 382, in setup_network
    self.setup_nodes()
  File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/test_framework.py", line 409, in setup_nodes
    self.import_deterministic_coinbase_privkeys()
  File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/test_framework.py", line 426, in import_deterministic_coinbase_privkeys
    self.init_wallet(node=i)
  File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/test_framework.py", line 433, in init_wallet
    n.createwallet(wallet_name=wallet_name, descriptors=self.options.descriptors, load_on_startup=True)
  File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/test_node.py", line 704, in createwallet
    return self.__getattr__('createwallet')(wallet_name, disable_private_keys, blank, passphrase, avoid_reuse, descriptors, load_on_startup, external_signer)
  File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/coverage.py", line 49, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/private/var/folders/tn/f_9sf1xx5t14qm_6f83q3b840000gn/T/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-apple-darwin19/test/functional/test_framework/authproxy.py", line 144, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Compiled without bdb support (required for legacy wallets) (-4)
```

**Comment by MarcoFalke** [comment]
fixed by f727d814bd8df5a5346c128dd4573e457c1970e1
