### ISSUE TITLE
ci: failure in rpc_scantxoutset.py

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#23847]
Seen in #23842. https://cirrus-ci.com/task/6388867203858432:
```bash
 node0 2021-12-22T19:23:59.527668Z [http] [httpserver.cpp:238] [http_request_cb] Received a POST request for / from 127.0.0.1:47384 
 node0 2021-12-22T19:23:59.527720Z [httpworker.1] [rpc/request.cpp:174] [parse] ThreadRPCServer method=scantxoutset user=__cookie__ 
 node0 2021-12-22T19:23:59.527890Z [httpworker.1] [logging/timer.h:57] [Log] FlushStateToDisk: write block and undo data to disk started 
 node0 2021-12-22T19:23:59.529826Z [httpworker.1] [logging/timer.h:57] [Log] FlushStateToDisk: write block and undo data to disk completed (1.92ms) 
 node0 2021-12-22T19:23:59.529841Z [httpworker.1] [logging/timer.h:57] [Log] FlushStateToDisk: write block index to disk started 
 node0 2021-12-22T19:23:59.530512Z [httpworker.1] [logging/timer.h:57] [Log] FlushStateToDisk: write block index to disk completed (0.66ms) 
 node0 2021-12-22T19:23:59.530530Z [httpworker.1] [logging/timer.h:57] [Log] FlushStateToDisk: write coins cache to disk (0 coins, 0kB) started 
 node0 2021-12-22T19:23:59.530557Z [httpworker.1] [txdb.cpp:161] [BatchWrite] Writing final batch of 0.00 MiB 
 node0 2021-12-22T19:23:59.530569Z [httpworker.1] [txdb.cpp:163] [BatchWrite] Committed 0 changed transaction outputs (out of 0) to coin database... 
 node0 2021-12-22T19:23:59.530578Z [httpworker.1] [logging/timer.h:57] [Log] FlushStateToDisk: write coins cache to disk (0 coins, 0kB) completed (0.04ms) 
 node0 2021-12-22T19:23:59.530591Z [httpworker.1] [validationinterface.cpp:244] [ChainStateFlushed] Enqueuing ChainStateFlushed: block hash=1da9728920712f0193810f287cb3b9ce59171e90d13b6dfe87094be9a6810176 
 test  2021-12-22T19:23:59.531000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/rpc_scantxoutset.py", line 72, in run_test
                                       assert_equal(self.nodes[0].scantxoutset("start", [ "wpkh(" + pubk1 + ")", "wpkh(" + pubk2 + ")", "wpkh(" + pubk3 + ")"])['total_amount'], Decimal("0.004"))
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 50, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(0E-8 == 0.004)
 node0 2021-12-22T19:23:59.531303Z [scheduler] [validationinterface.cpp:244] [operator()] ChainStateFlushed: block hash=1da9728920712f0193810f287cb3b9ce59171e90d13b6dfe87094be9a6810176 
 test  2021-12-22T19:23:59.532000Z TestFramework (DEBUG): Closing down network thread 
 test  2021-12-22T19:23:59.583000Z TestFramework (INFO): Stopping nodes 
 test  2021-12-22T19:23:59.583000Z TestFramework.node0 (DEBUG): Stopping node 
```

**Comment by fanquake** [comment]
Also seen in #20744: https://cirrus-ci.com/task/4651951055962112?logs=ci#L3487.

**Comment by MarcoFalke** [comment]
I can reproduce locally

**Comment by MarcoFalke** [comment]
This was introduced in commit 3ac38058ce :thinking: 

Seems odd either way that a blockchain rpc depends on the wallet, so would probably be best to remove the wallet and replace it with MiniWallet.
