### ISSUE TITLE
ci: failure in feature_startupnotify.py

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#23967]
Seen in https://cirrus-ci.com/task/6190790023053312?logs=functional_tests#L381 in the Win64 job:
```bash
 node0 2022-01-03T17:55:20.863953Z [C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\src\util\thread.cpp:17] [TraceThread] msghand thread start 
 test  2022-01-03T17:55:20.870000Z TestFramework.node0 (DEBUG): RPC successfully started 
 test  2022-01-03T17:55:20.870000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 132, in main
                                       self.run_test()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_startupnotify.py", line 29, in run_test
                                       assert os.path.exists(tmpdir_file)
                                   AssertionError
 test  2022-01-03T17:55:20.870000Z TestFramework (DEBUG): Closing down network thread 
```

**Comment by MarcoFalke** [comment]
Yeah, that should be a `wait_until`, not `assert`

**Comment by ryanofsky** [comment]
Saw another instance, not on windows

https://cirrus-ci.com/task/5158961778262016?logs=ci#L7630

```
2022-01-03T21:34:26.388000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_startupnotify.py", line 29, in run_test
    assert os.path.exists(tmpdir_file)
AssertionError
```

**Comment by fanquake** [comment]
Seen this again https://cirrus-ci.com/task/4803606300852224:
```bash
 test  2022-02-28T17:08:11.001000Z TestFramework (INFO): Test -startupnotify is executed once 
 test  2022-02-28T17:08:11.001000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 132, in main
                                       self.run_test()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_startupnotify.py", line 34, in run_test
                                       assert_equal(file_content.count(FILE_NAME), 1)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 51, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(0 == 1)
 test  2022-02-28T17:08:11.001000Z TestFramework (DEBUG): Closing down network thread 
 test  2022-02-28T17:08:11.001000Z TestFramework (INFO): Stopping nodes 
 test  2022-02-28T17:08:11.001000Z TestFramework.node0 (DEBUG): Stopping node 
```
