### ISSUE TITLE
ci: spurious failure in mining_prioritisetransaction.py (?)

### ISSUE THREAD

**Issue by sdaftuar** [bitcoin/bitcoin#24022]
Not totally sure but this looks like a spurious failure in the windows run, from https://github.com/bitcoin/bitcoin/pull/20726/checks?check_run_id=4764870441:

```
wallet_keypool.py --legacy-wallet                  | ✓ Passed  | 8 s
wallet_keypool_topup.py --descriptors              | ✓ Passed  | 25 s
wallet_keypool_topup.py --legacy-wallet            | ✓ Passed  | 39 s
wallet_labels.py --descriptors                     | ✓ Passed  | 9 s
wallet_labels.py --legacy-wallet                   | ✓ Passed  | 11 s
wallet_listdescriptors.py --descriptors            | ✓ Passed  | 2 s
wallet_listreceivedby.py --descriptors             | ✓ Passed  | 25 s
wallet_listreceivedby.py --legacy-wallet           | ✓ Passed  | 33 s
wallet_listsinceblock.py --descriptors             | ✓ Passed  | 17 s
wallet_listsinceblock.py --legacy-wallet           | ✓ Passed  | 14 s
wallet_listtransactions.py --descriptors           | ✓ Passed  | 33 s
wallet_listtransactions.py --legacy-wallet         | ✓ Passed  | 37 s
wallet_multisig_descriptor_psbt.py                 | ✓ Passed  | 14 s
wallet_multiwallet.py --descriptors                | ✓ Passed  | 52 s
wallet_multiwallet.py --legacy-wallet              | ✓ Passed  | 55 s
wallet_multiwallet.py --usecli                     | ✓ Passed  | 31 s
wallet_orphanedreward.py                           | ✓ Passed  | 11 s
wallet_reorgsrestore.py                            | ✓ Passed  | 7 s
wallet_resendwallettransactions.py --descriptors   | ✓ Passed  | 4 s
wallet_resendwallettransactions.py --legacy-wallet | ✓ Passed  | 7 s
wallet_send.py --descriptors                       | ✓ Passed  | 23 s
wallet_send.py --legacy-wallet                     | ✓ Passed  | 23 s
wallet_signer.py --descriptors                     | ✓ Passed  | 7 s
wallet_signmessagewithaddress.py                   | ✓ Passed  | 1 s
wallet_startup.py                                  | ✓ Passed  | 5 s
wallet_taproot.py                                  | ✓ Passed  | 82 s
wallet_transactiontime_rescan.py --descriptors     | ✓ Passed  | 16 s
wallet_transactiontime_rescan.py --legacy-wallet   | ✓ Passed  | 15 s
wallet_txn_clone.py                                | ✓ Passed  | 5 s
wallet_txn_clone.py --mineblock                    | ✓ Passed  | 7 s
wallet_txn_clone.py --segwit                       | ✓ Passed  | 5 s
wallet_txn_doublespend.py --descriptors            | ✓ Passed  | 6 s
wallet_txn_doublespend.py --legacy-wallet          | ✓ Passed  | 5 s
wallet_txn_doublespend.py --mineblock              | ✓ Passed  | 9 s
wallet_watchonly.py --legacy-wallet                | ✓ Passed  | 3 s
wallet_watchonly.py --usecli --legacy-wallet       | ✓ Passed  | 5 s
feature_backwards_compatibility.py --descriptors   | ○ Skipped | 0 s
feature_backwards_compatibility.py --legacy-wallet | ○ Skipped | 1 s
feature_bind_extra.py                              | ○ Skipped | 1 s
feature_init.py                                    | ○ Skipped | 1 s
feature_syscall_sandbox.py                         | ○ Skipped | 0 s
feature_taproot.py --previous_release              | ○ Skipped | 0 s
feature_txindex_compatibility.py                   | ○ Skipped | 0 s
mempool_compatibility.py                           | ○ Skipped | 0 s
rpc_bind.py --ipv4                                 | ○ Skipped | 0 s
rpc_bind.py --ipv6                                 | ○ Skipped | 1 s
rpc_bind.py --nonloopback                          | ○ Skipped | 1 s
wallet_upgradewallet.py --legacy-wallet            | ○ Skipped | 0 s
mining_prioritisetransaction.py                    | ✖ Failed  | 27 s

ALL                                                | ✖ Failed  | 9038 s (accumulated) 
Runtime: 2307 s


C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build>if 1 NEQ 0 exit /b 1 
��������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������������
```

**Comment by sdaftuar** [comment]
Looks like it failed while the test was trying to shut down, from https://api.cirrus-ci.com/v1/task/4693027317874688/logs/functional_tests.log:

```
113/234 - mining_prioritisetransaction.py failed, Duration: 27 s

stdout:
2022-01-10T18:17:07.035000Z TestFramework (INFO): Initializing test directory C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220110_174746\mining_prioritisetransaction_121

2022-01-10T18:17:28.655000Z TestFramework (INFO): Assert that prioritised transaction was mined

2022-01-10T18:17:30.639000Z TestFramework (INFO): Assert that de-prioritised transaction is still in mempool

2022-01-10T18:17:31.729000Z TestFramework (INFO): Assert that prioritised free transaction is accepted to mempool

2022-01-10T18:17:32.888000Z TestFramework (INFO): Stopping nodes

[node 0] Cleaning up leftover process



stderr:
Traceback (most recent call last):

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\authproxy.py", line 108, in _request

    return self._get_response()

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\authproxy.py", line 166, in _get_response

    http_response = self.__conn.getresponse()

  File "C:\Python39\lib\http\client.py", line 1349, in getresponse

    response.begin()

  File "C:\Python39\lib\http\client.py", line 316, in begin

    version, status, reason = self._read_status()

  File "C:\Python39\lib\http\client.py", line 285, in _read_status

    raise RemoteDisconnected("Remote end closed connection without"

http.client.RemoteDisconnected: Remote end closed connection without response



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\mining_prioritisetransaction.py", line 157, in <module>

    PrioritiseTransactionTest().main()

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 155, in main

    exit_code = self.shutdown()

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 304, in shutdown

    self.stop_nodes()

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 555, in stop_nodes

    node.stop_node(wait=wait, wait_until_stopped=False)

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_node.py", line 336, in stop_node

    self.stop(wait=wait)

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\coverage.py", line 49, in __call__

    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\authproxy.py", line 142, in __call__

    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\authproxy.py", line 113, in _request

    self.__conn.request(method, path, postdata, headers)

  File "C:\Python39\lib\http\client.py", line 1257, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "C:\Python39\lib\http\client.py", line 1303, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "C:\Python39\lib\http\client.py", line 1252, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "C:\Python39\lib\http\client.py", line 1012, in _send_output

    self.send(msg)

  File "C:\Python39\lib\http\client.py", line 952, in send

    self.connect()

  File "C:\Python39\lib\http\client.py", line 923, in connect

    self.sock = self._create_connection(

  File "C:\Python39\lib\socket.py", line 843, in create_connection

    raise err

  File "C:\Python39\lib\socket.py", line 831, in create_connection

    sock.connect(sa)

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by MarcoFalke** [comment]
This may have been an issue back in January (see also https://github.com/bitcoin/bitcoin/issues/24109 ).

Let us know if this still an issue these days.
