### ISSUE TITLE
test: failure in rpc_rawtransaction.py --descriptors

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#24107]
See in https://cirrus-ci.com/task/6352687573762048:
```bash
 node3 2022-01-20T07:28:55.722038Z [http] [httpserver.cpp:242] [http_request_cb] Received a POST request for / from 127.0.0.1:43982 
 node3 2022-01-20T07:28:55.722278Z [httpworker.0] [rpc/request.cpp:174] [parse] ThreadRPCServer method=getrawtransaction user=__cookie__ 
 test  2022-01-20T07:28:55.723000Z TestFramework (ERROR): JSONRPC error 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/rpc_rawtransaction.py", line 84, in run_test
                                       self.getrawtransaction_tests()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/rpc_rawtransaction.py", line 107, in getrawtransaction_tests
                                       assert_equal(self.nodes[n].getrawtransaction(txId), rawTxSigned['hex'])
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/coverage.py", line 49, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 144, in __call__
                                       raise JSONRPCException(response['error'], status)
                                   test_framework.authproxy.JSONRPCException: No such mempool transaction. Use -txindex or provide a block hash to enable blockchain transaction queries. Use gettransaction for wallet transactions. (-5)
 test  2022-01-20T07:28:55.724000Z TestFramework (DEBUG): Closing down network thread 
```

**Comment by jonatack** [comment]
Thanks. Same as #23991 and https://github.com/bitcoin/bitcoin/pull/22437/files#r779593489. I'll have a look today.
