### ISSUE TITLE
feature_versionbits_warning.py issue

### ISSUE THREAD

**Issue by brunoerg** [bitcoin/bitcoin#24109]
```
 test  2022-01-19T22:41:01.543000Z TestFramework.p2p (WARNING): Connection lost to 127.0.0.1:15128 due to [WinError 10054] An existing connection was forcibly closed by the remote host 
 test  2022-01-19T22:41:01.574000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 132, in main
                                       self.run_test()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_versionbits_warning.py", line 91, in run_test
                                       self.restart_node(0)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 563, in restart_node
                                       self.stop_node(i)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 549, in stop_node
                                       self.nodes[i].stop_node(expected_stderr, wait=wait)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_node.py", line 358, in stop_node
                                       self.wait_until_stopped()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_node.py", line 382, in wait_until_stopped
                                       wait_until_helper(self.is_node_stopped, timeout=timeout, timeout_factor=self.timeout_factor)
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 258, in wait_until_helper
                                       if predicate():
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_node.py", line 372, in is_node_stopped
                                       assert return_code == 0, self._node_msg(
                                   AssertionError: [node 0] Node returned non-zero exit code (3) when stopping
 test  2022-01-19T22:41:01.574000Z TestFramework (DEBUG): Closing down network thread 
 test  2022-01-19T22:41:01.636000Z TestFramework (INFO): Stopping nodes 
 test  2022-01-19T22:41:01.636000Z TestFramework.node0 (DEBUG): Stopping node 
```

https://cirrus-ci.com/task/6284577177075712?logs=functional_tests#L2567

**Comment by MarcoFalke** [comment]
See also #24022 and maybe #18623

**Comment by Nhaifbhuiyan1262** [comment]
How much have a my bit3

**Comment by MarcoFalke** [comment]
Let us know if this still an issue
