### ISSUE TITLE
22.x: darwin guix build currently failing

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#24110]
Guix building for Darwin, using the `22.x` branch currently fails due to a failing test in the python-certvalidator package. The test relies on a certificate, that expired 6 days ago..:
```bash
building /gnu/store/w8i5a3yfmayxhyjyr5ccnrh5pbx96pmq-python-oscryptotests-1.2.1.drv...
building /gnu/store/zpmm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv...
\ 'check' phasenote: keeping build directory `/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-1'
builder for `/gnu/store/zpmm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv' failed with exit code 1
build of /gnu/store/zpmm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv failed
View build log at '/var/log/guix/drvs/zp/mm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv.bz2'.
guix environment: error: build of `/gnu/store/zpmm8r9i2sx75f9ix9xs962qc5a7s3i7-python-certvalidator-0.1-1.e5bdb4b.drv' failed
....
======================================================================
ERROR: test_revocation_mode_soft (tests.test_validate.ValidateTests)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-0/source/tests/test_validate.py", line 85, in test_revocation_mode_soft
    validate_path(context, path)
  File "/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-0/source/tests/../certvalidator/validate.py", line 50, in validate_path
    return _validate_path(validation_context, path)
  File "/tmp/guix-build-python-certvalidator-0.1-1.e5bdb4b.drv-0/source/tests/../certvalidator/validate.py", line 358, in _validate_path
    raise PathValidationError(pretty_message(
certvalidator.errors.PathValidationError: The path could not be validated because the end-entity certificate expired 2022-01-14 12:00:00Z

----------------------------------------------------------------------
Ran 213 tests in 1.609s

FAILED (errors=1, skipped=10)
```

I have a fix for this in #24057, https://github.com/bitcoin/bitcoin/pull/24057/commits/85885919656a3f606f3d7f208378aabe95f3f62d, which can be backported to the 22.x branch.

**Comment by fanquake** [comment]
Was fixed by #24215.
