### ISSUE TITLE
feature_init intermittent issue:                                    UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1215-1217: unexpected end of data

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#24575]
Presumably because a Unicode character was only written partially.

```
 test  2022-03-15T19:13:39.817000Z TestFramework (ERROR): Unexpected exception caught during testing 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_init.py", line 79, in run_test
                                       node.start(extra_args=['-txindex=1', '-blockfilterindex=1', '-coinstatsindex=1'])
                                     File "/usr/lib/python3.8/contextlib.py", line 120, in __exit__
                                       next(self.gen)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 442, in wait_for_debug_log
                                       log = dl.read()
                                     File "/usr/lib/python3.8/codecs.py", line 322, in decode
                                       (result, consumed) = self._buffer_decode(data, self.errors, final)
                                   UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 1215-1217: unexpected end of data
```

https://cirrus-ci.com/task/5773197005029376?logs=ci#L5215

**Comment by jonatack** [comment]
Ran across this issue just now https://cirrus-ci.com/task/6682305988132864

**Comment by jonatack** [comment]
Another one: https://cirrus-ci.com/task/5447567851913216

**Comment by david-bakin** [comment]
Is this this issue or something I just did?

https://cirrus-ci.com/task/4666995277824000?logs=ci#L3403

**Comment by darosior** [comment]
Just ran into this in #24148: https://cirrus-ci.com/task/5477444768497664.
