### ISSUE TITLE
qa: Intermittent failure in feature_segwit.py --descriptors

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#24590]
https://api.cirrus-ci.com/v1/task/5763159330914304/logs/ci.log
```
5/238 - feature_segwit.py --descriptors failed, Duration: 11 s

stdout:
2022-03-16T18:38:33.242000Z TestFramework (INFO): Initializing test directory /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220316_183814/feature_segwit_225
2022-03-16T18:38:39.177000Z TestFramework (INFO): Verify sigops are counted in GBT with pre-BIP141 rules before the fork
2022-03-16T18:38:43.168000Z TestFramework (INFO): Verify witness txs cannot be mined before the fork
2022-03-16T18:38:43.200000Z TestFramework (INFO): Verify unsigned p2sh witness txs without a redeem script are invalid
2022-03-16T18:38:43.630000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_segwit.py", line 210, in run_test
    self.generate(self.nodes[0], 4)  # blocks 428-431
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 639, in generate
    blocks = generator.generate(*args, invalid_call=False, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 303, in generate
    return self.generatetoaddress(nblocks=nblocks, address=self.get_deterministic_priv_key().address, maxtries=maxtries, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_node.py", line 311, in generatetoaddress
    return self.__getattr__('generatetoaddress')(*args, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/coverage.py", line 49, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 144, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: CreateNewBlock: TestBlockValidity failed: unexpected-witness, ContextualCheckBlock : unexpected witness data found (-1)
2022-03-16T18:38:43.682000Z TestFramework (INFO): Stopping nodes
2022-03-16T18:38:43.856000Z TestFramework (WARNING): Not cleaning up dir /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220316_183814/feature_segwit_225
2022-03-16T18:38:43.856000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220316_183814/feature_segwit_225/test_framework.log
2022-03-16T18:38:43.866000Z TestFramework (ERROR): 
2022-03-16T18:38:43.866000Z TestFramework (ERROR): Hint: Call /tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/combine_logs.py '/tmp/cirrus-ci-build/ci/scratch/test_runner/test_runner_₿_🏃_20220316_183814/feature_segwit_225' to consolidate all logs
2022-03-16T18:38:43.866000Z TestFramework (ERROR): 
2022-03-16T18:38:43.866000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2022-03-16T18:38:43.867000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2022-03-16T18:38:43.867000Z TestFramework (ERROR): 
```

**Comment by MarcoFalke** [comment]
#24578
