### ISSUE TITLE
ci: failure wallet_send.py --legacy-wallet  

### ISSUE THREAD

**Issue by brunoerg** [bitcoin/bitcoin#24616]
https://cirrus-ci.com/task/4929921716846592?logs=functional_tests#L2737

```
 test  2022-03-18T20:16:34.251000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 132, in main
                                       self.run_test()
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\wallet_send.py", line 560, in run_test
                                       assert_fee_amount(testres["fees"]["base"], testres["vsize"], Decimal(0.0001))
                                     File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 46, in assert_fee_amount
                                       raise AssertionError("Fee of %s BTC too high! (Should be %s BTC)" % (str(fee), str(target_fee)))
                                   AssertionError: Fee of 0.00003160 BTC too high! (Should be 0.0000313 BTC)
```

**Comment by brunoerg** [comment]
Closing it because there is another issue related to it.
