### ISSUE TITLE
Intermittent win64 CI failure in feature_index_prune.py

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#25031]
https://cirrus-ci.com/task/6532449864777728

Win64 native  [msvc] task

```
 test  2022-04-29T14:22:15.843000Z TestFramework (WARNING): Not cleaning up dir C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220429_140215\feature_index_prune_242 

 test  2022-04-29T14:22:15.843000Z TestFramework (ERROR): Test failed. Test logging available at C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220429_140215\feature_index_prune_242/test_framework.log 

 test  2022-04-29T14:22:15.843000Z TestFramework (ERROR): 
 node0 stderr Error: basic block filter index best block of the index goes beyond pruned data. Please disable the index or reindex (which will download the whole blockchain again) 
 node1 stderr Error: coinstatsindex best block of the index goes beyond pruned data. Please disable the index or reindex (which will download the whole blockchain again) 
 node2 stderr Error: basic block filter index best block of the index goes beyond pruned data. Please disable the index or reindex (which will download the whole blockchain again)

**Comment by jonatack** [comment]
This test passes locally for me in 11-12 minutes (debian testing), albeit only with timeouts disabled `test/functional/feature_index_prune.py --timeout-factor=0`

**Comment by david-bakin** [comment]
I got the same at https://cirrus-ci.com/task/6464103580434432?logs=functional_tests#L3097:
```
test  2022-05-10T03:08:31.456000Z TestFramework (ERROR): Assertion failed 
                                Traceback (most recent call last):
                                    File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 133, in main
                                    self.run_test()
                                    File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_index_prune.py", line 141, in run_test
                                    self.sync_blocks(timeout=300)
                                    File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 680, in sync_blocks
                                    assert (all([len(x.getpeerinfo()) for x in rpc_connections]))
                                AssertionError
test  2022-05-10T03:08:31.456000Z TestFramework (DEBUG): Closing down network thread 
...
<lots of lines of other tests elided>
...
test  2022-05-10T03:08:35.705000Z TestFramework (WARNING): Not cleaning up dir C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220510_024705\feature_index_prune_242 
test  2022-05-10T03:08:35.705000Z TestFramework (ERROR): Test failed. Test logging available at C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220510_024705\feature_index_prune_242/test_framework.log 
test  2022-05-10T03:08:35.705000Z TestFramework (ERROR): 
test  2022-05-10T03:08:35.705000Z TestFramework (ERROR): Hint: Call C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\combine_logs.py 'C:\Users\ContainerAdministrator\AppData\Local\Temp\test_runner_₿_🏃_20220510_024705\feature_index_prune_242' to consolidate all logs 
test  2022-05-10T03:08:35.705000Z TestFramework (ERROR): 
test  2022-05-10T03:08:35.705000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log. 
test  2022-05-10T03:08:35.705000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues 
test  2022-05-10T03:08:35.705000Z TestFramework (ERROR):             
```
(I'm not sure how to do the upload of the combined log myself, but the link above should take you to the job.)

**Comment by ryanofsky** [comment]
Note the stack trace:

```
Traceback (most recent call last):

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 133, in main

    self.run_test()

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\feature_index_prune.py", line 141, in run_test

    self.sync_blocks(timeout=300)

  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 680, in sync_blocks

    assert (all([len(x.getpeerinfo()) for x in rpc_connections]))

AssertionError
```

**Comment by fjahr** [comment]
Thanks for the ping! I was unable to reproduce the issue locally but I agree with the analysis by @ryanofsky that there is a race going on between the establishment of the connection and that sanity check line in `sync_blocks` that fails.

I think the one-liner suggested would work I think but I think I would prefer to use the `addconnection` RPC which should have the same effect but the code is easier to read and debug. Suggested in #25123.

**Comment by MarcoFalke** [comment]
Can reproduce on master with a diff.


```diff
diff --git a/src/net.cpp b/src/net.cpp
index 1c775f9a3f..e2ddb7fe3b 100644
--- a/src/net.cpp
+++ b/src/net.cpp
@@ -1913,6 +1913,7 @@ void CConnman::ThreadOpenConnections(const std::vector<std::string> connect)
     // Connect to specific addresses
     if (!connect.empty())
     {
+        UninterruptibleSleep(1s);
         for (int64_t nLoop = 0;; nLoop++)
         {
             ProcessAddrFetch();
