### ISSUE TITLE
CI failure in feature_fee_estimation.py

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#25061]
https://cirrus-ci.com/task/5178042396966912?logs=ci#L3381

```
Traceback (most recent call last):
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 133, in main self.run_test()
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 297, in run_test self.sanity_check_estimates_range()
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 213, in sanity_check_estimates_range check_estimates(self.nodes[1], self.fees_per_kb)
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 115, in check_estimates check_smart_estimates(node, fees_seen)
File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_fee_estimation.py", line 102, in check_smart_estimates raise AssertionError(
AssertionError: Estimated fee (0.00108829) larger than last fee (0.00096573) for lower number of confirms
```

**Comment by MarcoFalke** [comment]
Pretty sure this is already reported

**Comment by MarcoFalke** [comment]
#23165

**Comment by jonatack** [comment]
> Pretty sure this is already reported

Thanks. I had searched the GitHub issues for `feature_fee_estimation` and it looks like GitHub doesn't find it with that search term, but these both work: `feature_fee_estimation.py` or `"feature fee estimation"`
