### ISSUE TITLE
p2p_filter intermittent failure (assert not filter_peer.tx_received)

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#25128]
https://cirrus-ci.com/task/5227425125629952?logs=ci#L3810

```
 test  2022-05-13T10:12:44.237000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 133, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_filter.py", line 224, in run_test
                                       self.test_filter(filter_peer)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_filter.py", line 204, in test_filter
                                       assert not filter_peer.tx_received
                                   AssertionError
```

Looks like a tx from a previous test is received, but I don't see how this could happen:

```
 test  2022-05-13T10:12:44.211000Z TestFramework (INFO): Check that request for filtered blocks is ignored if no filter is set 
 test  2022-05-13T10:12:44.195000Z TestFramework.p2p (DEBUG): Received message from 127.0.0.1:15536: msg_tx(tx=CTransaction(nVersion=2 vin=[CTxIn(prevout=COutPoint(hash=f42858379b446cd7252015d8e86c6d7efc471f21869c1f205c44fd87bab1e9b2 n=0) scriptSig= nSequence=0)] vout=[CTxOut(nValue=42.99999000 scriptPubKey=51202913b252fe537830f843bfdc5fa7d20ba48639a87c86ff837b92d083c55ad7c1), CTxOut(nValue=7.00000000 scriptPubKey=0014ad24a8b5432802973418b25352d5606492c24e4d)] wit=CTxWitness(CScriptWitness(51,c00000000000000000000000000000000000000000000000000000000000000001)) nLockTime=0))... (msg truncated)

**Comment by MarcoFalke** [comment]
Reproduced: https://drahtbot.space/temp_scratch/p2p_filter.tar.xz


```
 test  2022-12-30T09:33:49.167000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 134, in main
                                       self.run_test()
                                     File "/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_filter.py", line 240, in run_test
                                       self.test_filter(filter_peer_without_nrelay)
                                     File "/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_filter.py", line 204, in test_filter
                                       assert not filter_peer.tx_received
                                   AssertionError

**Comment by MarcoFalke** [comment]
I still don't understand how this can happen.

on_message takes the p2p_lock to update last_message and call on_msgtype under the same lock:

https://github.com/bitcoin/bitcoin/blob/2ec97825e70882262ee2b7d53dc1def788a60162/test/functional/test_framework/p2p.py#L377-L390

The wait should also take the p2p_lock internally: https://github.com/bitcoin/bitcoin/blob/2ec97825e70882262ee2b7d53dc1def788a60162/test/functional/p2p_filter.py#L194

The tx_received property is also guarded by the p2p_lock: https://github.com/bitcoin/bitcoin/blob/2ec97825e70882262ee2b7d53dc1def788a60162/test/functional/p2p_filter.py#L69-L80

As I fail to see how the lock is release in between, tx_received and last_message *should* be updated in one go. So the wait *should* only succeed if tx_received was also updated.

However, from the log it looks like the p2p_lock was intermittently released in the on_message function??

```
 test  2022-12-30T09:33:48.464000Z TestFramework (INFO): Check that request for filtered blocks is ignored if no filter is set 
 test  2022-12-30T09:33:48.288000Z TestFramework.p2p (DEBUG): Received message from 127.0.0.1:12488: msg_tx(tx=CTransaction(nVersion=2 vin=[CTxIn(prevout=COutPoint(hash=17576cfafe2ea026d9ab00f6082fe7cc81caf31f5060a1872693f5bf73bf6b11 n=0) scriptSig= nSequence=0)] vout=[CTxOut(nValue=42.99999000 scriptPubKey=51202913b252fe537830f843bfdc5fa7d20ba48639a87c86ff837b92d083c55ad7c1), CTxOut(nValue=7.00000000 scriptPubKey=512009f79ded0947576f92dc6be2a39c6e083bf6d239574d9b0d47226c1813d52539)] wit=CTxWitness(CScriptWitness(51,c00000000000000000000000000000000000000000000000000000000000000001)) nLockTime=... (msg truncated)

**Comment by MarcoFalke** [comment]
https://cirrus-ci.com/task/6016550344327168?logs=ci#L4478
