### ISSUE TITLE
Intermittent CI failure "fee too high" in wallet_send.py

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#25164]
https://cirrus-ci.com/task/6295015969259520

`wallet_send.py --descriptors`

```
 test  2022-04-22T21:26:09.984000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 133, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/wallet_send.py", line 560, in run_test
                                       assert_fee_amount(testres["fees"]["base"], testres["vsize"], Decimal(0.0001))
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/util.py", line 46, in assert_fee_amount
                                       raise AssertionError("Fee of %s BTC too high! (Should be %s BTC)" % (str(fee), str(target_fee)))
                                   AssertionError: Fee of 0.00003160 BTC too high! (Should be 0.0000313 BTC)
```

**Comment by jonatack** [comment]
It's 3 weeks old, closing, will re-open if see a new one. I think I recall seeing this more recently, though.

**Comment by mzumsande** [comment]
It still happens:
https://cirrus-ci.com/task/6418676576944128

```
 node0 2023-11-29T05:48:26.130808Z [httpworker.3] [txmempool.cpp:678] [check] [mempool] Checking mempool with 0 transactions and 0 inputs 
 test  2023-11-29T05:48:26.131000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
                                       self.run_test()
                                     File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_send.py", line 577, in run_test
                                       assert_fee_amount(testres["fees"]["base"], testres["vsize"], Decimal(0.0001))
                                     File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 52, in assert_fee_amount
                                       raise AssertionError("Fee of %s BTC too high! (Should be %s BTC)" % (str(fee), str(target_fee)))
                                   AssertionError: Fee of 0.00002520 BTC too high! (Should be 0.0000249 BTC)
```

**Comment by stratospher** [comment]
happened here too: https://cirrus-ci.com/task/4577902440742912?logs=ci#L2654

**Comment by m3dwards** [comment]
Seen this on my local windows machine:

```shell
2024-02-21T21:14:35.394000Z TestFramework.node0 (DEBUG): TestNode.generate() dispatches `generate` call to `generatetoaddress`
2024-02-21T21:14:36.537000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "C:\Users\Max\source\bitcoin\test\functional\test_framework\test_framework.py", line 131, in main
    self.run_test()
  File "C:\Users\Max\source\bitcoin/test/functional/wallet_send.py", line 577, in run_test
    assert_fee_amount(testres["fees"]["base"], testres["vsize"], Decimal(0.0001))
  File "C:\Users\Max\source\bitcoin\test\functional\test_framework\util.py", line 52, in assert_fee_amount
    raise AssertionError("Fee of %s BTC too high! (Should be %s BTC)" % (str(fee), str(target_fee)))
AssertionError: Fee of 0.00002520 BTC too high! (Should be 0.0000249 BTC)
2024-02-21T21:14:36.546000Z TestFramework (DEBUG): Closing down network thread
```
Currently running the functional tests in a loop and this happened once in 57 runs (so far).

**Comment by m3dwards** [comment]
When passing, this test's expected fee of 0.00002500 does not match the actual of 0.00002520. It passes because of the 2 byte allowance in `assert_fee_amount`. This happens because the calculation for the expected weight of an input is slightly off. I believe a better weight calculation would remove the 1 byte buffers and correctly calculate the _length_ of the number of scriptWitnesses rather than just adding the count directly to the weight. After speaking with @achow101 the buffers were added to account for the fact that sometimes ECDSA signatures can be 1 byte shorter than normal but in that case the buffer makes the estimate even further from the reality so I have simply removed them.

```diff
diff --git a/test/functional/wallet_send.py b/test/functional/wallet_send.py
index 6ce2a56bfc..fed34c250b 100755
--- a/test/functional/wallet_send.py
+++ b/test/functional/wallet_send.py
@@ -543,11 +543,16 @@ class WalletSendTest(BitcoinTestFramework):
                 break
         psbt_in = dec["inputs"][input_idx]
         # Calculate the input weight
-        # (prevout + sequence + length of scriptSig + scriptsig + 1 byte buffer) * WITNESS_SCALE_FACTOR + num scriptWitness stack items + (length of stack item + stack item) * N stack items + 1 byte buffer
+        # (prevout + sequence + length of scriptSig + scriptsig) * WITNESS_SCALE_FACTOR + len of num scriptWitness stack items + (length of stack item + stack item) * N stack items
+        # Note that occasionally this weight estimate may be slightly larger than the real weight
+        # as sometimes ECDSA signatures are one byte shorter than expected with a probability of 1/128
         len_scriptsig = len(psbt_in["final_scriptSig"]["hex"]) // 2 if "final_scriptSig" in psbt_in else 0
-        len_scriptsig += len(ser_compact_size(len_scriptsig)) + 1
-        len_scriptwitness = (sum([(len(x) // 2) + len(ser_compact_size(len(x) // 2)) for x in psbt_in["final_scriptwitness"]]) + len(psbt_in["final_scriptwitness"]) + 1) if "final_scriptwitness" in psbt_in else 0
-        input_weight = ((40 + len_scriptsig) * WITNESS_SCALE_FACTOR) + len_scriptwitness
+        len_scriptsig += len(ser_compact_size(len_scriptsig))
+        len_scriptwitness = (sum([(len(x) // 2) + len(ser_compact_size(len(x) // 2)) for x in psbt_in["final_scriptwitness"]]) + len(ser_compact_size(len(psbt_in["final_scriptwitness"])))) if "final_scriptwitness" in psbt_in else 0
+        len_prevout_txid = 32
+        len_prevout_index = 4
+        len_sequence = 4
+        input_weight = ((len_prevout_txid + len_prevout_index + len_sequence + len_scriptsig) * WITNESS_SCALE_FACTOR) + len_scriptwitness

         # Input weight error conditions
         assert_raises_rpc_error(
```

The reason for the flake was because with a probability of 1/128, the signatures on the transaction can be 1 byte shorter potentially making the whole transaction 249 vbytes. The proposed change above not only makes the expected and actual fees match (usually) but would also prevent the flake as the real fee of 0.00002500 would be within 2 bytes of the expected fee of 0.00002490 as afforded by `assert_fee_amount`.

@achow101 also suggested that an alternative solution could be to change the test to use taproot instead which has predictable signature lengths.

If we are happy with the solution proposed above, I can submit as PR.

**Comment by m3dwards** [comment]
That's correct, test that includes weight doesn't include other address types. Changing address types would just change coverage rather than add coverage.

I think the test is valid with the address type it has and the assert takes care of the fact the signatures can vary a bit in length so in my humble opinion just correcting the weight calculation is good.

**Comment by fanquake** [comment]
https://cirrus-ci.com/task/5938282698113024?logs=ci#L3358
