### ISSUE TITLE
test: failure in rpc_net.py

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#25741]
https://cirrus-ci.com/task/5789129014247424
```bash
 test  2022-07-29T10:31:54.510000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: '''' 
                                           self.wait_until(lambda: sum(peer['version'] != 0 for peer in to_connection.getpeerinfo()) == to_num_peers)
                                   '''
 test  2022-07-29T10:31:54.511000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 133, in main
                                       self.run_test()
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/rpc_net.py", line 68, in run_test
                                       self.test_getnetworkinfo()
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/rpc_net.py", line 144, in test_getnetworkinfo
                                       self.connect_nodes(0, 1)
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 594, in connect_nodes
                                       self.wait_until(lambda: sum(peer['version'] != 0 for peer in to_connection.getpeerinfo()) == to_num_peers)
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 717, in wait_until
                                       return wait_until_helper(test_function, timeout=timeout, timeout_factor=self.options.timeout_factor)
                                     File "/tmp/cirrus-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 277, in wait_until_helper
                                       raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
                                   AssertionError: Predicate ''''
                                           self.wait_until(lambda: sum(peer['version'] != 0 for peer in to_connection.getpeerinfo()) == to_num_peers)
                                   ''' not true after 2400.0 seconds
```

**Comment by jonatack** [comment]
https://cirrus-ci.com/task/5120821952774144?logs=ci#L619

**Comment by MarcoFalke** [comment]
Maybe the timeout should be reduced for ci to make the tail of logs actually usable to debug this issue?

**Comment by theStack** [comment]
https://cirrus-ci.com/task/5378490135478272?logs=ci#L4486

**Comment by MarcoFalke** [comment]
Was able to reproduce and keep the datadir:


```
wget https://drahtbot.space/temp_scratch/rpc_net_137.tar.xz
tar xvf rpc_net_137.tar.xz
./test/functional/combine_logs.py ./rpc_net_137/

**Comment by MarcoFalke** [comment]
Excerpt:

```
 test  2022-12-03T04:42:40.092000Z TestFramework (INFO): Test getnetworkinfo 
 node0 2022-12-03T04:42:40.094239Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.094989Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getnetworkinfo user=__cookie__ 
 node0 2022-12-03T04:42:40.160731Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.162322Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=setnetworkactive user=__cookie__ 
 node0 2022-12-03T04:42:40.163326Z [httpworker.0] [net.cpp:2196] [SetNetworkActive] SetNetworkActive: false 
 node0 2022-12-03T04:42:40.171697Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.172701Z [httpworker.2] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getnetworkinfo user=__cookie__ 
 node0 2022-12-03T04:42:40.181750Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.182466Z [httpworker.1] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getnetworkinfo user=__cookie__ 
 node0 2022-12-03T04:42:40.196431Z [net] [net.cpp:1093] [DisconnectNodes] [net] Network not active, dropping peer=0 
 node0 2022-12-03T04:42:40.196837Z [net] [net.cpp:1093] [DisconnectNodes] [net] Network not active, dropping peer=1 
 node0 2022-12-03T04:42:40.197178Z [net] [net.cpp:573] [CloseSocketDisconnect] [net] disconnecting peer=0 
 node0 2022-12-03T04:42:40.197629Z [net] [net.cpp:573] [CloseSocketDisconnect] [net] disconnecting peer=1 
 node1 2022-12-03T04:42:40.198047Z [net] [net.cpp:1327] [SocketHandlerConnected] [net] socket closed for peer=0 
 node0 2022-12-03T04:42:40.198486Z [net] [net_processing.cpp:1532] [FinalizeNode] [net] Cleared nodestate for peer=0 
 node0 2022-12-03T04:42:40.199611Z [net] [net_processing.cpp:1532] [FinalizeNode] [net] Cleared nodestate for peer=1 
 node0 2022-12-03T04:42:40.249479Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.250659Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getnetworkinfo user=__cookie__ 
 node0 2022-12-03T04:42:40.259784Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.261110Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=setnetworkactive user=__cookie__ 
 node0 2022-12-03T04:42:40.261822Z [httpworker.0] [net.cpp:2196] [SetNetworkActive] SetNetworkActive: true 
 node0 2022-12-03T04:42:40.265768Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.266549Z [httpworker.2] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:40.447599Z [net] [net.cpp:573] [CloseSocketDisconnect] [net] disconnecting peer=0 
 node1 2022-12-03T04:42:40.448203Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:40.450719Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:40.452776Z [net] [net_processing.cpp:1532] [FinalizeNode] [net] Cleared nodestate for peer=0 
 node1 2022-12-03T04:42:40.454527Z [net] [net.cpp:1327] [SocketHandlerConnected] [net] socket closed for peer=1 
 node1 2022-12-03T04:42:40.454850Z [net] [net.cpp:573] [CloseSocketDisconnect] [net] disconnecting peer=1 
 node1 2022-12-03T04:42:40.456376Z [net] [net_processing.cpp:1532] [FinalizeNode] [net] Cleared nodestate for peer=1 
 node0 2022-12-03T04:42:40.461781Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.462924Z [httpworker.1] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=addnode user=__cookie__ 
 node0 2022-12-03T04:42:40.463530Z [httpworker.1] [net.cpp:454] [ConnectNode] [net:debug] trying connection 127.0.0.1:12645 lastseen=0.0hrs 
 node0 2022-12-03T04:42:40.464641Z [httpworker.1] [net.cpp:2763] [CNode] [net] Added connection peer=3 
 node1 2022-12-03T04:42:40.464951Z [net] [net.cpp:2763] [CNode] [net] Added connection peer=2 
 node0 2022-12-03T04:42:40.465194Z [httpworker.1] [net.cpp:2776] [PushMessage] [net] sending version (114 bytes) peer=3 
 node1 2022-12-03T04:42:40.465533Z [net] [net.cpp:1037] [CreateNodeFromAcceptedSocket] [net] connection from 127.0.0.1:43104 accepted 
 node0 2022-12-03T04:42:40.465746Z [httpworker.1] [net_processing.cpp:1396] [PushNodeVersion] [net] send version message: version 70016, blocks=103, txrelay=1, peer=3 
 node1 2022-12-03T04:42:40.466282Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: version (114 bytes) peer=2 
 node1 2022-12-03T04:42:40.466694Z [msghand] [net.cpp:2776] [PushMessage] [net] sending version (114 bytes) peer=2 
 node1 2022-12-03T04:42:40.467080Z [msghand] [net_processing.cpp:1396] [PushNodeVersion] [net] send version message: version 70016, blocks=103, txrelay=1, peer=2 
 node1 2022-12-03T04:42:40.467304Z [msghand] [net.cpp:2776] [PushMessage] [net] sending wtxidrelay (0 bytes) peer=2 
 node1 2022-12-03T04:42:40.467656Z [msghand] [net.cpp:2776] [PushMessage] [net] sending sendaddrv2 (0 bytes) peer=2 
 node1 2022-12-03T04:42:40.469706Z [msghand] [net.cpp:2776] [PushMessage] [net] sending verack (0 bytes) peer=2 
 node1 2022-12-03T04:42:40.470150Z [msghand] [net_processing.cpp:3360] [ProcessMessage] [net] receive version message: /Satoshi:24.99.0(testnode0)/: version 70016, blocks=103, us=[::]:0, txrelay=1, peer=2 
 node0 2022-12-03T04:42:40.475565Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.476434Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node0 2022-12-03T04:42:40.506581Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: version (114 bytes) peer=3 
 node0 2022-12-03T04:42:40.771191Z [msghand] [net.cpp:2776] [PushMessage] [net] sending wtxidrelay (0 bytes) peer=3 
 node0 2022-12-03T04:42:40.771817Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46108 
 node0 2022-12-03T04:42:40.772228Z [msghand] [net.cpp:2776] [PushMessage] [net] sending sendaddrv2 (0 bytes) peer=3 
 node1 2022-12-03T04:42:40.773808Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: wtxidrelay (0 bytes) peer=2 
 node0 2022-12-03T04:42:40.774343Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:40.774910Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: sendaddrv2 (0 bytes) peer=2 
 node0 2022-12-03T04:42:40.777441Z [msghand] [net.cpp:2776] [PushMessage] [net] sending verack (0 bytes) peer=3 
 node1 2022-12-03T04:42:40.778647Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: verack (0 bytes) peer=2 
 node0 2022-12-03T04:42:40.778716Z [msghand] [net.cpp:2776] [PushMessage] [net] sending getaddr (0 bytes) peer=3 
 node1 2022-12-03T04:42:40.779045Z [msghand] [net.cpp:2776] [PushMessage] [net] sending sendcmpct (9 bytes) peer=2 
 node0 2022-12-03T04:42:40.779325Z [msghand] [net_processing.cpp:3360] [ProcessMessage] [net] receive version message: /Satoshi:24.99.0(testnode1)/: version 70016, blocks=103, us=[::]:0, txrelay=1, peer=3 
 node1 2022-12-03T04:42:40.779772Z [msghand] [net.cpp:2776] [PushMessage] [net] sending ping (8 bytes) peer=2 
 node0 2022-12-03T04:42:40.780004Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: wtxidrelay (0 bytes) peer=3 
 node0 2022-12-03T04:42:40.780463Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: sendaddrv2 (0 bytes) peer=3 
 node1 2022-12-03T04:42:40.780546Z [msghand] [net.cpp:2776] [PushMessage] [net] sending getheaders (613 bytes) peer=2 
 node0 2022-12-03T04:42:40.780932Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: verack (0 bytes) peer=3 
 node1 2022-12-03T04:42:40.781261Z [msghand] [net_processing.cpp:5412] [SendMessages] [net] initial getheaders (102) to peer=2 (startheight:103) 
 node0 2022-12-03T04:42:40.781283Z [msghand] [net_processing.cpp:3403] [ProcessMessage] New outbound peer connected: version: 70016, blocks=103, peer=3 (manual) 
 node0 2022-12-03T04:42:40.781631Z [msghand] [net.cpp:2776] [PushMessage] [net] sending sendcmpct (9 bytes) peer=3 
 node1 2022-12-03T04:42:40.781768Z [msghand] [net.cpp:2776] [PushMessage] [net] sending feefilter (8 bytes) peer=2 
 node0 2022-12-03T04:42:40.782233Z [msghand] [net.cpp:2776] [PushMessage] [net] sending ping (8 bytes) peer=3 
 node1 2022-12-03T04:42:40.782475Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: getaddr (0 bytes) peer=2 
 node0 2022-12-03T04:42:40.783207Z [msghand] [net.cpp:2776] [PushMessage] [net] sending getheaders (613 bytes) peer=3 
 node0 2022-12-03T04:42:40.783894Z [msghand] [net_processing.cpp:5412] [SendMessages] [net] initial getheaders (102) to peer=3 (startheight:103) 
 node0 2022-12-03T04:42:40.784428Z [msghand] [net.cpp:2776] [PushMessage] [net] sending feefilter (8 bytes) peer=3 
 node1 2022-12-03T04:42:40.784506Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: sendcmpct (9 bytes) peer=2 
 node1 2022-12-03T04:42:40.785098Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: ping (8 bytes) peer=2 
 node0 2022-12-03T04:42:40.785120Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: sendcmpct (9 bytes) peer=3 
 node1 2022-12-03T04:42:40.785471Z [msghand] [net.cpp:2776] [PushMessage] [net] sending pong (8 bytes) peer=2 
 node0 2022-12-03T04:42:40.785673Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: ping (8 bytes) peer=3 
 node0 2022-12-03T04:42:40.786024Z [msghand] [net.cpp:2776] [PushMessage] [net] sending pong (8 bytes) peer=3 
 node0 2022-12-03T04:42:40.786679Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: getheaders (613 bytes) peer=3 
 node1 2022-12-03T04:42:40.786709Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:40.787419Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: getheaders (613 bytes) peer=2 
 node0 2022-12-03T04:42:40.787480Z [msghand] [net_processing.cpp:3938] [ProcessMessage] [net] getheaders 103 to end from peer=3 
 node1 2022-12-03T04:42:40.787866Z [msghand] [net_processing.cpp:3938] [ProcessMessage] [net] getheaders 103 to end from peer=2 
 node0 2022-12-03T04:42:40.787874Z [msghand] [net.cpp:2776] [PushMessage] [net] sending headers (82 bytes) peer=3 
 node1 2022-12-03T04:42:40.788324Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node0 2022-12-03T04:42:40.788686Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: feefilter (8 bytes) peer=3 
 node1 2022-12-03T04:42:40.788788Z [msghand] [net.cpp:2776] [PushMessage] [net] sending headers (82 bytes) peer=2 
 node0 2022-12-03T04:42:40.789470Z [msghand] [net_processing.cpp:4760] [ProcessMessage] [net] received: feefilter of 0.00000500 BTC/kvB from peer=3 
 node1 2022-12-03T04:42:40.789545Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: feefilter (8 bytes) peer=2 
 node0 2022-12-03T04:42:40.789963Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: pong (8 bytes) peer=3 
 node1 2022-12-03T04:42:40.789987Z [msghand] [net_processing.cpp:4760] [ProcessMessage] [net] received: feefilter of 0.00001000 BTC/kvB from peer=2 
 node0 2022-12-03T04:42:40.790480Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: headers (82 bytes) peer=3 
 node1 2022-12-03T04:42:40.790481Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: pong (8 bytes) peer=2 
 node1 2022-12-03T04:42:40.790999Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: headers (82 bytes) peer=2 
 node0 2022-12-03T04:42:40.792285Z [msghand] [net.cpp:2776] [PushMessage] [net] sending sendheaders (0 bytes) peer=3 
 node1 2022-12-03T04:42:40.792879Z [msghand] [net.cpp:2776] [PushMessage] [net] sending sendheaders (0 bytes) peer=2 
 node1 2022-12-03T04:42:40.793580Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: sendheaders (0 bytes) peer=2 
 node0 2022-12-03T04:42:40.793705Z [msghand] [net_processing.cpp:3147] [ProcessMessage] [net] received: sendheaders (0 bytes) peer=3 
 node1 2022-12-03T04:42:40.850287Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:40.851175Z [httpworker.2] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:40.919811Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:40.920840Z [httpworker.1] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:40.982748Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:40.983747Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.050396Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.051381Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.111389Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.112355Z [httpworker.2] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.174791Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.175846Z [httpworker.1] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.253119Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.253996Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.352674Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.353547Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.455060Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.455823Z [httpworker.2] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.554956Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.556033Z [httpworker.1] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.654634Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.655309Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.755241Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.756091Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:41.856037Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:41.857135Z [httpworker.2] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:42.057209Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:42.057881Z [httpworker.1] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:42.157823Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:42.158571Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:42.257935Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:42.258608Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:42.459945Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:42.460815Z [httpworker.2] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:42.560325Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:42.561041Z [httpworker.1] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:42.659419Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:42.660179Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__ 
 node1 2022-12-03T04:42:42.776446Z [http] [httpserver.cpp:241] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54300 
 node1 2022-12-03T04:42:42.778739Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getpeerinfo user=__cookie__
