### ISSUE TITLE
test: BDB-only build fails wallet_basic.py

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#26029]
Steps to reproduce:

* Compile bdb-only
* Run wallet_basic.py

```
 test  2022-09-05T10:20:34.866000Z TestFramework (ERROR): JSONRPC error 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/bitcoin-core/test/functional/test_framework/test_framework.py", line 133, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/bitcoin-core/test/functional/wallet_basic.py", line 708, in run_test
                                       self.nodes[0].createwallet(wallet_name="wo", descriptors=True, disable_private_keys=True)
                                     File "/tmp/cirrus-ci-build/bitcoin-core/test/functional/test_framework/test_node.py", line 754, in createwallet
                                       return self.__getattr__('createwallet')(wallet_name, disable_private_keys, blank, passphrase, avoid_reuse, descriptors, load_on_startup, external_signer)
                                     File "/tmp/cirrus-ci-build/bitcoin-core/test/functional/test_framework/coverage.py", line 49, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                     File "/tmp/cirrus-ci-build/bitcoin-core/test/functional/test_framework/authproxy.py", line 144, in __call__
                                       raise JSONRPCException(response['error'], status)
                                   test_framework.authproxy.JSONRPCException: Compiled without sqlite support (required for descriptor wallets) (-4)

**Comment by kouloumos** [comment]
The same error also occurs when bdb-only for `wallet_listsinceblock.py`.  

It's because of the test cases added in https://github.com/bitcoin/bitcoin/pull/25504 which run without checking for `options.descriptors`
