### ISSUE TITLE
test: failure in interface_rest.py 

### ISSUE THREAD

**Issue by aureleoules** [bitcoin/bitcoin#26098]
https://cirrus-ci.com/task/6131758964932608?logs=functional_tests#L43

```
Traceback (most recent call last):
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 133, in main
    self.run_test()
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\interface_rest.py", line 293, in run_test
    json_obj = self.test_rest_request(f"/blockfilterheaders/basic/{bb_hash}", query_params={"count": 5})
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\interface_rest.py", line 85, in test_rest_request
    assert_equal(resp.status, status)
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\util.py", line 56, in assert_equal
    raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
AssertionError: not(404 == 200)
```

**Comment by brunoerg** [comment]
I'm working on it.
