### ISSUE TITLE
test: `make test-security-check` fails on macOS arm64

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#26386]
On macOS 12.6 Monterey (Apple M1, 21G115):
```
% make test-security-check      
Command 'DYLD_CHAINED_FIXUPS' not parsed!
Command 'DYLD_EXPORTS_TRIE' not parsed!
Command 'DYLD_CHAINED_FIXUPS' not parsed!
Command 'DYLD_EXPORTS_TRIE' not parsed!
Traceback (most recent call last):
  File "/Users/hebasto/git/bitcoin/./contrib/devtools/security-check.py", line 254, in <module>
    if not func(binary):
  File "/Users/hebasto/git/bitcoin/./contrib/devtools/security-check.py", line 160, in check_MACHO_LAZY_BINDINGS
    return binary.dyld_info.lazy_bind == (0,0)
AttributeError: 'NoneType' object has no attribute 'lazy_bind'
F
======================================================================
FAIL: test_MACHO (__main__.TestSecurityChecks)
----------------------------------------------------------------------
Traceback (most recent call last):
  File "/Users/hebasto/git/bitcoin/./contrib/devtools/test-security-check.py", line 138, in test_MACHO
    self.assertEqual(call_security_check(cc, source, executable, ['-Wl,-flat_namespace','-fno-stack-protector']),
AssertionError: Tuples differ: (1, '') != (1, 'test1: failed NOUNDEFS LAZY_BINDINGS Canary')

First differing element 1:
''
'test1: failed NOUNDEFS LAZY_BINDINGS Canary'

- (1, '')
+ (1, 'test1: failed NOUNDEFS LAZY_BINDINGS Canary')

----------------------------------------------------------------------
Ran 1 test in 0.382s

FAILED (failures=1)
make: *** [test-security-check] Error 1
```

**Comment by fanquake** [comment]
Unless it: failing in a Guix build, it's not a bug, and isn't even expected to pass.

**Comment by hebasto** [comment]
> Unless it's failing in a Guix build, it's not a bug

Agree.

> ... and isn't even expected to pass.

At least, we run `make test-security-check` on the CI for macOS Intel.

**Comment by hebasto** [comment]
It works. It seems I had some issues with python packages.

Sorry for noise.

---

FWIW, my current `lief§ package details are as follows:
```
% pip3 show lief                                 
Name: lief
Version: 0.12.2
Summary: Library to instrument executable formats
Home-page: https://github.com/lief-project/LIEF
Author: Romain Thomas
Author-email: contact@lief.re
License: Apache License 2.0
Location: /Users/hebasto/Library/Python/3.10/lib/python/site-packages
Requires: 
Required-by: 
```
