### ISSUE TITLE
test: sqlite tests on freebsd fail with ModuleNotFoundError: No module named '_sqlite3'

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#26819]
It would be good if the test was skipped instead, or if the documentation explained how to install py-sqlite.

```
126/256 - wallet_descriptor.py --descriptors failed, Duration: 0 s
stdout:
stderr:
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/bitcoin-core/test/functional/wallet_descriptor.py", line 7, in <module>
    import sqlite3
  File "/usr/local/lib/python3.9/sqlite3/__init__.py", line 57, in <module>
    from sqlite3.dbapi2 import *
  File "/usr/local/lib/python3.9/sqlite3/dbapi2.py", line 27, in <module>
    from _sqlite3 import *
ModuleNotFoundError: No module named '_sqlite3'

**Comment by 09090997** [comment]
Yo

**Comment by MarcoFalke** [comment]
Closing for now, due to low priority. Bug fixes are still welcome

**Comment by 09090997** [comment]
Wtf?¿??
