### ISSUE TITLE
Intermittent failure in mining_getblocktemplate_longpoll.py

### ISSUE THREAD

**Issue by mzumsande** [bitcoin/bitcoin#26962]
Seen on master, https://cirrus-ci.com/task/6706434163867648?logs=ci#L5577
```
2023-01-24T20:06:14.173000Z TestFramework (INFO): Test that introducing a new transaction into the mempool will terminate the longpoll
2023-01-24T20:07:34.182000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 134, in main
    self.run_test()
  File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/mining_getblocktemplate_longpoll.py", line 74, in run_test
    assert not thr.is_alive()
AssertionError
2023-01-24T20:07:

```

**Comment by MarcoFalke** [comment]
My guess is that the thread (or memory, or storage) is put to sleep for several seconds. Not sure how to fix this, though.

**Comment by MarcoFalke** [comment]
I am seeing it regularly. (A few times per month, depending on how many CI runs you look at in the month, see https://github.com/bitcoin/bitcoin/issues/19684#issuecomment-1082031824)

But there is also the tx delay issue, #19732, so maybe we just give up and accept some failures
