### ISSUE TITLE
Intermittent issue in wallet_pruning.py

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#27065]
```
wget https://drahtbot.space/temp_scratch/wallet_pruning_258.tar.xz
tar -xvf ./wallet_pruning_258.tar.xz
test/functional/combine_logs.py -c ./wallet_pruning_258
```

```
 test  2023-02-08T07:00:29.787000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 134, in main
                                       self.run_test()
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_pruning.py", line 127, in run_test
                                       self.mine_large_blocks(self.nodes[0], 50)
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_pruning.py", line 63, in mine_large_blocks
                                       self.sync_all()
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 728, in sync_all
                                       self.sync_blocks(nodes)
                                     File "/root/bitcoin-core/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 697, in sync_blocks
                                       assert (all([len(x.getpeerinfo()) for x in rpc_connections]))
                                   AssertionError

**Comment by MarcoFalke** [comment]
Looks like there is a timeout due to mocktime:

```
 test  2023-02-08T07:00:06.288000Z TestFramework (INFO): Initializing test directory /root/bitcoin-core/ci/scratch/test_runner/test_runner_₿_🏃_20230208_070004/wallet_pruning_258 
[...]
 node0 2023-02-08T07:00:08.879142Z [httpworker.2] [validation.cpp:2586] [UpdateTipLog] UpdateTip: new best=4198d97f81c8f149dd154b45f0ebb0a1a1caa2e9634da87390040c4250d37166 height=229 version=0x30000000 log2_work=8.845490 tx=230 date='2023-02-08T07:00:46Z' progress=1.000000 cache=0.0MiB(229txo) 
[...]
 node0 2023-02-08T07:00:08.882662Z [msghand] [net_processing.cpp:5541] [SendMessages] [net] SendMessages: sending header 4198d97f81c8f149dd154b45f0ebb0a1a1caa2e9634da87390040c4250d37166 to peer=0
[...]
 node1 2023-02-08T07:00:09.283026Z [msghand] [net_processing.cpp:2672] [HeadersDirectFetchBlocks] [net] Large reorg, won't direct fetch to 4198d97f81c8f149dd154b45f0ebb0a1a1caa2e9634da87390040c4250d37166 (229) 
[...]
 node1 2023-02-08T07:00:10.375203Z [msghand] [net_processing.cpp:5807] [SendMessages] [net] Requesting block 4198d97f81c8f149dd154b45f0ebb0a1a1caa2e9634da87390040c4250d37166 (229) peer=0
[...]
 node0 2023-02-08T07:00:10.377206Z [msghand] [net_processing.cpp:3767] [ProcessMessage] [net] received getdata for: witness-block 4198d97f81c8f149dd154b45f0ebb0a1a1caa2e9634da87390040c4250d37166 peer=0
 node0 2023-02-08T07:00:10.377303Z [msghand] [net.cpp:2787] [PushMessage] [net] sending block (253 bytes) peer=0
[...]
 node1 2023-02-08T07:00:10.592529Z (mocktime: 2023-02-08T07:10:51Z) [msghand] [net_processing.cpp:5752] [SendMessages] Timeout downloading block 4198d97f81c8f149dd154b45f0ebb0a1a1caa2e9634da87390040c4250d37166 from peer=0, disconnecting
