### ISSUE TITLE
feature_index_prune.py failed on macOS

### ISSUE THREAD

**Issue by rex4539** [bitcoin/bitcoin#27091]
Latest master
macOS 13.2

```
2/262 - feature_index_prune.py failed, Duration: 203 s                                                  

stdout:
2023-02-13T12:45:50.370000Z TestFramework (INFO): Initializing test directory /var/folders/pn/rswd5k6175d02hbt25tvl47r0000gn/T/test_runner_₿_🏃_20230213_144546/feature_index_prune_259
2023-02-13T12:45:54.845000Z TestFramework (INFO): check if we can access blockfilters and coinstats when pruning is enabled but no blocks are actually pruned
2023-02-13T12:47:17.695000Z TestFramework (INFO): prune some blocks
2023-02-13T12:47:17.961000Z TestFramework (INFO): check if we can access the tips blockfilter and coinstats when we have pruned some blocks
2023-02-13T12:47:18.114000Z TestFramework (INFO): check if we can access the blockfilter and coinstats of a pruned block
2023-02-13T12:47:29.025000Z TestFramework (INFO): make sure trying to access the indices throws errors
2023-02-13T12:48:06.313000Z TestFramework (INFO): prune exactly up to the indices best blocks while the indices are disabled
2023-02-13T12:48:12.841000Z TestFramework (INFO): make sure that we can continue with the partially synced indices after having pruned up to the index height
2023-02-13T12:49:12.905000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: ''''
        self.wait_until(lambda: self.nodes[1].getindexinfo() == expected_stats)
'''
2023-02-13T12:49:12.906000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/rex/bitcoin/test/functional/test_framework/test_framework.py", line 134, in main
    self.run_test()
  File "/Users/rex/bitcoin/test/functional/feature_index_prune.py", line 116, in run_test
    self.sync_index(height=1500)
  File "/Users/rex/bitcoin/test/functional/feature_index_prune.py", line 33, in sync_index
    self.wait_until(lambda: self.nodes[1].getindexinfo() == expected_stats)
  File "/Users/rex/bitcoin/test/functional/test_framework/test_framework.py", line 732, in wait_until
    return wait_until_helper(test_function, timeout=timeout, timeout_factor=self.options.timeout_factor)
  File "/Users/rex/bitcoin/test/functional/test_framework/util.py", line 281, in wait_until_helper
    raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
AssertionError: Predicate ''''
        self.wait_until(lambda: self.nodes[1].getindexinfo() == expected_stats)
''' not true after 60.0 seconds
```

**Comment by fanquake** [comment]
Thanks. However these are more than likely due to resource contention, or issues on your local machine. I assume the same failure doesn't happen if you run the test directly?

**Comment by MarcoFalke** [comment]
Maybe the default timeout can be increased for this one?

**Comment by rex4539** [comment]
```
o% PYTHON_DEBUG=1 ./test/functional/test_runner.py feature_index_prune.py
Temporary test directory at /var/folders/pn/rswd5k6175d02hbt25tvl47r0000gn/T/test_runner_₿_🏃_20230213_155540
Running Unit Tests for Test Framework Modules
..........
----------------------------------------------------------------------
Ran 10 tests in 0.746s

OK
Remaining jobs: [feature_index_prune.py]
..............................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................................                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                                              1/1 - feature_index_prune.py passed, Duration: 434 s                                                                

TEST                   | STATUS    | DURATION

feature_index_prune.py | ✓ Passed  | 434 s

ALL                    | ✓ Passed  | 434 s (accumulated) 
Runtime: 434 s
```
