### ISSUE TITLE
feature_pruning.py failed on macOS

### ISSUE THREAD

**Issue by rex4539** [bitcoin/bitcoin#27092]
Latest master
macOS 13.2

```
39/262 - feature_pruning.py failed, Duration: 1365 s

stdout:
2023-02-13T12:45:50.370000Z TestFramework (INFO): Initializing test directory /var/folders/pn/rswd5k6175d02hbt25tvl47r0000gn/T/test_runner_₿_🏃_20230213_144546/feature_pruning_261
2023-02-13T12:45:55.313000Z TestFramework (INFO): Warning! This test requires 4GB of disk space
2023-02-13T12:45:55.313000Z TestFramework (INFO): Mining a big blockchain of 995 blocks
2023-02-13T12:56:41.112000Z TestFramework (INFO): Check that we haven't started pruning yet because we're below PruneAfterHeight
2023-02-13T12:56:41.113000Z TestFramework (INFO): Success
2023-02-13T12:56:41.114000Z TestFramework (INFO): Though we're already using more than 550MiB, current usage: 592.1861438751221
2023-02-13T12:56:41.114000Z TestFramework (INFO): Mining 25 more blocks should cause the first block file to be pruned
2023-02-13T12:57:03.339000Z TestFramework (INFO): Success
2023-02-13T12:57:03.341000Z TestFramework (INFO): Usage should be below target: 480.31389808654785
2023-02-13T12:57:03.341000Z TestFramework (INFO): Check that we'll exceed disk space target if we have a very high stale block rate
2023-02-13T12:57:03.341000Z TestFramework (INFO): Mine 24 (stale) blocks on Node 1, followed by 25 (main chain) block reorg from Node 0, for 12 rounds
2023-02-13T13:03:22.620000Z TestFramework (INFO): Usage can be over target because of high stale rate: 512.3138980865479
2023-02-13T13:03:22.624000Z TestFramework (INFO): Check that we can survive a 288 block reorg still
2023-02-13T13:03:22.625000Z TestFramework (INFO): Current block height: 1320
2023-02-13T13:03:22.626000Z TestFramework (INFO): Invalidating block 68d407cd9c6dd2892030c6181d713b3c28fe877f67b667efbd95f907258ae51d at height 1033
2023-02-13T13:03:24.215000Z TestFramework (INFO): New best height: 1032
2023-02-13T13:03:24.343000Z TestFramework (INFO): Generating new longer chain of 300 more blocks
2023-02-13T13:03:31.584000Z TestFramework (INFO): Reconnect nodes
2023-02-13T13:03:48.607000Z TestFramework (INFO): Verify height on node 2: 1332
2023-02-13T13:03:48.608000Z TestFramework (INFO): Usage possibly still high because of stale blocks in block files: 512.3138980865479
2023-02-13T13:03:48.608000Z TestFramework (INFO): Mine 220 more large blocks so we have requisite history
2023-02-13T13:06:34.969000Z TestFramework (INFO): Usage should be below target: 448.40030097961426
2023-02-13T13:06:34.970000Z TestFramework (INFO): Test that we can rerequest a block we previously pruned if needed for a reorg
2023-02-13T13:07:34.976000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/Users/rex/bitcoin/test/functional/test_framework/authproxy.py", line 168, in _get_response
    http_response = self.__conn.getresponse()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 1349, in getresponse
    response.begin()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 316, in begin
    version, status, reason = self._read_status()
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/http/client.py", line 277, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/Applications/Xcode.app/Contents/Developer/Library/Frameworks/Python3.framework/Versions/3.9/lib/python3.9/socket.py", line 704, in readinto
    return self._sock.recv_into(b)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/Users/rex/bitcoin/test/functional/test_framework/test_framework.py", line 134, in main
    self.run_test()
  File "/Users/rex/bitcoin/test/functional/feature_pruning.py", line 443, in run_test
    self.reorg_back()
  File "/Users/rex/bitcoin/test/functional/feature_pruning.py", line 227, in reorg_back
    self.nodes[2].verifychain(checklevel=4, nblocks=0)
  File "/Users/rex/bitcoin/test/functional/test_framework/coverage.py", line 49, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/Users/rex/bitcoin/test/functional/test_framework/authproxy.py", line 144, in __call__
    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/Users/rex/bitcoin/test/functional/test_framework/authproxy.py", line 108, in _request
    return self._get_response()
  File "/Users/rex/bitcoin/test/functional/test_framework/authproxy.py", line 170, in _get_response
    raise JSONRPCException({
test_framework.authproxy.JSONRPCException: 'verifychain' RPC took longer than 60.000000 seconds. Consider using larger timeout for calls that take longer to return. (-344)
```

**Comment by fanquake** [comment]
Thanks. However these are more than likely due to resource contention, or issues on your local machine. I assume the same failure doesn't happen if you run the test directly?
