### ISSUE TITLE
test: p2p_message_capture.py fails with undefined sanitizer

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#27149]
On Ubuntu 22.10

Relevant configure variable: `--with-sanitizers=undefined`

```
$ test/functional/p2p_message_capture.py 
2023-02-23T19:55:57.251000Z TestFramework (INFO): PRNG seed is: 8604348948412116696
2023-02-23T19:55:57.251000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_v2mn0yad
2023-02-23T19:55:57.666000Z TestFramework (INFO): Stopping nodes
Traceback (most recent call last):
  File "test/functional/p2p_message_capture.py", line 72, in <module>
    MessageCaptureTest().main()
  File "/home/sjors/dev/bitcoin/test/functional/test_framework/test_framework.py", line 157, in main
    exit_code = self.shutdown()
  File "/home/sjors/dev/bitcoin/test/functional/test_framework/test_framework.py", line 313, in shutdown
    self.stop_nodes()
  File "/home/sjors/dev/bitcoin/test/functional/test_framework/test_framework.py", line 577, in stop_nodes
    node.stop_node(wait=wait, wait_until_stopped=False)
  File "/home/sjors/dev/bitcoin/test/functional/test_framework/test_node.py", line 356, in stop_node
    raise AssertionError("Unexpected stderr {} != {}".format(stderr, expected_stderr))
AssertionError: Unexpected stderr streams.h:556:19: runtime error: null pointer passed as argument 1, which is declared to never be null != 
[node 0] Cleaning up leftover process

```

Seems pretty consistent on the latest master.

**Comment by Sjors** [comment]
Which suppression file?

Aha: https://github.com/bitcoin/bitcoin/blob/master/test/sanitizer_suppressions/ubsan

We should point to it in https://github.com/bitcoin/bitcoin/blob/master/doc/developer-notes.md#sanitizers
