### ISSUE TITLE
feature_config_args.py failure under `--valgrind`

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#27259]
This doesn't fail inside the Valgrind CI system, but seems to consistently fail in a (non-timeout) fashion when running the functional tests under `--valgrind`. Done on Ubuntu 22.04, with Vagrind `valgrind-3.21.0.GIT`. master at 460e394625fab2942748aaeec9be31f460f91c58.
```bash
254/262 - feature_config_args.py failed, Duration: 54 s

stdout:
2023-03-14T20:40:35.820000Z TestFramework (INFO): PRNG seed is: 3139282899219230712
2023-03-14T20:40:35.821000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10
2023-03-14T20:40:59.872000Z TestFramework (INFO): Test config args logging
2023-03-14T20:41:09.130000Z TestFramework (INFO): Test seed peers
2023-03-14T20:41:28.917000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/ubuntu/bitcoin/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/home/ubuntu/bitcoin/test/functional/feature_config_args.py", line 288, in run_test
    self.test_seed_peers()
  File "/home/ubuntu/bitcoin/test/functional/feature_config_args.py", line 213, in test_seed_peers
    with self.nodes[0].assert_debug_log(expected_msgs=[
  File "/usr/lib/python3.10/contextlib.py", line 142, in __exit__
    next(self.gen)
  File "/home/ubuntu/bitcoin/test/functional/test_framework/test_node.py", line 444, in assert_debug_log
    self._raise_assertion_error('Expected messages "{}" does not partially match log:\n\n{}\n\n'.format(str(expected_msgs), print_log))
  File "/home/ubuntu/bitcoin/test/functional/test_framework/test_node.py", line 173, in _raise_assertion_error
    raise AssertionError(self._node_msg(msg))
AssertionError: [node 0] Expected messages "['Loaded 0 addresses from peers.dat', 'DNS seeding disabled', 'Adding fixed seeds as -dnsseed=0 (or IPv4/IPv6 connections are disabled via -onlynet), -addnode is not provided and all -seednode(s) attempted\n']" does not partially match log:

 - 
 - 
 - 
 - 
 - 
 - 2023-03-14T20:41:23.870481Z [init] [init/common.cpp:149] [LogPackageVersion] Bitcoin Core version v24.99.0-460e394625fa (release build)
 - 2023-03-14T20:41:23.897857Z [init] [init.cpp:680] [InitParameterInteraction] InitParameterInteraction: parameter interaction: -bind set -> setting -listen=1
 - 2023-03-14T20:41:24.198111Z [init] [kernel/context.cpp:21] [Context] Using the 'sse4(1way),sse41(4way),avx2(8way)' SHA256 implementation
 - 2023-03-14T20:41:24.201143Z [init] [random.cpp:99] [ReportHardwareRand] Using RdSeed as an additional entropy source
 - 2023-03-14T20:41:24.202115Z [init] [random.cpp:102] [ReportHardwareRand] Using RdRand as an additional entropy source
 - 2023-03-14T20:41:24.565512Z [init] [init/common.cpp:120] [StartLogging] Default data directory /home/ubuntu/.bitcoin
 - 2023-03-14T20:41:24.566901Z [init] [init/common.cpp:121] [StartLogging] Using data directory /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/regtest
 - 2023-03-14T20:41:24.568077Z [init] [init/common.cpp:126] [StartLogging] Config file: /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/bitcoin.conf
 - 2023-03-14T20:41:24.572728Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: regtest="1"
 - 2023-03-14T20:41:24.574541Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] bind="127.0.0.1"
 - 2023-03-14T20:41:24.574874Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] discover="0"
 - 2023-03-14T20:41:24.575102Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] dnsseed="0"
 - 2023-03-14T20:41:24.575359Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] fallbackfee="0.0002"
 - 2023-03-14T20:41:24.575578Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] fixedseeds="0"
 - 2023-03-14T20:41:24.575805Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] keypool="1"
 - 2023-03-14T20:41:24.576024Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] listenonion="0"
 - 2023-03-14T20:41:24.576257Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] natpmp="0"
 - 2023-03-14T20:41:24.576478Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] peertimeout="999999999"
 - 2023-03-14T20:41:24.576697Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] port="11120"
 - 2023-03-14T20:41:24.576917Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] printtoconsole="0"
 - 2023-03-14T20:41:24.577142Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] rpcdoccheck="1"
 - 2023-03-14T20:41:24.577365Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] rpcport="16120"
 - 2023-03-14T20:41:24.577587Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] server="1"
 - 2023-03-14T20:41:24.577885Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] shrinkdebugfile="0"
 - 2023-03-14T20:41:24.578111Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] unsafesqlitesync="1"
 - 2023-03-14T20:41:24.578329Z [init] [util/system.cpp:1076] [logArgsPrefix] Config file arg: [regtest] upnp="0"
 - 2023-03-14T20:41:24.579101Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: datadir="/tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0"
 - 2023-03-14T20:41:24.579411Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: debug=""
 - 2023-03-14T20:41:24.579643Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: debugexclude="libevent"
 - 2023-03-14T20:41:24.579868Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: debugexclude="leveldb"
 - 2023-03-14T20:41:24.580106Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: debugexclude="rand"
 - 2023-03-14T20:41:24.580342Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: dnsseed="0"
 - 2023-03-14T20:41:24.580557Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: fixedseeds="1"
 - 2023-03-14T20:41:24.580774Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: loglevel="trace"
 - 2023-03-14T20:41:24.580994Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: logsourcelocations=""
 - 2023-03-14T20:41:24.581213Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: logthreadnames=""
 - 2023-03-14T20:41:24.581433Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: logtimemicros=""
 - 2023-03-14T20:41:24.581655Z [init] [util/system.cpp:1076] [logArgsPrefix] Command-line arg: uacomment="testnode0"
 - 2023-03-14T20:41:24.584872Z [init] [init.cpp:1124] [AppInitMain] Using at most 125 automatic connections (1024 file descriptors available)
 - 2023-03-14T20:41:24.613504Z [init] [script/sigcache.cpp:102] [InitSignatureCache] Using 16 MiB out of 16 MiB requested for signature cache, able to store 524288 elements
 - 2023-03-14T20:41:24.637428Z [init] [validation.cpp:1732] [InitScriptExecutionCache] Using 16 MiB out of 16 MiB requested for script execution cache, able to store 524288 elements
 - 2023-03-14T20:41:24.639975Z [init] [init.cpp:1156] [AppInitMain] Script verification uses 15 additional threads
 - 2023-03-14T20:41:27.541899Z [init] [httpserver.cpp:192] [InitHTTPAllowList] [http] Allowing HTTP connections from: 127.0.0.0/8 ::1/128 
 - 2023-03-14T20:41:27.567750Z [init] [httpserver.cpp:337] [HTTPBindAddresses] Binding RPC on address ::1 port 16120
 - 2023-03-14T20:41:27.577316Z [scheduler] [util/thread.cpp:20] [TraceThread] scheduler thread start
 - 2023-03-14T20:41:27.595150Z [init] [httpserver.cpp:337] [HTTPBindAddresses] Binding RPC on address 127.0.0.1 port 16120
 - 2023-03-14T20:41:27.598979Z [init] [httpserver.cpp:417] [InitHTTPServer] [http] Initialized HTTP server
 - 2023-03-14T20:41:27.601010Z [init] [httpserver.cpp:419] [InitHTTPServer] [http] creating work queue of depth 16
 - 2023-03-14T20:41:27.604515Z [init] [rpc/server.cpp:289] [StartRPC] [rpc] Starting RPC
 - 2023-03-14T20:41:27.620975Z [init] [httprpc.cpp:296] [StartHTTPRPC] [rpc] Starting HTTP RPC server
 - 2023-03-14T20:41:27.622378Z [init] [httprpc.cpp:245] [InitRPCAuthentication] Using random cookie authentication.
 - 2023-03-14T20:41:27.631030Z [init] [rpc/request.cpp:106] [GenerateAuthCookie] Generated RPC authentication cookie /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/regtest/.cookie
 - 2023-03-14T20:41:27.637041Z [init] [httpserver.cpp:699] [RegisterHTTPHandler] [http] Registering HTTP handler for / (exactmatch 1)
 - 2023-03-14T20:41:27.641354Z [init] [httpserver.cpp:699] [RegisterHTTPHandler] [http] Registering HTTP handler for /wallet/ (exactmatch 0)
 - 2023-03-14T20:41:27.643874Z [init] [httpserver.cpp:441] [StartHTTPServer] [http] Starting HTTP server
 - 2023-03-14T20:41:27.644721Z [init] [httpserver.cpp:443] [StartHTTPServer] [http] starting 4 worker threads
 - 2023-03-14T20:41:27.778245Z [http] [httpserver.cpp:304] [ThreadHTTP] [http] Entering http event loop
 - 2023-03-14T20:41:27.790342Z [init] [wallet/load.cpp:51] [VerifyWallets] Using wallet directory /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/regtest/wallets
 - 2023-03-14T20:41:27.822936Z [init] [noui.cpp:56] [noui_InitMessage] init message: Verifying wallet(s)…
 - 2023-03-14T20:41:27.846484Z [init] [init.cpp:1241] [AppInitMain] Using /16 prefix for IP bucketing
 - 2023-03-14T20:41:27.882716Z [init] [noui.cpp:56] [noui_InitMessage] init message: Loading P2P addresses…
 - 2023-03-14T20:41:27.895682Z [http] [httpserver.cpp:256] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46800
 - 2023-03-14T20:41:27.931657Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getblockcount user=__cookie__
 - 2023-03-14T20:41:27.978323Z [init] [logging/timer.h:58] [Log] [addrman] CheckAddrman: new 0, tried 0, total 0 started
 - 2023-03-14T20:41:27.988699Z [init] [logging/timer.h:58] [Log] [addrman] CheckAddrman: completed (3.45ms)
 - 2023-03-14T20:41:28.006991Z [init] [addrdb.cpp:194] [LoadAddrman] Loaded 0 addresses from peers.dat  115ms
 - 2023-03-14T20:41:28.019458Z [init] [noui.cpp:56] [noui_InitMessage] init message: Loading banlist…
 - 2023-03-14T20:41:28.033539Z [init] [banman.cpp:38] [LoadBanlist] [net] Loaded 0 banned node addresses/subnets  6ms
 - 2023-03-14T20:41:28.040061Z [init] [net.cpp:1562] [SetTryNewOutboundPeer] [net] setting try another outbound peer=false
 - 2023-03-14T20:41:28.044870Z [init] [net.cpp:2237] [SetNetworkActive] SetNetworkActive: true
 - 2023-03-14T20:41:28.083697Z [init] [policy/fees.cpp:455] [Read] [estimatefee] Reading estimates: 190 buckets counting confirms up to 48 blocks
 - 2023-03-14T20:41:28.088447Z [init] [policy/fees.cpp:455] [Read] [estimatefee] Reading estimates: 190 buckets counting confirms up to 12 blocks
 - 2023-03-14T20:41:28.101952Z [init] [policy/fees.cpp:455] [Read] [estimatefee] Reading estimates: 190 buckets counting confirms up to 1008 blocks
 - 2023-03-14T20:41:28.131902Z [init] [init.cpp:1456] [AppInitMain] Cache configuration:
 - 2023-03-14T20:41:28.134593Z [init] [init.cpp:1457] [AppInitMain] * Using 2.0 MiB for block index database
 - 2023-03-14T20:41:28.137444Z [init] [init.cpp:1465] [AppInitMain] * Using 8.0 MiB for chain state database
 - 2023-03-14T20:41:28.149948Z [init] [init.cpp:1483] [AppInitMain] * Using 440.0 MiB for in-memory UTXO set (plus up to 286.1 MiB of unused mempool space)
 - 2023-03-14T20:41:28.159368Z [init] [noui.cpp:56] [noui_InitMessage] init message: Loading block index…
 - 2023-03-14T20:41:28.162439Z [init] [node/chainstate.cpp:166] [LoadChainstate] Validating signatures for all blocks.
 - 2023-03-14T20:41:28.165706Z [init] [node/chainstate.cpp:168] [LoadChainstate] Setting nMinimumChainWork=0000000000000000000000000000000000000000000000000000000000000000
 - 2023-03-14T20:41:28.181261Z [init] [dbwrapper.cpp:150] [CDBWrapper] Opening LevelDB in /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/regtest/blocks/index
 - 2023-03-14T20:41:28.331624Z [http] [httpserver.cpp:256] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46808
 - 2023-03-14T20:41:28.335383Z [httpworker.1] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getblockcount user=__cookie__
 - 2023-03-14T20:41:28.381068Z [init] [dbwrapper.cpp:158] [CDBWrapper] Opened LevelDB successfully
 - 2023-03-14T20:41:28.417920Z [init] [dbwrapper.cpp:183] [CDBWrapper] Using obfuscation key for /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/regtest/blocks/index: 0000000000000000
 - 2023-03-14T20:41:28.477659Z [init] [node/blockstorage.cpp:332] [LoadBlockIndexDB] LoadBlockIndexDB: last block file = 0
 - 2023-03-14T20:41:28.487961Z [init] [node/blockstorage.cpp:336] [LoadBlockIndexDB] LoadBlockIndexDB: last block file info: CBlockFileInfo(blocks=1, size=293, heights=0...0, time=2011-02-02...2011-02-02)
 - 2023-03-14T20:41:28.490877Z [init] [node/blockstorage.cpp:347] [LoadBlockIndexDB] Checking all blk files are present...
 - 2023-03-14T20:41:28.522217Z [init] [node/chainstate.cpp:106] [CompleteChainstateInitialization] Initializing chainstate Chainstate [ibd] @ height -1 (null)
 - 2023-03-14T20:41:28.525912Z [init] [dbwrapper.cpp:150] [CDBWrapper] Opening LevelDB in /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/regtest/chainstate
 - 2023-03-14T20:41:28.547666Z [init] [dbwrapper.cpp:158] [CDBWrapper] Opened LevelDB successfully
 - 2023-03-14T20:41:28.554506Z [init] [dbwrapper.cpp:183] [CDBWrapper] Using obfuscation key for /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/regtest/chainstate: 37d8dc8d956f119e
 - 2023-03-14T20:41:28.574601Z [init] [validation.cpp:4102] [LoadChainTip] Loaded best chain: hashBestChain=0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206 height=0 date=2011-02-02T23:16:42Z progress=1.000000
 - 2023-03-14T20:41:28.578374Z [init] [validation.cpp:5509] [MaybeRebalanceCaches] [snapshot] allocating all cache to the IBD chainstate
 - 2023-03-14T20:41:28.594626Z [init] [dbwrapper.cpp:150] [CDBWrapper] Opening LevelDB in /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/regtest/chainstate
 - 2023-03-14T20:41:28.598603Z [http] [httpserver.cpp:256] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46812
 - 2023-03-14T20:41:28.599392Z [httpworker.2] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getblockcount user=__cookie__
 - 2023-03-14T20:41:28.606727Z [init] [dbwrapper.cpp:158] [CDBWrapper] Opened LevelDB successfully
 - 2023-03-14T20:41:28.607335Z [init] [dbwrapper.cpp:183] [CDBWrapper] Using obfuscation key for /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/node0/regtest/chainstate: 37d8dc8d956f119e
 - 2023-03-14T20:41:28.610108Z [init] [validation.cpp:4890] [ResizeCoinsCaches] [Chainstate [ibd] @ height 0 (0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)] resized coinsdb cache to 8.0 MiB
 - 2023-03-14T20:41:28.611608Z [init] [validation.cpp:4892] [ResizeCoinsCaches] [Chainstate [ibd] @ height 0 (0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206)] resized coinstip cache to 440.0 MiB
 - 2023-03-14T20:41:28.618567Z [init] [noui.cpp:56] [noui_InitMessage] init message: Verifying blocks…
 - 2023-03-14T20:41:28.626781Z [init] [init.cpp:1526] [AppInitMain]  block index             465ms
 - 2023-03-14T20:41:28.638105Z [init] [init.cpp:1615] [AppInitMain] Setting NODE_NETWORK on non-prune mode
 - 2023-03-14T20:41:28.671945Z [init] [init.cpp:1703] [AppInitMain] block tree size = 1
 - 2023-03-14T20:41:28.673586Z [init] [init.cpp:1715] [AppInitMain] nBestHeight = 0
 - 2023-03-14T20:41:28.693827Z [init] [net.cpp:2170] [BindListenPort] Bound to 127.0.0.1:11120
 - 2023-03-14T20:41:28.698958Z [init] [net.cpp:2170] [BindListenPort] Bound to 127.0.0.1:18445
 - 2023-03-14T20:41:28.701917Z [loadblk] [util/thread.cpp:20] [TraceThread] loadblk thread start
 - 2023-03-14T20:41:28.718596Z [init] [addrdb.cpp:228] [ReadAnchors] Loaded 0 addresses from "anchors.dat"
 - 2023-03-14T20:41:28.724261Z [loadblk] [kernel/mempool_persist.cpp:121] [LoadMempool] Imported mempool transactions from disk: 0 succeeded, 0 failed, 0 expired, 0 already there, 0 waiting for initial broadcast
 - 2023-03-14T20:41:28.727724Z [loadblk] [util/thread.cpp:22] [TraceThread] loadblk thread exit
 - 2023-03-14T20:41:28.732327Z [init] [net.cpp:2341] [Start] 0 block-relay-only anchors will be tried for connections.
 - 2023-03-14T20:41:28.733494Z [init] [noui.cpp:56] [noui_InitMessage] init message: Starting network threads…
 - 2023-03-14T20:41:28.762270Z [init] [net.cpp:2376] [Start] DNS seeding disabled
 - 2023-03-14T20:41:28.816075Z [opencon] [util/thread.cpp:20] [TraceThread] opencon thread start
 - 2023-03-14T20:41:28.847255Z [net] [util/thread.cpp:20] [TraceThread] net thread start
 - 2023-03-14T20:41:28.856072Z [addcon] [util/thread.cpp:20] [TraceThread] addcon thread start
 - 2023-03-14T20:41:28.861055Z [init] [noui.cpp:56] [noui_InitMessage] init message: Done loading
 - 2023-03-14T20:41:28.863033Z [msghand] [util/thread.cpp:20] [TraceThread] msghand thread start
 - 2023-03-14T20:41:28.870955Z [http] [httpserver.cpp:256] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46818
 - 2023-03-14T20:41:28.871515Z [httpworker.3] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getblockcount user=__cookie__
 - 2023-03-14T20:41:28.888274Z [http] [httpserver.cpp:256] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:46818
 - 2023-03-14T20:41:28.888838Z [httpworker.0] [rpc/request.cpp:179] [parse] [rpc] ThreadRPCServer method=getmempoolinfo user=__cookie__


2023-03-14T20:41:28.968000Z TestFramework (INFO): Stopping nodes
2023-03-14T20:41:29.436000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10
2023-03-14T20:41:29.436000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10/test_framework.log
2023-03-14T20:41:29.437000Z TestFramework (ERROR): 
2023-03-14T20:41:29.437000Z TestFramework (ERROR): Hint: Call /home/ubuntu/bitcoin/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230314_195709/feature_config_args_10' to consolidate all logs
2023-03-14T20:41:29.437000Z TestFramework (ERROR): 
2023-03-14T20:41:29.437000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-03-14T20:41:29.437000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2023-03-14T20:41:29.437000Z TestFramework (ERROR): 


stderr:
```

**Comment by fanquake** [comment]
Ok this is timeout related. Going to close for now.
