### ISSUE TITLE
Memory leak in wallet_tests with BDB using address sanitizer

### ISSUE THREAD

**Issue by Sjors** [bitcoin/bitcoin#27283]
```
src/test/test_bitcoin --run_test=wallet_tests
```

Passed when configured without BDB, fails when configured with BDB:

```sh
./configure 'BDB_LIBS=-L/…' BDB_CFLAGS=-I/…/include CC=clang CXX=clang++ --enable-suppress-external-warnings --disable-asm --with-sanitizers=address --disable-fuzz-binary --without-gui
make -j33 -C src/test
src/test/test_bitcoin --run_test=wallet_tests

…

*** No errors detected

=================================================================
==637422==ERROR: LeakSanitizer: detected memory leaks

Direct leak of 320 byte(s) in 2 object(s) allocated from:
    #0 0x555592a03dbe in malloc (/home/sjors/dev/bitcoin/src/test/test_bitcoin+0x470dbe) (BuildId: 8a0fe1527885800d0ca318fefe6c7e66c608d5eb)
    #1 0x555595965e64 in __os_malloc (/home/sjors/dev/bitcoin/src/test/test_bitcoin+0x33d2e64) (BuildId: 8a0fe1527885800d0ca318fefe6c7e66c608d5eb)

SUMMARY: AddressSanitizer: 320 byte(s) leaked in 2 allocation(s).
make[3]: *** [Makefile:21823: wallet/test/wallet_tests.cpp.test] Error 1
```

There's other BDB related `-with-sanitizers=address` issues: #22592, #19034.

There's currently no suppression file for the address sanitizer and I don't know how to make one. It could make sense to suppress the ones we've found, keep a Github issue open for each of one to fix & remove the suppression.

**Comment by Sjors** [comment]
cc @achow101

**Comment by fanquake** [comment]
Doesn't look like you've provided anything more actionable or useful than the last comment in #19034?

**Comment by fanquake** [comment]
Also if you are going to open issues like this, can you provide more information. i.e you don't even tell us what version of the code this happens with. I guess we are meant to assume it's the latest commit in master? What compiler versions did you use? What system are you running on?

**Comment by Sjors** [comment]
@fanquake that was 65840 bytes, this one is 320 bytes, so I assume it's a different issue?

I was going to add more details if anyone couldn't reproduce it, but here we go:

Found it while testing a PR, but reproduced on master @ 40e1c4d4024b8ad35f2511b2e10bf80c5531dfde.

```
Ubuntu clang version 15.0.6
Target: x86_64-pc-linux-gnu

Ubuntu 22.10 (GNU/Linux 6.0.6-060006-generic x86_64)
```

@MarcoFalke I'll see if I can get that too work.

**Comment by fanquake** [comment]
> I was going to add more details if anyone couldn't reproduce it, but here we go

In future, save us all wasting our time, and provide the (trivial to do so) details initially.

**Comment by Sjors** [comment]
That test can be further narrowed down:

```
BOOST_FIXTURE_TEST_CASE(CreateWallet, TestChain100Setup)
{
    WalletContext context;
    context.args = &m_args;
    context.chain = m_node.chain.get();
    auto wallet = TestLoadWallet(context);
    // TestUnloadWallet(std::move(wallet));
    // wallet = TestLoadWallet(context);
    TestUnloadWallet(std::move(wallet));
}
```

Uncommenting the extra unload & load will trigger the sanitizer.

**Comment by Sjors** [comment]
I went back to the #18727 merge commit 0f204dd3f21b997334a0e99954c939db154b64ca where this test was introduced. In order to test that old commit, I used `contrib/install_db4.sh` as it existed at the time, but otherwise didn't use depends (can't get that old version of boost to build). I then recreated a narrowed down test:

```cpp
    auto chain = interfaces::MakeChain(m_node);
    auto wallet = TestLoadWallet(*chain);
    TestUnloadWallet(std::move(wallet));
    wallet = TestLoadWallet(*chain);
    TestUnloadWallet(std::move(wallet));
```

This did not produce a memory leak (the full test file does).

So I guess we have a `good` and `bad` for `bisect` now, but with all the build system changes it's a bit non-trivial. It may be more efficient to just figure out what causes the memory leak.

**Comment by Sjors** [comment]
It's not limited to the test. Running that commit in regtest, creating a wallet and then exiting triggers it too. That should make debugging easier...

**Comment by Sjors** [comment]
> This leak may be fixed in bdb5.3, but I haven't re-checked this.

I tried with `apt install libdb++-dev` version 5.3.21 (?_ and `./configure --with-incompatible-bdb …`

This shows "Using BerkeleyDB version Berkeley DB 5.3.28: (September  9, 2013)" in the log so that's a bit odd.

But in any case there's no leak. Not with valgrind (gcc) and not with the address sanitizer (clang).

**Comment by ryanofsky** [comment]
This is puzzling because https://github.com/bitcoin/bitcoin/issues/27283#issuecomment-1476822455 seems to suggest that memory is leaked while creating the BDB environment, but the commit which triggers the leak 8b5e7297c02f3100a9cb27bfe206e3fc617ec173 does not seem to be changing the way the environment is created or how it is used. The commit does switch from using a function called `CreateWalletDatabase` to another one called `MakeWalletDatabase`, but in both cases the functions are calling the same `GetWalletEnv` function to get a shared_ptr to the BerkeleyEnvironment, and passing that pointer to the BerkeleyDatabase constructor.

I guess the fact that the leak happens in one version of BDB but another suggests it is a BDB bug, but it's not clear what could be changing in commit 8b5e7297c02f3100a9cb27bfe206e3fc617ec173 which triggers the bug.

I haven't tried to reproduce this myself, though, so just going off of the information above.

**Comment by achow101** [comment]
I've been able to reproduce the leak that valgrind finds on master. It appears to be related to the `-privdb` option; looking at the BDB source, the problem occurs inside a block of code guarded by a check for the `DB_PRIVATE` flag. Disabling that with `-privdb=0` "resolves" the leak.

The bisect appears to be incorrect as the parent commit shows the same issue for me. I don't think there's really a solution for us other than upgrading BDB or ditching it entirely.

**Comment by Sjors** [comment]
One solution is to ignore the problem but fix the address sanitizer test suite.

This branch does that: https://github.com/bitcoin/bitcoin/compare/master...Sjors:bitcoin:2023/03/legacy-leak

It sets `options.use_shared_memory = true` for wallet unit tests, and it adds `-dbpriv=0` to the default config of functional tests.

The second commit also makes the wallet migration tool `use_shared_memory`. This seems safe, since the operation only runs briefly, so the concern about other processes snooping seems less pressing.

Strangely there's one test that still fails with a memory leak: `wallet_migration.py`, at "Test migration of a basic keys only wallet with a balance".

I can make a PR if people think it's the right approach.

**Comment by willcl-ark** [comment]
Can we close this and https://github.com/bitcoin/bitcoin/issues/19034 as "unplanned"?

In theory v28.0 will (hopefully) be the final version we will read BDB wallets at all, and we now have our own [BDB parser](https://github.com/bitcoin/bitcoin/pull/26606), and will (soon) be able to [migrate without BDB](https://github.com/bitcoin/bitcoin/pull/26596).

I don't see these issues ever being fixed, and therefore they are not useful to keep open IMO...
