### ISSUE TITLE
test: `interface_bitcoin_cli.py --descriptors` failure under `--valgrind`

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#27281]
Seen on a aarch64 Alpine box. Master @ 40e1c4d4024b8ad35f2511b2e10bf80c5531dfde. Binaries compiled with Clang 15.0.7. Valgrind `valgrind-3.21.0.GIT`.

```bash
79/262 - interface_bitcoin_cli.py --descriptors failed, Duration: 34 s

stdout:
2023-03-20T10:34:23.174000Z TestFramework (INFO): PRNG seed is: 6631947331891546746
2023-03-20T10:34:23.175000Z TestFramework (INFO): Initializing test directory /tmp/test_runner_₿_🏃_20230320_101936/interface_bitcoin_cli_187
2023-03-20T10:34:29.054000Z TestFramework (INFO): Compare responses from getblockchaininfo RPC and `bitcoin-cli getblockchaininfo`
2023-03-20T10:34:29.077000Z TestFramework (INFO): Test named arguments
2023-03-20T10:34:29.102000Z TestFramework (INFO): Test that later cli named arguments values silently overwrite earlier ones
2023-03-20T10:34:29.115000Z TestFramework (INFO): Test -stdinrpcpass option
2023-03-20T10:34:29.381000Z TestFramework (INFO): Test -stdin and -stdinrpcpass
2023-03-20T10:34:29.645000Z TestFramework (INFO): Test connecting to a non-existing server
2023-03-20T10:34:29.650000Z TestFramework (INFO): Test connecting with non-existing RPC cookie file
2023-03-20T10:34:29.908000Z TestFramework (INFO): Test -getinfo with arguments fails
2023-03-20T10:34:29.914000Z TestFramework (INFO): Test -getinfo with -color=never does not return ANSI escape codes
2023-03-20T10:34:29.952000Z TestFramework (INFO): Test -getinfo with -color=always returns ANSI escape codes
2023-03-20T10:34:29.967000Z TestFramework (INFO): Test -getinfo with invalid value for -color option
2023-03-20T10:34:29.984000Z TestFramework (INFO): Test -getinfo returns expected network and blockchain info
2023-03-20T10:34:31.647000Z TestFramework (INFO): Test -getinfo and bitcoin-cli return all proxies
2023-03-20T10:34:37.382000Z TestFramework (INFO): Test -getinfo and bitcoin-cli getwalletinfo return expected wallet info
2023-03-20T10:34:44.867000Z TestFramework (INFO): Test -getinfo with multiple wallets and -rpcwallet returns specified wallet balance
2023-03-20T10:34:45.005000Z TestFramework (INFO): Test -getinfo with multiple wallets and -rpcwallet=non-existing-wallet returns no balances
2023-03-20T10:34:45.039000Z TestFramework (INFO): Test -getinfo with multiple wallets returns all loaded wallet names and balances
2023-03-20T10:34:45.127000Z TestFramework (INFO): Test -getinfo after unloading all wallets except a non-default one returns its balance
2023-03-20T10:34:45.147000Z TestFramework (INFO): Test -getinfo with -rpcwallet=remaining-non-default-wallet returns only its balance
2023-03-20T10:34:45.165000Z TestFramework (INFO): Test -getinfo with -rpcwallet=unloaded wallet returns no balances
2023-03-20T10:34:45.410000Z TestFramework (INFO): Test -generate with no args
2023-03-20T10:34:45.456000Z TestFramework (INFO): Test -generate with bad args
2023-03-20T10:34:45.507000Z TestFramework (INFO): Test -generate with nblocks
2023-03-20T10:34:45.578000Z TestFramework (INFO): Test -generate with nblocks and maxtries
2023-03-20T10:34:45.654000Z TestFramework (INFO): Test -generate -rpcwallet in single-wallet mode
2023-03-20T10:34:45.707000Z TestFramework (INFO): Test -generate -rpcwallet=unloaded wallet raises RPC error
2023-03-20T10:34:45.837000Z TestFramework (INFO): Test -generate -rpcwallet with no args
2023-03-20T10:34:45.890000Z TestFramework (INFO): Test -generate -rpcwallet with bad args
2023-03-20T10:34:45.942000Z TestFramework (INFO): Test -generate -rpcwallet with nblocks
2023-03-20T10:34:46.021000Z TestFramework (INFO): Test -generate -rpcwallet with nblocks and maxtries
2023-03-20T10:34:46.263000Z TestFramework (INFO): Test -generate without -rpcwallet in multiwallet mode raises RPC error
2023-03-20T10:34:46.303000Z TestFramework (INFO): Test -version with node stopped
2023-03-20T10:34:46.670000Z TestFramework (INFO): Test -rpcwait option successfully waits for RPC connection
2023-03-20T10:34:52.150000Z TestFramework (INFO): Test -rpcwait option waits at most -rpcwaittimeout seconds for startup
2023-03-20T10:34:57.462000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/bitcoin/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/bitcoin/test/functional/interface_bitcoin_cli.py", line 333, in run_test
    assert_greater_than_or_equal(time.time(), start_time + 5)
  File "/bitcoin/test/functional/test_framework/util.py", line 66, in assert_greater_than_or_equal
    raise AssertionError("%s < %s" % (str(thing1), str(thing2)))
AssertionError: 1679308497.4619503 < 1679308497.462919
2023-03-20T10:34:57.513000Z TestFramework (INFO): Stopping nodes
2023-03-20T10:34:57.514000Z TestFramework (WARNING): Not cleaning up dir /tmp/test_runner_₿_🏃_20230320_101936/interface_bitcoin_cli_187
2023-03-20T10:34:57.514000Z TestFramework (ERROR): Test failed. Test logging available at /tmp/test_runner_₿_🏃_20230320_101936/interface_bitcoin_cli_187/test_framework.log
2023-03-20T10:34:57.514000Z TestFramework (ERROR): 
2023-03-20T10:34:57.514000Z TestFramework (ERROR): Hint: Call /bitcoin/test/functional/combine_logs.py '/tmp/test_runner_₿_🏃_20230320_101936/interface_bitcoin_cli_187' to consolidate all logs
2023-03-20T10:34:57.514000Z TestFramework (ERROR): 
2023-03-20T10:34:57.514000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log.
2023-03-20T10:34:57.514000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues
2023-03-20T10:34:57.514000Z TestFramework (ERROR): 
```

**Comment by fanquake** [comment]
> What is the combined log?

Unfortunately don't have one, and cannot seem to recreate this failure. Happy to close until have more useful info.
