### ISSUE TITLE
wallet_create_tx.py "Not solvable pre-selected input" exception

### ISSUE THREAD

**Issue by ryanofsky** [bitcoin/bitcoin#27316]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

CI test failure https://cirrus-ci.com/task/5315879898972160?logs=functional_tests#L2675:

```
test  2023-03-23T17:23:41.645000Z TestFramework (ERROR): JSONRPC error 
Traceback (most recent call last):
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\test_framework.py", line 132, in main
    self.run_test()
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\wallet_create_tx.py", line 35, in run_test
    self.test_create_too_long_mempool_chain()
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\wallet_create_tx.py", line 98, in test_create_too_long_mempool_chain
    tx_data = test_wallet.send(outputs=[{test_wallet.getnewaddress(): 25 - i}], options=options)
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\coverage.py", line 49, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "C:\Users\ContainerAdministrator\AppData\Local\Temp\cirrus-ci-build\test\functional\test_framework\authproxy.py", line 149, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: Not solvable pre-selected input COutPoint(e425cbbd63, 1) (-4)
```

(log also includes a `feature_config_args` failure not related to this issue)

### Expected behaviour

Test should pass. This seems like a race condition as there is an `AddToWallet` log line immediately below the exception.

### Steps to reproduce

Happened in CI on commit 53d99551e913bfb85769a2b34fed73898779ff0f, but probably does not happen reliably.

### Relevant log output

https://cirrus-ci.com/task/5315879898972160?logs=functional_tests#L2675

### How did you obtain Bitcoin Core

Other

### What version of Bitcoin Core are you using?

master@a70911492fcd1f726782cca2f1ffac18c25e8fb4

### Operating system and version

Windows

**Comment by furszy** [comment]
@jonatack https://github.com/bitcoin/bitcoin/pull/27318

**Comment by fanquake** [comment]
Also seen here https://cirrus-ci.com/task/4836577990410240

**Comment by josibake** [comment]
seen here: https://cirrus-ci.com/task/5086775773757440
