### ISSUE TITLE
ci: failure in feature_taproot.py (TSAN)

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#27595]
master at 26cb32c02d76d6635c67942a5eeb70a6199df69d. https://cirrus-ci.com/task/5769539133112320?logs=ci#L3369:
```bash
 node0 2023-05-08T14:19:47.988934Z [httpworker.1] [rpc/request.cpp:181] [parse] [rpc] ThreadRPCServer method=sendrawtransaction user=__cookie__ 
 test  2023-05-08T14:19:47.989000Z TestFramework (ERROR): JSONRPC error 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_taproot.py", line 1759, in run_test
                                       self.test_spenders(self.nodes[0], spenders_taproot_active(), input_counts=[1, 2, 2, 2, 2, 3])
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/feature_taproot.py", line 1509, in test_spenders
                                       node.sendrawtransaction(tx.serialize().hex(), 0)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/coverage.py", line 49, in __call__
                                       return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                                                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/authproxy.py", line 126, in __call__
                                       raise JSONRPCException(response['error'], status)
                                   test_framework.authproxy.JSONRPCException: non-mandatory-script-verify-flag (Data push larger than necessary) (-26)
 node0 2023-05-08T14:19:47.989451Z [httpworker.1] [txmempool.cpp:659] [check] [mempool] Checking mempool with 0 transactions and 0 inputs 
 test  2023-05-08T14:19:47.997000Z TestFramework (DEBUG): Closing down network thread 
```

**Comment by Andrew-SUPPORT** [comment]
Hello
