### ISSUE TITLE
wallet_importdescriptors.py: can't decode bytes in position 228861-228863: unexpected end of data

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#28030]
Failure in the TSAN job: https://cirrus-ci.com/task/5229709189971968?logs=ci#L1848:
```bash
 node0 2023-07-04T11:34:16.737172Z [httpworker.0] [wallet/wallet.h:895] [WalletLogPrintf] [encrypted_wallet] Scanning current mempool transactions. 
 node0 2023-07-04T11:34:16.737361Z [httpworker.0] [wallet/wallet.h:895] [WalletLogPrintf] [encrypted_wallet] Rescan completed in           53755ms 
 test  2023-07-04T11:34:16.743000Z TestFramework (ERROR): Unexpected exception caught during testing 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_importdescriptors.py", line 695, in run_test
                                       with self.nodes[0].assert_debug_log(expected_msgs=["Rescan started from block 0f9188f13cb7b2c71f2a335e3a4fc328bf5beb436012afca590b1a11466e2206... (slow variant inspecting all blocks)"], timeout=5):
                                     File "/usr/lib/python3.11/contextlib.py", line 144, in __exit__
                                       next(self.gen)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py", line 444, in assert_debug_log
                                       log = dl.read()
                                             ^^^^^^^^^
                                     File "<frozen codecs>", line 322, in decode
                                   UnicodeDecodeError: 'utf-8' codec can't decode bytes in position 228861-228863: unexpected end of data
 test  2023-07-04T11:34:16.778000Z TestFramework (DEBUG): Closing down network thread 
 test  2023-07-04T11:34:16.829000Z TestFramework (INFO): Stopping nodes 
 test  2023-07-04T11:34:16.829000Z TestFramework.node0 (DEBUG): Stopping node 
```

**Comment by furszy** [comment]
#28035 was merged, can this be closed?
