### ISSUE TITLE
p2p_getaddr_caching.py failure in TSan CI

### ISSUE THREAD

**Issue by jonatack** [bitcoin/bitcoin#28133]
https://cirrus-ci.com/task/5471865133596672?logs=ci#L3981

```
 test  2023-07-22T19:16:17.696000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
                                       self.run_test()
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/p2p_getaddr_caching.py", line 74, in run_test
                                       addr_receiver_onion1 = self.nodes[0].add_p2p_connection(AddrReceiver(), dstport=self.onion_port1)
                                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_node.py", line 652, in add_p2p_connection
                                       assert_equal(len(info), 1)
                                     File "/tmp/cirrus-ci-build/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 57, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(2 == 1)
 test  2023-07-22T19:16:17.697000Z TestFramework (DEBUG): Closing down network thread 
 test  2023-07-22T19:16:17.747000Z TestFramework (INFO): Stopping nodes 
 test  2023-07-22T19:16:17.748000Z TestFramework.node0 (DEBUG): Stopping node 
```

### Is there an existing issue for this?

- [X] I have searched the existing issues

**Comment by mzumsande** [comment]
See #28144 for a fix.

**Comment by vasild** [comment]
It is good to put asserts that can never the triggered because sometimes they are.
