### ISSUE TITLE
Intermittent failure in feature_config_args.py

### ISSUE THREAD

**Issue by mzumsande** [bitcoin/bitcoin#28290]
https://cirrus-ci.com/task/5383892962639872?logs=ci#L7698

```
2023-08-17T20:59:43.754000Z TestFramework (INFO): Test seed peers
2023-08-17T21:03:45.922000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
    self.run_test()
  File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_config_args.py", line 377, in run_test
    self.test_seed_peers()
  File "/ci_container_base/ci/scratch/build/bitcoin-i686-pc-linux-gnu/test/functional/feature_config_args.py", line 273, in test_seed_peers
    assert time.time() - start < 60
AssertionError
```

**Comment by mzumsande** [comment]
> I think the general idea is that we can't measure wall clock time and assume some operation is _faster_ than a specified wall clock duration (60 seconds in this case).

I agree. We can't do without timeouts, but have a way to scale the timeouts for extremely slow condition (`timeout_factor`), so we should try to reduce instances that circumvent this.
They also seem  unrelated to what is being tested, so I opened #28386 to remove them.
