### ISSUE TITLE
Intermittent failure in `wallet_backup.py --legacy-wallet`

### ISSUE THREAD

**Issue by theStack** [bitcoin/bitcoin#28323]
https://cirrus-ci.com/task/6546470984220672

```
 test  2023-08-22T10:17:14.044000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/test_framework.py", line 131, in main
                                       self.run_test()
                                     File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/wallet_backup.py", line 237, in run_test
                                       assert_equal(self.nodes[2].getbalance(), 0)
                                     File "/ci_container_base/ci/scratch/build/bitcoin-x86_64-pc-linux-gnu/test/functional/test_framework/util.py", line 57, in assert_equal
                                       raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
                                   AssertionError: not(50.00000000 == 0)
 test  2023-08-22T10:17:14.045000Z TestFramework (DEBUG): Closing down network thread 
```

**Comment by fanquake** [comment]
dupe of #25652?

**Comment by theStack** [comment]
> dupe of #25652?

Indeed, closing.
(FWIW, I searched via "is:issue is:open wallet_backup" and had no results, apparently the search is extra pedantic and needs full words)
