### ISSUE TITLE
ci: wallet_listtransactions.py --legacy-wallet failure

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#28411]
https://github.com/bitcoin/bitcoin/actions/runs/6082441277/job/16500239670"

```bash
Remaining jobs: [wallet_listtransactions.py --legacy-wallet]
274/274 - wallet_listtransactions.py --legacy-wallet failed, Duration: 2686 s

stdout:
2023-09-05T11:07:42.589000Z TestFramework (INFO): PRNG seed is: 4023633279228776754

2023-09-05T11:07:42.589000Z TestFramework (INFO): Initializing test directory D:\a\_temp\test_runner_₿_🏃_20230905_092624\wallet_listtransactions_222

2023-09-05T11:52:26.642000Z TestFramework (ERROR): Assertion failed

Traceback (most recent call last):

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 552, in start_nodes

    node.wait_for_rpc_connection()

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 296, in wait_for_rpc_connection

    self._raise_assertion_error("Unable to connect to bitcoind after {}s".format(self.rpc_timeout))

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 177, in _raise_assertion_error

    raise AssertionError(self._node_msg(msg))

AssertionError: [node 1] Unable to connect to bitcoind after 2400s



During handling of the above exception, another exception occurred:



Traceback (most recent call last):

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 130, in main

    self.setup()

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 295, in setup

    self.setup_network()

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 389, in setup_network

    self.setup_nodes()

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 411, in setup_nodes

    self.start_nodes()

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 555, in start_nodes

    self.stop_nodes()

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 570, in stop_nodes

    node.stop_node(wait=wait, wait_until_stopped=False)

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 357, in stop_node

    self.stop(wait=wait)

    ^^^^^^^^^

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 194, in __getattr__

    assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")

                                  ^^^^^^^^^^^^^^^^^^^^

AssertionError: [node 1] Error: no RPC connection

2023-09-05T11:52:26.703000Z TestFramework (INFO): Stopping nodes

[node 2] Cleaning up leftover process

[node 1] Cleaning up leftover process

[node 0] Cleaning up leftover process



stderr:
Traceback (most recent call last):

  File "D:\a\bitcoin\bitcoin/test/functional/wallet_listtransactions.py", line 304, in <module>

    ListTransactionsTest().main()

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 154, in main

    exit_code = self.shutdown()

                ^^^^^^^^^^^^^^^

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 311, in shutdown

    self.stop_nodes()

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 570, in stop_nodes

    node.stop_node(wait=wait, wait_until_stopped=False)

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 357, in stop_node

    self.stop(wait=wait)

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\coverage.py", line 50, in __call__

    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)

                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\authproxy.py", line 127, in __call__

    response, status = self._request('POST', self.__url.path, postdata.encode('utf-8'))

                       ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^

  File "D:\a\bitcoin\bitcoin\test\functional\test_framework\authproxy.py", line 105, in _request

    self.__conn.request(method, path, postdata, headers)

  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\http\client.py", line 1286, in request

    self._send_request(method, url, body, headers, encode_chunked)

  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\http\client.py", line 1332, in _send_request

    self.endheaders(body, encode_chunked=encode_chunked)

  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\http\client.py", line 1281, in endheaders

    self._send_output(message_body, encode_chunked=encode_chunked)

  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\http\client.py", line 1041, in _send_output

    self.send(msg)

  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\http\client.py", line 979, in send

    self.connect()

  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\http\client.py", line 945, in connect

    self.sock = self._create_connection(

                ^^^^^^^^^^^^^^^^^^^^^^^^

  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\socket.py", line 851, in create_connection

    raise exceptions[0]

  File "C:\hostedtoolcache\windows\Python\3.11.4\x64\Lib\socket.py", line 836, in create_connection

    sock.connect(sa)

ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it



Combine the logs and print the last 99999999 lines ...
```

```bash
  test  2023-09-05T11:52:26.642000Z TestFramework.node0 (DEBUG): Stopping node 
 test  2023-09-05T11:52:26.642000Z TestFramework.node1 (DEBUG): Stopping node 
 test  2023-09-05T11:52:26.642000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 552, in start_nodes
                                       node.wait_for_rpc_connection()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 296, in wait_for_rpc_connection
                                       self._raise_assertion_error("Unable to connect to bitcoind after {}s".format(self.rpc_timeout))
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 177, in _raise_assertion_error
                                       raise AssertionError(self._node_msg(msg))
                                   AssertionError: [node 1] Unable to connect to bitcoind after 2400s
                                   During handling of the above exception, another exception occurred:
                                   Traceback (most recent call last):
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 130, in main
                                       self.setup()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 295, in setup
                                       self.setup_network()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 389, in setup_network
                                       self.setup_nodes()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 411, in setup_nodes
                                       self.start_nodes()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 555, in start_nodes
                                       self.stop_nodes()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 570, in stop_nodes
                                       node.stop_node(wait=wait, wait_until_stopped=False)
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 357, in stop_node
                                       self.stop(wait=wait)
                                       ^^^^^^^^^
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 194, in __getattr__
                                       assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")
                                                                     ^^^^^^^^^^^^^^^^^^^^
                                   AssertionError: [node 1] Error: no RPC connection
 test  2023-09-05T11:52:26.642000Z TestFramework (DEBUG): Closing down network thread 
 node0 2023-09-05T11:52:26.644582Z [D:\a\bitcoin\bitcoin\src\httpserver.cpp:255] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:54455 
```

**Comment by fanquake** [comment]
> Looks like the known GHA Windows issue, no?

Is there an issue open for that, can close this is favour.
Is the issue that the Native Windows GitHub Actions are just randomly broken?

**Comment by hebasto** [comment]
We have been faced this issue in GHA since begging. https://github.com/bitcoin/bitcoin/pull/28384 has improved situation but not resolved.

**Comment by hebasto** [comment]
Suggesting to rename this issue using:
```
ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by hebasto** [comment]
> > Suggesting to rename this issue using:
> > ```
> > ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
> > ```
> 
> I can't find this in the logs, only `AssertionError: [node 1] Unable to connect to bitcoind after 2400s`.

https://pipelines.actions.githubusercontent.com/serviceHosts/5bbf6e8c-f281-4d7e-8054-12202ac3842a/_apis/pipelines/1/runs/618/signedlogcontent/4?urlExpires=2023-09-06T19%3A00%3A48.6754143Z&urlSigningMethod=HMACV1&urlSignature=SSbuIksLOg%2F5mdiTDZwxpY98LYsCl7HGBBWMSIFXOOI%3D:

```
2023-09-05T11:52:29.3711049Z ConnectionRefusedError: [WinError 10061] No connection could be made because the target machine actively refused it
```

**Comment by hebasto** [comment]
> Not sure what you are linking to...

It was a raw log of the job mentioned in the top comment.

This one should work: https://github.com/bitcoin/bitcoin/actions/runs/6082441277/job/16500239670#step:28:228

**Comment by hebasto** [comment]
I've re-read logs from this issue and other similar ones. The combined logs miss entries for nodes that are supposed to run.

Could `subprocess.Popen` just stuck on Windows?

For example: https://github.com/python/cpython/issues/88693.
