### ISSUE TITLE
ci: failure in feature_index_prune.py (MSVC)

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#29326]
https://github.com/bitcoin/bitcoin/actions/runs/7667501768/job/20897463395

```bash
 ============
Combined log for D:\a\_temp/test_runner_₿_🏃_20240126_113602/feature_index_prune_293:
============

 test  2024-01-26T11:36:28.165000Z TestFramework (INFO): PRNG seed is: 8852427722333217080 
 test  2024-01-26T11:36:28.165000Z TestFramework (DEBUG): Setting up network thread 
 test  2024-01-26T11:36:28.212000Z TestFramework (INFO): Initializing test directory D:\a\_temp\test_runner_₿_🏃_20240126_113602\feature_index_prune_293 
 test  2024-01-26T11:36:28.212000Z TestFramework (DEBUG): Copy cache directory D:\a\bitcoin\bitcoin\test\cache\node0 to node 0 
 test  2024-01-26T11:36:28.227000Z TestFramework (DEBUG): Copy cache directory D:\a\bitcoin\bitcoin\test\cache\node0 to node 1 
 test  2024-01-26T11:36:28.274000Z TestFramework (DEBUG): Copy cache directory D:\a\bitcoin\bitcoin\test\cache\node0 to node 2 
 test  2024-01-26T11:36:28.290000Z TestFramework (DEBUG): Copy cache directory D:\a\bitcoin\bitcoin\test\cache\node0 to node 3 
 test  2024-01-26T11:36:28.337000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up 
 test  2024-01-26T11:36:28.337000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up 
 test  2024-01-26T11:36:28.337000Z TestFramework.node2 (DEBUG): bitcoind started, waiting for RPC to come up 
 test  2024-01-26T11:36:28.337000Z TestFramework.node3 (DEBUG): bitcoind started, waiting for RPC to come up 
 test  2024-01-26T12:18:05.036000Z TestFramework.node0 (DEBUG): Stopping node 
 test  2024-01-26T12:18:05.036000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 556, in start_nodes
                                       node.wait_for_rpc_connection()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 308, in wait_for_rpc_connection
                                       self._raise_assertion_error("Unable to connect to bitcoind after {}s".format(self.rpc_timeout))
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 182, in _raise_assertion_error
                                       raise AssertionError(self._node_msg(msg))
                                   AssertionError: [node 0] Unable to connect to bitcoind after 2400s
                                   During handling of the above exception, another exception occurred:
                                   Traceback (most recent call last):
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 130, in main
                                       self.setup()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 297, in setup
                                       self.setup_network()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 391, in setup_network
                                       self.setup_nodes()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 413, in setup_nodes
                                       self.start_nodes()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 559, in start_nodes
                                       self.stop_nodes()
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_framework.py", line 574, in stop_nodes
                                       node.stop_node(wait=wait, wait_until_stopped=False)
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 369, in stop_node
                                       self.stop(wait=wait)
                                       ^^^^^^^^^
                                     File "D:\a\bitcoin\bitcoin\test\functional\test_framework\test_node.py", line 199, in __getattr__
                                       assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")
                                   AssertionError: [node 0] Error: no RPC connection
 test  2024-01-26T12:18:05.036000Z TestFramework (DEBUG): Closing down network thread 
 test  2024-01-26T12:18:05.090000Z TestFramework (INFO): Stopping nodes 
 test  2024-01-26T12:18:05.090000Z TestFramework.node0 (DEBUG): Stopping node 
````

**Comment by fanquake** [comment]
Yea I think so. Was trying to remember which of the Windows issues documented this failure. Will move to there.
