### ISSUE TITLE
ci: failure in `rpc_scanblocks.py`

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#29831]
https://github.com/bitcoin/bitcoin/actions/runs/8600455763/job/23565458580?pr=29707#step:7:3826:
```bash
  node0 2024-04-08T13:15:12.710688Z [httpworker.3] [rpc/request.cpp:187] [parse] [rpc] ThreadRPCServer method=getindexinfo user=__cookie__ 
 test  2024-04-08T13:15:12.711000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-apple-darwin/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-apple-darwin/test/functional/rpc_scanblocks.py", line 49, in run_test
                                       assert blockhash in out['relevant_blocks']
                                   AssertionError
 node0 2024-04-08T13:15:12.711330Z [http] [httpserver.cpp:306] [http_request_cb] [http] Received a POST request for / from 127.0.0.1:51647 
```

**Comment by furszy** [comment]
Quick check, the index seems to not have processed the block by the time `scanblocks()` (line 48) is called. The `getindexinfo()['synced']` value is set to true after the index initial sync. It does not tell us anything about tip scanning.
So, we can change line 46 check to verify the latest block height instead of the `synced` value. And that should fix the issue:
```diff
diff --git a/test/functional/rpc_scanblocks.py b/test/functional/rpc_scanblocks.py
--- a/test/functional/rpc_scanblocks.py	(revision 496f38dab4ba4506e4b628cb08ce4e582d638d07)
+++ b/test/functional/rpc_scanblocks.py	(date 1712655455099)
@@ -43,7 +43,7 @@
         # mine a block and assure that the mined blockhash is in the filterresult
         blockhash = self.generate(node, 1)[0]
         height = node.getblockheader(blockhash)['height']
-        self.wait_until(lambda: all(i["synced"] for i in node.getindexinfo().values()))
+        self.wait_until(lambda: all(i["best_block_height"] == height for i in node.getindexinfo().values()))
 
         out = node.scanblocks("start", [f"addr({addr_1})"])
         assert blockhash in out['relevant_blocks']
```

**Comment by furszy** [comment]
> @furszy Are you sure? The event at block height = 201 does not exist anymore, so I don't think it will be processed at all.

Hmm ok, what I said could be another issue.. nvm. The index will probably stop syncing if this happens.. throwing a "WARNING: Block %s does not connect to an ancestor of..". Will do some tests.

**Comment by emc99** [comment]
Who performs ci?

**Comment by furszy** [comment]
> Will do some tests.

Update: working on a fix. Will push it next week.

**Comment by fanquake** [comment]
https://cirrus-ci.com/task/4562186641604608?logs=ci#L4268
