### ISSUE TITLE
test: intermittent issue in interface_rest.py - AssertionError: self.wait_until(lambda: self.nodes[0].getindexinfo() == expected_filter)

### ISSUE THREAD

**Issue by brunoerg** [bitcoin/bitcoin#29863]
Logs: https://github.com/bitcoin/bitcoin/actions/runs/8659881706/job/23746656188?pr=29833#step:7:44796

```sh
 test  2024-04-12T10:25:31.001000Z TestFramework.utils (ERROR): wait_until() failed. Predicate: '''' 
                                           self.wait_until(lambda: self.nodes[0].getindexinfo() == expected_filter)
                                   '''
 test  2024-04-12T10:25:31.002000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-apple-darwin/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-apple-darwin/test/functional/interface_rest.py", line 295, in run_test
                                       self.wait_until(lambda: self.nodes[0].getindexinfo() == expected_filter)
                                     File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-apple-darwin/test/functional/test_framework/test_framework.py", line 780, in wait_until
                                       return wait_until_helper_internal(test_function, timeout=timeout, timeout_factor=self.options.timeout_factor)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build/bitcoin-x86_64-apple-darwin/test/functional/test_framework/util.py", line 293, in wait_until_helper_internal
                                       raise AssertionError("Predicate {} not true after {} seconds".format(predicate_source, timeout))
                                   AssertionError: Predicate ''''
                                           self.wait_until(lambda: self.nodes[0].getindexinfo() == expected_filter)
                                   ''' not true after 2400.0 seconds
```

**Comment by furszy** [comment]
Same issue as #29831, logs:
```
node0 2024-04-12T09:45:29.827143Z [scheduler] [validationinterface.cpp:212] [operator()] [validation] BlockConnected: block hash=54586dbb0de750d4bcd83326f04f6619d8e00dd5815981030ace95125f1eef87 block height=208 
...
node0 2024-04-12T09:45:29.827159Z [scheduler] [index/base.cpp:293] [BlockConnected] BlockConnected: WARNING: Block 54586dbb0de750d4bcd83326f04f6619d8e00dd5815981030ace95125f1eef87 does not connect to an ancestor of known best chain (tip=39455d83324a3dbbb15712ab63dd2f96b45a30f271617aa16c12483a561f721c); not updating index 
```

Fix is #29867.
