### ISSUE TITLE
test: SegFault in `ismine_tests` on SunOS / illumos

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#29908]
```
$ gdb -q --args ./src/test/test_bitcoin -t ismine_tests
Reading symbols from ./src/test/test_bitcoin...
(gdb) run
Starting program: /export/home/hebasto/git/bitcoin/build/src/test/test_bitcoin -t ismine_tests
[Thread debugging using libthread_db enabled]
warning: could not convert 'mutex_t' from the host encoding (ISO-8859-1) to UTF-32.
This normally should not happen, please file a bug report.
Running 1 test case...
[New Thread 1 (LWP 1)]

Thread 2 received signal SIGSEGV, Segmentation fault.
[Switching to Thread 1 (LWP 1)]
0x00007fffaf3eac59 in mutex_trylock_adaptive () from /lib/64/libc.so.1
(gdb) backtrace
#0  0x00007fffaf3eac59 in mutex_trylock_adaptive () from /lib/64/libc.so.1
#1  0x00007fffaf3ebe75 in mutex_lock_internal () from /lib/64/libc.so.1
#2  0x00007fffaf3ec415 in mutex_lock_impl () from /lib/64/libc.so.1
#3  0x00007fffaf3ec573 in pthread_mutex_lock () from /lib/64/libc.so.1
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f22e0 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
#4  0x00000000012f232b in boost::signals2::mutex::lock (warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x13085f0 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
this=<optimized out>) at /usr/include/boost/signals2/detail/lwm_pthreads.hpp:60
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
#5  boost::signals2::detail::unique_lock<boost::signals2::mutex>::unique_lock (warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
m=..., this=0x7fffbffecfc8) at /usr/include/boost/signals2/detail/unique_lock.hpp:29
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
#6  boost::signals2::detail::garbage_collecting_lock<boost::signals2::mutex>::garbage_collecting_lock (warning: (Internal error: pc 0x12f232a in read in CU, but not in symtab.)
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
this=0x7fffbffecf10, warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
m=...)
    at /usr/include/boost/signals2/connection.hpp:44
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
#7  0x0000000001308631 in boost::signals2::detail::signal_impl<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() (warning: (Internal error: pc 0x1308630 in read in CU, but not in symtab.)
this=0x1e1b060)
    at /usr/include/boost/signals2/detail/signal_template.hpp:230
#8  0x00000000016069c8 in boost::signals2::signal<void (), boost::signals2::optional_last_value<void>, int, std::less<int>, boost::function<void ()>, boost::function<void (boost::signals2::connection const&)>, boost::signals2::mutex>::operator()() (this=0x1e6eaf8) at /usr/include/boost/signals2/detail/signal_template.hpp:722
#9  wallet::DescriptorScriptPubKeyMan::TopUpWithDB (this=this@entry=0x1e6ead0, batch=..., size=size@entry=0)
    at /export/home/hebasto/git/bitcoin/src/wallet/scriptpubkeyman.cpp:2248
#10 0x0000000001606bcf in wallet::DescriptorScriptPubKeyMan::TopUp (this=0x1e6ead0, size=0) at /export/home/hebasto/git/bitcoin/src/wallet/scriptpubkeyman.cpp:2182
#11 0x000000000165c3c0 in wallet::CWallet::AddWalletDescriptor (this=this@entry=0x7fffbfff5540, desc=..., signing_provider=..., label="", 
    internal=internal@entry=false) at /export/home/hebasto/git/bitcoin/src/wallet/wallet.cpp:3884
#12 0x0000000001092c62 in wallet::ismine_tests::CreateDescriptor (keystore=..., desc_str="pkh(5JsGTWCrg7h7fA2fizVwyEVpXJxNuL9GGrYAmp2nTNS758WKDtU)", 
    success=success@entry=true) at /export/home/hebasto/git/bitcoin/src/wallet/test/ismine_tests.cpp:38
#13 0x000000000109585e in wallet::ismine_tests::ismine_standard::test_method (this=this@entry=0x7fffbfffe870)
    at /export/home/hebasto/git/bitcoin/src/wallet/test/ismine_tests.cpp:174
#14 0x00000000010a4ade in wallet::ismine_tests::ismine_standard_invoker () at /export/home/hebasto/git/bitcoin/src/wallet/test/ismine_tests.cpp:41
#15 0x00000000009487e0 in boost::function0<void>::operator() (this=<optimized out>) at /usr/include/boost/function/function_template.hpp:763
#16 boost::detail::forward::operator() (this=<optimized out>) at /usr/include/boost/test/impl/execution_monitor.ipp:1388
#17 boost::detail::function::function_obj_invoker0<boost::detail::forward, int>::invoke (function_obj_ptr=...)
    at /usr/include/boost/function/function_template.hpp:137
#18 0x00000000009199e1 in boost::function0<int>::operator() (this=0x7fffbffff390) at /usr/include/boost/function/function_template.hpp:763
#19 boost::detail::do_invoke<boost::shared_ptr<boost::detail::translator_holder_base>, boost::function<int ()> >(boost::shared_ptr<boost::detail::translator_holder_base> const&, boost::function<int ()> const&) (tr=..., F=...) at /usr/include/boost/test/impl/execution_monitor.ipp:301
#20 boost::execution_monitor::catch_signals(boost::function<int ()> const&) (
    this=this@entry=0x1d6e4a0 <boost::unit_test::unit_test_monitor_t::instance()::the_inst>, F=...) at /usr/include/boost/test/impl/execution_monitor.ipp:903
#21 0x0000000000919abb in boost::execution_monitor::execute(boost::function<int ()> const&) (
    this=this@entry=0x1d6e4a0 <boost::unit_test::unit_test_monitor_t::instance()::the_inst>, F=...) at /usr/include/boost/test/impl/execution_monitor.ipp:1301
#22 0x0000000000919b24 in boost::execution_monitor::vexecute(boost::function<void ()> const&) (
    this=this@entry=0x1d6e4a0 <boost::unit_test::unit_test_monitor_t::instance()::the_inst>, F=...) at /usr/include/boost/test/impl/execution_monitor.ipp:1397
#23 0x00000000009231ff in boost::unit_test::unit_test_monitor_t::execute_and_translate(boost::function<void ()> const&, unsigned long) (
    this=0x1d6e4a0 <boost::unit_test::unit_test_monitor_t::instance()::the_inst>, func=..., timeout_microseconds=timeout_microseconds@entry=0)
    at /usr/include/boost/test/impl/unit_test_monitor.ipp:49
```

---

System and compiler details:

```
$ uname -a
SunOS openindiana 5.11 illumos-faadcf7eb2 i86pc i386 i86pc
$ g++ --version
g++ (OpenIndiana 13.2.0-oi-3) 13.2.0
Copyright (C) 2023 Free Software Foundation, Inc.
This is free software; see the source for copying conditions.  There is NO
warranty; not even for MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
```

**Comment by fanquake** [comment]
Are you planning on providing the requested information here, so this can be investigated further?

**Comment by hebasto** [comment]
> Are you planning on providing the requested information here, so this can be investigated further?

Sure. Thanks for reminding :)

**Comment by hebasto** [comment]
I've tested the recent master branch @ 457e1846d2bf6ef9d54b9ba1a330ba8bbff13091 on the updated system:
```
$ uname -a
SunOS openindiana 5.11 illumos-82079dec87 i86pc i386 i86pc
```

The issue is no longer reproducible.

Closing.
