### ISSUE TITLE
Test Framework - test_framework.test_node.FailedToStartError: No RPC credentials

### ISSUE THREAD

**Issue by somethingbeta** [bitcoin/bitcoin#30818]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

On execution bitcoind fails to start and logs Failed to start error. Have pasted logs into the logs section. 

It looks as though there is some rpc config required for this to run, but have not found a way to specify whats required. When i hard code a username/password in utils.py .. fails with Connection Refused. 

**Example Command**
`
python functional/feature_rbf.py --loglevel=DEBUG --tracerpc
`

**Config.ini**
[environment]
PACKAGE_NAME=Bitcoin Core
PACKAGE_BUGREPORT=https://github.com/bitcoin/bitcoin/issues
SRCDIR=/usr/src/bitcoin
BUILDDIR=/usr/src/bitcoin
EXEEXT=.exe
RPCAUTH=/usr/src/bitcoin/share/rpcauth/rpcauth.py

[components]
ENABLE_WALLET=true
USE_SQLITE=true
USE_BDB=true
ENABLE_CLI=true
ENABLE_BITCOIN_UTIL=true
ENABLE_WALLET_TOOL=true
ENABLE_BITCOIND=true
ENABLE_FUZZ_BINARY=true
ENABLE_ZMQ=true
#ENABLE_EXTERNAL_SIGNER=true
#ENABLE_USDT_TRACEPOINTS=true
`

**Bitcoin.conf (autogenerated)**
`

regtest=1
[regtest]
port=12201
rpcport=17201
rpcservertimeout=99000
rpcdoccheck=1
fallbackfee=0.0002
server=1
keypool=1
discover=0
dnsseed=0
fixedseeds=0
listenonion=0
peertimeout=999999999
printtoconsole=0
upnp=0
natpmp=0
shrinkdebugfile=0
deprecatedrpc=create_bdb
unsafesqlitesync=1
connect=0
bind=127.0.0.1
`

### Expected behaviour

The test should run to completion. 

### Steps to reproduce

Build 27.* on Ubuntu WLS

Execute python test with example command. 
python functional/feature_rbf.py --loglevel=DEBUG --tracerpc

### Relevant log output

`
2024-09-04T18:07:10.779000Z TestFramework (INFO): PRNG seed is: 4851958720779390906
2024-09-04T18:07:10.779000Z TestFramework (DEBUG): Setting up network thread
2024-09-04T18:07:10.780000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_u9zpt_2g
2024-09-04T18:07:10.780000Z TestFramework (DEBUG): Copy cache directory /usr/src/bitcoin/test/cache/node0 to node 0
2024-09-04T18:07:10.781000Z TestFramework (DEBUG): Copy cache directory /usr/src/bitcoin/test/cache/node0 to node 1
2024-09-04T18:07:10.783000Z TestFramework.node0 (DEBUG): ['/usr/src/bitcoin/src/bitcoind.exe', '-datadir=/tmp/bitcoin_func_test_u9zpt_2g/node0', '-logtimemicros', '-debug', '-debugexclude=libevent', '-debugexclude=leveldb', '-debugexclude=rand', '-uacomment=testnode0', '-logthreadnames', '-logsourcelocations', '-loglevel=trace', '-v2transport=0']
2024-09-04T18:07:10.783000Z TestFramework.node0 (DEBUG): ['-maxorphantx=1000', '-limitancestorcount=50', '-limitancestorsize=101', '-limitdescendantcount=200', '-limitdescendantsize=101']
2024-09-04T18:07:10.783000Z TestFramework.node0 (DEBUG): bitcoind started, waiting for RPC to come up
2024-09-04T18:07:10.784000Z TestFramework.node1 (DEBUG): ['/usr/src/bitcoin/src/bitcoind.exe', '-datadir=/tmp/bitcoin_func_test_u9zpt_2g/node1', '-logtimemicros', '-debug', '-debugexclude=libevent', '-debugexclude=leveldb', '-debugexclude=rand', '-uacomment=testnode1', '-logthreadnames', '-logsourcelocations', '-loglevel=trace', '-v2transport=0']
2024-09-04T18:07:10.784000Z TestFramework.node1 (DEBUG): []
2024-09-04T18:07:10.784000Z TestFramework.node1 (DEBUG): bitcoind started, waiting for RPC to come up
2024-09-04T18:07:10.784000Z TestFramework.utils (DEBUG): /tmp/bitcoin_func_test_u9zpt_2g/node0/bitcoin.conf
2024-09-04T18:07:10.784000Z TestFramework.node0 (DEBUG): Value Error No RPC credentials
....
2024-09-04T18:07:14.552000Z TestFramework.utils (DEBUG): /tmp/bitcoin_func_test_u9zpt_2g/node0/bitcoin.conf
2024-09-04T18:07:14.552000Z TestFramework.node0 (DEBUG): Value Error No RPC credentials
2024-09-04T18:07:14.803000Z TestFramework.node0 (DEBUG): Stopping node
2024-09-04T18:07:14.804000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 556, in start_nodes
    node.wait_for_rpc_connection()
  File "/usr/src/bitcoin/test/functional/test_framework/test_node.py", line 260, in wait_for_rpc_connection
    raise FailedToStartError(self._node_msg(
**test_framework.test_node.FailedToStartError: [node 0] bitcoind exited with status 1 during initialization. Error: Specified data directory "/tmp/bitcoin_func_test_u9zpt_2g/node0" does not exist.**
************************
During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 130, in main     self.setup()
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 297, in setup     self.setup_network()
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 391, in setup_network     self.setup_nodes()
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 413, in setup_nodes     self.start_nodes()
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 559, in start_nodes     self.stop_nodes()
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 574, in stop_nodes     node.stop_node(wait=wait, wait_until_stopped=False)
  File "/usr/src/bitcoin/test/functional/test_framework/test_node.py", line 386, in stop_node     self.stop(wait=wait)
  **File "/usr/src/bitcoin/test/functional/test_framework/test_node.py", line 207, in __getattr__    assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection") AssertionError: [node 0] Error: no RPC connection**

2024-09-04T18:07:14.806000Z TestFramework (DEBUG): Closing down network thread
2024-09-04T18:07:14.857000Z TestFramework (INFO): Stopping nodes
2024-09-04T18:07:14.857000Z TestFramework.node0 (DEBUG): Stopping node
Traceback (most recent call last):
  File "/usr/src/bitcoin/test/functional/feature_rbf.py", line 731, in <module>
    ReplaceByFeeTest().main()
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 154, in main
    exit_code = self.shutdown()
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 313, in shutdown
    self.stop_nodes()
  File "/usr/src/bitcoin/test/functional/test_framework/test_framework.py", line 574, in stop_nodes
    node.stop_node(wait=wait, wait_until_stopped=False)
  File "/usr/src/bitcoin/test/functional/test_framework/test_node.py", line 386, in stop_node
    self.stop(wait=wait)
  File "/usr/src/bitcoin/test/functional/test_framework/test_node.py", line 207, in __getattr__
    assert self.rpc_connected and self.rpc is not None, self._node_msg("Error: no RPC connection")

AssertionError: [node 0] Error: no RPC connection

[node 1] Cleaning up leftover process
[node 0] Cleaning up leftover process
`

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v27.1.0

### Operating system and version

Ubuntu 22.04.4 LTS

### Machine specifications

Windows 11 Home
8 Core i7 9700
32 GB Ram

**Comment by somethingbeta** [comment]
> > Error: Specified data directory "/tmp/bitcoin_func_test_u9zpt_2g/node0" does not exist.
> 
> This seems to be the first error, so it would be good to debug this first. Can you check whether `/usr/src/bitcoin/test/cache/node0` exists and whether the following is successful:
> 
> > 2024-09-04T18:07:10.780000Z TestFramework (DEBUG): Copy cache directory /usr/src/bitcoin/test/cache/node0 to node 0
> 
> Given that you claim that `bitcoin.conf` exists (presumably in this dir), the error message that the directory does not exist seems odd.
> 
> Generally, it may be a bit difficult to get the Windows functional tests run on Linux, which is probably also the reason why the corresponding CI task only runs the Windows unit tests on Linux: https://github.com/bitcoin/bitcoin/runs/29691284283

yes the directory exists, for some reason only get the does not exist. The contents of the bitcoin.conf are from the one in the respective dir.  

Inlcuded the log output for the copy, that succeeds for both nodes :
`
2024-09-05T09:17:31.312000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_t2z9w4gc
2024-09-05T09:17:31.312000Z TestFramework (DEBUG): Copy cache directory /usr/src/bitcoin/test/cache/node0 to node 0
2024-09-05T09:17:31.315000Z TestFramework (DEBUG): -- Result of Copytree /tmp/bitcoin_func_test_t2z9w4gc/node0
2024-09-05T09:17:31.315000Z TestFramework (DEBUG): ['stderr', 'bitcoin.conf', 'stdout']
2024-09-05T09:17:31.315000Z TestFramework (DEBUG): Copy cache directory /usr/src/bitcoin/test/cache/node0 to node 1
2024-09-05T09:17:31.320000Z TestFramework (DEBUG): -- Result of Copytree /tmp/bitcoin_func_test_t2z9w4gc/node1
2024-09-05T09:17:31.320000Z TestFramework (DEBUG): ['stderr', 'bitcoin.conf', 'stdout']
`

**Comment by somethingbeta** [comment]
> Running the Windows tests on Wine in Linux is obviously better than nothing, but it would be better to run them directly on Windows. However, I am not sure what the easiest way to do this would be. For now, editing the config ini to adjust the paths is required.

When you say edit the config.ini paths, what would i be editing here please?

**Comment by somethingbeta** [comment]
> For WSL, can you share exact steps to reproduce, please? I guess they are https://github.com/bitcoin/bitcoin/blob/28.x/doc/build-windows.md ?
> 
> > > Running the Windows tests on Wine in Linux is obviously better than nothing, but it would be better to run them directly on Windows. However, I am not sure what the easiest way to do this would be. For now, editing the config ini to adjust the paths is required.
> > 
> > 
> > When you say edit the config.ini paths, what would i be editing here please?
> 
> You can try to manually edit the paths in the config ini file to point to the "source dir" and "build dir". The source dir is the folder that contains the src cpp files (e.g. `'src', 'rpc', 'client.cpp'`). The build dir is the folder that cointains the exe files (e.g. `bitcoind.exe`). They may be identical, depending on your build. Inside WSL this is not needed. However, outside WSL (in Windows) this should be required.

Used the 27.x branch ..followed the steps based on 
https://github.com/bitcoin/bitcoin/blob/27.x/doc/build-windows.md except the "make deploy"

then i just navigate to the path, and invoke the test

all this is on WSL including the invocation of the test. I don't leave that env.

**Comment by somethingbeta** [comment]
> Ok, thanks for confirming.
> 
> I don't have WSL, so I can't test this. However running the functional tests inside WSL was never supported, IIRC.
> 
> Even if you work around your initial issue, the test framework and individual tests have to modified for the Wine environment.
> 
> So my recommendation would be to run the tests on Windows directly. However that isn't possible out-of-the-box either and requires modifying the config ini file.

Ok good to know re support for running the tests in WSL.  

Let me have a play getting these to run on windows directly.

**Comment by maflcko** [comment]
> I presume adding support for tests directly on Windows is easier (or adding documentation on how to do it).

This is done in the CI now. See:

https://github.com/bitcoin/bitcoin/blob/c862936d16a640690ef4c89456738fe4bb99be54/.github/workflows/ci.yml#L382-L443

The basic idea is that you re-write the `test/config.ini` file.
