### ISSUE TITLE
ci: failure in feature_assumeutxo.py

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#30878]
Seems like this is intermittently failing, since #30807 was merged? i.e https://cirrus-ci.com/task/4893652609138688?logs=ci#L3674. Seeing the same failure in PRs with unrelated changes, i.e https://cirrus-ci.com/task/5740917921939456.

**Comment by fanquake** [comment]
Also seen here https://github.com/bitcoin/bitcoin/actions/runs/10828541638/job/30044139197#step:7:2918:
```bash
 2024-09-12T13:21:45.762000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/Users/runner/work/bitcoin/bitcoin/test/functional/test_framework/test_framework.py", line 132, in main
    self.run_test()
  File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build-x86_64-apple-darwin/test/functional/feature_assumeutxo.py", line 738, in run_test
    self.test_sync_from_assumeutxo_node(snapshot=dump_output)
  File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build-x86_64-apple-darwin/test/functional/feature_assumeutxo.py", line 317, in test_sync_from_assumeutxo_node
    assert 'NETWORK' in snapshot_node.getnetworkinfo()['localservicesnames']
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError
```
