### ISSUE TITLE
ci: macOS 14 CI failure `Invalid value detected for '-wallet' or '-nowallet'`

### ISSUE THREAD

**Issue by tdb3** [bitcoin/bitcoin#31019]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

Encountered the following failure in PR #30793 (https://github.com/bitcoin/bitcoin/pull/30793#issuecomment-2387502458) for `CI / macOS 14 native, arm64, no depends, sqlite only, gui (pull_request)`.  The failure wasn't seen on the other CI jobs.

### Expected behaviour

No failure

### Steps to reproduce

CI run with #39793 commit e6853592361341c27103ed74b25470ac1e098d6d

### Relevant log output

```
node0 2024-10-02T00:15:45.783638Z [init] [src/noui.cpp:57] [noui_InitMessage] init message: Verifying wallet(s)… 
Error:  node0 2024-10-02T00:15:45.783653Z [init] [src/noui.cpp:31] [noui_ThreadSafeMessageBox] [error] Invalid value detected for '-wallet' or '-nowallet'. '-wallet' requires a string value, while '-nowallet' accepts only '1' to disable all wallets 
 node0 2024-10-02T00:15:45.783737Z [init] [src/httpserver.cpp:510] [InterruptHTTPServer] [http] Interrupting HTTP server 
 node0 2024-10-02T00:15:45.783748Z [init] [src/httprpc.cpp:379] [InterruptHTTPRPC] [rpc] Interrupting HTTP RPC server 
 node0 2024-10-02T00:15:45.783756Z [init] [src/rpc/server.cpp:291] [operator()] [rpc] Interrupting RPC 
 node0 2024-10-02T00:15:45.783770Z [init] [src/init.cpp:277] [Shutdown] Shutdown: In progress... 
 node0 2024-10-02T00:15:45.783782Z [shutoff] [src/httprpc.cpp:384] [StopHTTPRPC] [rpc] Stopping HTTP RPC server 
 node0 2024-10-02T00:15:45.783794Z [shutoff] [src/httpserver.cpp:772] [UnregisterHTTPHandler] [http] Unregistering HTTP handler for / (exactmatch 1) 
 node0 2024-10-02T00:15:45.783804Z [shutoff] [src/httpserver.cpp:772] [UnregisterHTTPHandler] [http] Unregistering HTTP handler for /wallet/ (exactmatch 0) 
 node0 2024-10-02T00:15:45.783810Z [shutoff] [src/rpc/server.cpp:303] [operator()] [rpc] Stopping RPC 
 node0 2024-10-02T00:15:45.783892Z [shutoff] [src/rpc/server.cpp:309] [operator()] [rpc] RPC stopped. 
 node0 2024-10-02T00:15:45.783904Z [shutoff] [src/httpserver.cpp:522] [StopHTTPServer] [http] Stopping HTTP server 
 node0 2024-10-02T00:15:45.783911Z [shutoff] [src/httpserver.cpp:524] [StopHTTPServer] [http] Waiting for HTTP worker threads to exit 
 node0 2024-10-02T00:15:45.784048Z [http] [src/httpserver.cpp:354] [ThreadHTTP] [http] Entering http event loop 
 node0 2024-10-02T00:15:45.784129Z [http] [src/httpserver.cpp:357] [ThreadHTTP] [http] Exited http event loop 
 test  2024-10-02T00:55:45.674000Z TestFramework (ERROR): Assertion failed 
                                   Traceback (most recent call last):
                                     File "/Users/runner/work/bitcoin/bitcoin/test/functional/test_framework/test_node.py", line 665, in assert_start_raises_init_error
                                       ret = self.process.wait(timeout=self.rpc_timeout)
                                             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 1264, in wait
                                       return self._wait(timeout=timeout)
                                              ^^^^^^^^^^^^^^^^^^^^^^^^^^^
                                     File "/opt/homebrew/Cellar/python@3.12/3.12.6/Frameworks/Python.framework/Versions/3.12/lib/python3.12/subprocess.py", line 2045, in _wait
                                       raise TimeoutExpired(self.args, timeout)
                                   subprocess.TimeoutExpired: Command '['/Users/runner/work/bitcoin/bitcoin/ci/scratch/build-aarch64-apple-darwin23.6.0/src/bitcoind', '-datadir=/Users/runner/work/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20241002_001101/feature_settings_11/node0', '-logtimemicros', '-debug', '-debugexclude=libevent', '-debugexclude=leveldb', '-debugexclude=rand', '-uacomment=testnode0', '-logthreadnames', '-logsourcelocations', '-loglevel=trace', '-v2transport=0', '-settings=/Users/runner/work/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20241002_001101/feature_settings_11/node0/regtest/settings.json']' timed out after 2400 seconds
                                   During handling of the above exception, another exception occurred:
                                   Traceback (most recent call last):
                                     File "/Users/runner/work/bitcoin/bitcoin/test/functional/test_framework/test_framework.py", line 132, in main
                                       self.run_test()
                                     File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build-aarch64-apple-darwin23.6.0/test/functional/feature_settings.py", line 110, in run_test
                                       self.test_wallet_settings(settings)
                                     File "/Users/runner/work/bitcoin/bitcoin/ci/scratch/build-aarch64-apple-darwin23.6.0/test/functional/feature_settings.py", line 39, in test_wallet_settings
                                       node.assert_start_raises_init_error(expected_msg="Error: Invalid value detected for '-wallet' or '-nowallet'. '-wallet' requires a string value, while '-nowallet' accepts only '1' to disable all wallets",
                                     File "/Users/runner/work/bitcoin/bitcoin/test/functional/test_framework/test_node.py", line 695, in assert_start_raises_init_error
                                       self._raise_assertion_error(assert_msg)
                                     File "/Users/runner/work/bitcoin/bitcoin/test/functional/test_framework/test_node.py", line 197, in _raise_assertion_error
                                       raise AssertionError(self._node_msg(msg))
                                   AssertionError: [node 0] bitcoind should have exited within 2400s with expected error Error: Invalid value detected for '-wallet' or '-nowallet'. '-wallet' requires a string value, while '-nowallet' accepts only '1' to disable all wallets
 test  2024-10-02T00:55:45.690000Z TestFramework (DEBUG): Closing down network thread 
 test  2024-10-02T00:55:45.894000Z TestFramework (INFO): Stopping nodes 
 test  2024-10-02T00:55:45.894000Z TestFramework (WARNING): Not cleaning up dir /Users/runner/work/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20241002_001101/feature_settings_11 
 test  2024-10-02T00:55:45.895000Z TestFramework (ERROR): Test failed. Test logging available at /Users/runner/work/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20241002_001101/feature_settings_11/test_framework.log 
 test  2024-10-02T00:55:45.895000Z TestFramework (ERROR): 
 test  2024-10-02T00:55:45.896000Z TestFramework (ERROR): Hint: Call /Users/runner/work/bitcoin/bitcoin/test/functional/combine_logs.py '/Users/runner/work/bitcoin/bitcoin/ci/scratch/test_runner/test_runner_₿_🏃_20241002_001101/feature_settings_11' to consolidate all logs 
 test  2024-10-02T00:55:45.897000Z TestFramework (ERROR): 
 test  2024-10-02T00:55:45.897000Z TestFramework (ERROR): If this failure happened unexpectedly or intermittently, please file a bug and provide a link or upload of the combined log. 
 test  2024-10-02T00:55:45.897000Z TestFramework (ERROR): https://github.com/bitcoin/bitcoin/issues 
 test  2024-10-02T00:55:45.897000Z TestFramework (ERROR): 
 ```

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v28.99.0-86e8b1bd8d33-dirty

### Operating system and version

macOS 14.6.1

### Machine specifications

arm64

**Comment by ismaelsadeeq** [comment]
@tdb3 it might be helpful to share link to the full C.I logs?

**Comment by tdb3** [comment]
> @tdb3 it might be helpful to share link to the full C.I logs?

Thanks.  Link now included in the description.

**Comment by mzumsande** [comment]
I think the problem is that the node got stuck during shutdown for some reason:

```
 node0 2024-10-02T00:15:45.784129Z [http] [src/httpserver.cpp:357] [ThreadHTTP] [http] Exited http event loop 
 test  2024-10-02T00:55:45.674000Z TestFramework (ERROR): Assertion failed 
```
The second line is ~40 minutes after the first, the node hasn't completed shutdown during that time.
The node is expected to fail with `Invalid value detected for '-wallet' or '-nowallet'` (that's what the test is testing), so that's not the problem.

**Comment by tdb3** [comment]
> The node is expected to fail with `Invalid value detected for '-wallet' or '-nowallet'` (that's what the test is testing), so that's not the problem.

Right, the title was poorly worded. Updated

**Comment by willcl-ark** [comment]
I don't think there's much else we can do here with current information.

Does this seem worth keeping open to anyone else, seeing as we haven't seen re-occurrence in CI (AFAIK)?
