### ISSUE TITLE
intermittent issue in wallet_upgradewallet.py: AssertionError: bdb magic does not match bdb btree magic

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#31210]
https://cirrus-ci.com/task/5232872305459200:
```bash
067]  node0 2024-11-04T11:58:48.064759Z [httpworker.0] [src/wallet/wallet.h:936] [WalletLogPrintf] [default wallet] m_address_book.size() = 2 
[06:58:49.067]  test  2024-11-04T11:58:48.065000Z TestFramework (INFO): Can upgrade to HD 
[06:58:49.067]  test  2024-11-04T11:58:48.066000Z TestFramework (ERROR): Assertion failed 
[06:58:49.067]                                    Traceback (most recent call last):
[06:58:49.067]                                      File "/ci_container_base/test/functional/test_framework/test_framework.py", line 132, in main
[06:58:49.067]                                        self.run_test()
[06:58:49.067]                                      File "/ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/test/functional/wallet_upgradewallet.py", line 226, in run_test
[06:58:49.067]                                        orig_kvs = dump_bdb_kv(node_master_wallet)
[06:58:49.067]                                      File "/ci_container_base/test/functional/test_framework/bdb.py", line 142, in dump_bdb_kv
[06:58:49.067]                                        dump_meta_page(pages[INNER_META_PAGE])
[06:58:49.067]                                      File "/ci_container_base/test/functional/test_framework/bdb.py", line 100, in dump_meta_page
[06:58:49.067]                                        assert magic == BTREE_MAGIC, 'bdb magic does not match bdb btree magic'
[06:58:49.067]                                    AssertionError: bdb magic does not match bdb btree magic
[06:58:49.067]  test  2024-11-04T11:58:48.067000Z TestFramework (DEBUG): Closing down network thread 
```

Looking at all the logs in #30798, this seems to be a different issue.

**Comment by achow101** [comment]
I don't think this issue has to do with ZFS. I'm debugging the test on the problematic system and it seems that BDB decided to use a page size of 16384 for some reason, rather than our expected and hardcoded 4096. Changing it to 16384 resolves this, but we should instead be using the pagesize given by the wallet file rather than a fixed pagesize. This is a test only issue as the C++ parser does not use a fixed pagesize.
