### ISSUE TITLE
Intermittent issue in feature_index_prune.py: assert_equal(pruneheight_new, 248) AssertionError: not(249 == 248)

### ISSUE THREAD

**Issue by maflcko** [bitcoin/bitcoin#31446]
https://cirrus-ci.com/task/5093097040773120?logs=ci#L2925

```
[05:55:03.695]  test  2024-12-03T05:55:02.834000Z TestFramework (ERROR): Assertion failed 
[05:55:03.695]                                    Traceback (most recent call last):
[05:55:03.695]                                      File "/ci_container_base/test/functional/test_framework/test_framework.py", line 135, in main
[05:55:03.695]                                        self.run_test()
[05:55:03.695]                                      File "/ci_container_base/ci/scratch/build-x86_64-pc-linux-gnu/test/functional/feature_index_prune.py", line 77, in run_test
[05:55:03.695]                                        assert_equal(pruneheight_new, 248)
[05:55:03.695]                                      File "/ci_container_base/test/functional/test_framework/util.py", line 77, in assert_equal
[05:55:03.695]                                        raise AssertionError("not(%s)" % " == ".join(str(arg) for arg in (thing1, thing2) + args))
[05:55:03.695]                                    AssertionError: not(249 == 248)

**Comment by mzumsande** [comment]
This is due to the possibility of blocks arriving out of order, even when syncing with just one peer:

As node 0 generates blocks, it sends out cmpctblock messages to its peers.
In response to this, node 1 will either reconstruct the blocks/write them to disk directly or (if it's slow in keeping up, and its tip is behind so that it sees the announcements as in the future) request them via GETDATA, adding a round trip.
Therefore, blocks can be saved to disk out of order for node 1, and if that happens with the last block of the block file, the prune height can be different for one of the blocks receiving blocks via p2p.

Not sure how to best fix this - I thought about just softening the assertions for the pruning height, but possibly the later subtest "prune exactly up to the indices best blocks while the indices are disabled" could fail due to that same effect?
