### ISSUE TITLE
test: different error message fails rpc_signer.py

### ISSUE THREAD

**Issue by 110CodingP** [bitcoin/bitcoin#31506]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

On my Ubuntu 24.04 system on running rpc_signer.py functional test (after compiling from source) fails the test which tests the case of missing script (on master and 28.x but passes on 27.x !) 
I tried running (with only regtest = 1 in bitcoin.conf)
```
bitcoind  -daemon  -signer=fake.py
bitcoin-cli enumeratesigners
```
to get the following:
```
execve failed: Not a directory (20)
```
which is different than what is asserted in the test.
I tried compiling 28.x and master on a Ubuntu 24.04 VM running on Qemu/KVM and the test passes there.

I followed all the steps for installing the dependencies mentioned in build-unix.md and checked the versions mentioned in dependencies.md . Also tried removing bitcoin and again compiling from source but the test still fails.

### Expected behaviour

The functional test should pass just like it does on the CI. 

### Steps to reproduce

I referred to build-unix.md for compile instructions and installing dependencies.
For master followed the following commands:
```
cmake -B build
cmake --build build
cmake --install build
build/test/functional/rpc_signer.py
```
which gives basically the following error:
```
Traceback (most recent call last):
  File "/home/codingp110/bitcoin/test/functional/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "/home/codingp110/bitcoin/build/test/functional/rpc_signer.py", line 56, in run_test
    assert_raises_rpc_error(
  File "/home/codingp110/bitcoin/test/functional/test_framework/util.py", line 151, in assert_raises_rpc_error
    assert try_rpc(code, message, fun, *args, **kwds), "No exception raised"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codingp110/bitcoin/test/functional/test_framework/util.py", line 166, in try_rpc
    raise AssertionError(
AssertionError: Expected substring not found in error message:
substring: 'execve failed: No such file or directory'
error message: 'execve failed: Not a directory (20)'.
```
For 28.x and 27.x (used git worktree to create separate directories and then git reset hard to overwrite with upstream/28.x and upstream/27.x):
```
./autogen.sh
./configure
make
test/functional/rpc_signer.py
```
28.x gives similar error as master but 27.x passes!

### Relevant log output

relevant log (master):
```
2024-12-16T02:42:47.859000Z TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/home/codingp110/bitcoin/test/functional/test_framework/util.py", line 160, in try_rpc
    fun(*args, **kwds)
  File "/home/codingp110/bitcoin/test/functional/test_framework/coverage.py", line 50, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codingp110/bitcoin/test/functional/test_framework/authproxy.py", line 146, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: execve failed: Not a directory (20) (-1)

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/home/codingp110/bitcoin/test/functional/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "/home/codingp110/bitcoin/build/test/functional/rpc_signer.py", line 56, in run_test
    assert_raises_rpc_error(
  File "/home/codingp110/bitcoin/test/functional/test_framework/util.py", line 151, in assert_raises_rpc_error
    assert try_rpc(code, message, fun, *args, **kwds), "No exception raised"
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/codingp110/bitcoin/test/functional/test_framework/util.py", line 166, in try_rpc
    raise AssertionError(
AssertionError: Expected substring not found in error message:
substring: 'execve failed: No such file or directory'
error message: 'execve failed: Not a directory (20)'.
```

running `bitcoind` with the `-signer=fake.py` and then getting strace output on running `enumeratesigners` rpc gave only the following major differences on master and 27.x
on master:
```
readv(6, [{iov_base="HTTP/1.1 200 OK\r\nContent-Type: application/json\r\nDate: Sat, 14 Dec 2024 09:31:05 GMT\r\nContent-Length: 93\r\nConnection: close\r\n\r\n{\"jsonrpc\":\"2.0\",\"error\":{\"code\":-1,\"message\":\"execve failed: Not a directory (20)\"},\"id\":1}\n", iov_len=220}], 1) = 220
```
on 27.x
```
readv(6, [{iov_base="HTTP/1.1 500 Internal Server Error\r\nContent-Type: application/json\r\nDate: Sat, 14 Dec 2024 09:32:19 GMT\r\nContent-Length: 96\r\nConnection: close\r\n\r\n{\"result\":null,\"error\":{\"code\":-1,\"message\":\"execve failed: No such file or directory\"},\"id\":1}\n", iov_len=242}], 1) = 242
```
but on doing the same for master and 28.x on a VM(Ubuntu 24.04.1 LTS on VirtualBox) gave the same strace output as my system but with the correct error message.

PS: The logs/outputs mentioned for master(except for the first one in this section) are old and not for master-b042c4f0538c

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v28.99.0-b042c4f0538c 

### Operating system and version

Ubuntu 24.04.1 LTS

### Machine specifications

OS: Ubuntu 24.04
Architecture:             x86_64
CPU(s):                   8
Vendor ID:                GenuineIntel
  Model name:             12th Gen Intel(R) Core(TM) i3-1215U

**Comment by 110CodingP** [comment]
I understand that this may be a problem with only my system and hence not relevant, happy to close the issue in that case!

**Comment by Sjors** [comment]
The error "execve failed: Not a directory (20)" is quite strange, since we're not expecting `-signer` to point to a directory.

Most of the action happens here: https://github.com/bitcoin/bitcoin/blame/master/src/common/run_command.cpp

And the biggest change between v27 and v28 is https://github.com/bitcoin/bitcoin/pull/28981

I assume you've tried deleting the `build` directory to see if you still get the test error?

Does `enumeratesigners` work with the real HWI?

**Comment by 110CodingP** [comment]
Thanks a lot maflcko  and Sjors for the suggestions!
git bisect gave `[70434b1c443d9251a880d0193af771f574c40617] external_signer: replace boost::process with cpp-subprocess compiling bad` (the same one Sjors mentioned) as the commit at which the test first fails.

 Tried deleting build and then rebuilding but still the test fails

Does real HWI mean https://github.com/bitcoin-core/HWI ? Sorry not very familiar with this, will try to see if it works.

replacing fake.py by ./fake.py fixes the test for both my system and the VM! Did not really understood how the above commit relates to this though.

**Comment by Sjors** [comment]
Yes, the real HWI is at https://github.com/bitcoin-core/HWI

No need to connect an actual hardware wallet to it.

> replacing fake.py by ./fake.py fixes the test for both my system and the VM!

That might be enough info to figure out what's going on.

cc @hebasto

**Comment by fanquake** [comment]
> cc @hebasto 

@hebasto or maybe @achow101 can you take a look here? Seems like the bisect is pointing to breakage when boost::process was swapped out.

**Comment by hebasto** [comment]
> > cc [@hebasto](https://github.com/hebasto)
> 
> [@hebasto](https://github.com/hebasto) or maybe [@achow101](https://github.com/achow101) can you take a look here? Seems like the bisect is pointing to breakage when boost::process was swapped out.

I'm working on `src/util/subprocess.h` code.

**Comment by hebasto** [comment]
I'm struggling to reproduce the 'execve failed: Not a directory (20)' error message on Ubuntu 24.04:

```
$ bitcoind -daemon -signet -signer=fake.py
Bitcoin Core starting
$ bitcoin-cli -signet enumeratesigners
error code: -1
error message:
execve failed: No such file or directory (2)
```

**Comment by SakshiKasat18** [comment]
I’m able to run rpc_signer.py on current upstream master (macOS) and it passes for me. The issue report shows the test can fail due to OS-dependent execve failed errno strings. I’ll open a small PR to accept the reported alternate message while keeping the check tight.

Tested: python3 build/test/functional/test_runner.py rpc_signer.py

**Comment by maflcko** [comment]
Is this still an issue with a recent version of Bitcoin Core? If yes, what are the steps to reproduce?

> but on doing the same for master and 28.x on a VM(Ubuntu 24.04.1 LTS on VirtualBox) gave the same strace output as my system but with the correct error message.

The fact that this stops reproducing as soon as you hop into a vm, and the fact that no one else reproduced this so far, makes me wonder if this is a local issue?

**Comment by 110CodingP** [comment]
This issue seems to be fixed as per [2706758](https://github.com/bitcoin/bitcoin/commit/2706758dc38c7a4e271d9df5ea3104b7135974f3). Feel free to close!

**Comment by maflcko** [comment]
> This issue seems to be fixed as per [2706758](https://github.com/bitcoin/bitcoin/commit/2706758dc38c7a4e271d9df5ea3104b7135974f3). Feel free to close!

Nice. Thx for reporting back. The commit you link to is meant to be a refactor, which shouldn't change any behavior, so I'd be surprised if this was the exact commit that fixed it.

In any case, good to hear it is finally fixed
