### ISSUE TITLE
qa: `feature_pruning.py` fails on OpenBSD 7.6

### ISSUE THREAD

**Issue by hebasto** [bitcoin/bitcoin#31532]
```
$ ./build/test/functional/feature_pruning.py                                                                                                                                    
2024-12-18T15:43:01.718000Z TestFramework (INFO): PRNG seed is: 9161356521613668802
2024-12-18T15:43:01.722000Z TestFramework (INFO): Initializing test directory /tmp/bitcoin_func_test_9kemfg2i
2024-12-18T15:43:03.429000Z TestFramework (INFO): Warning! This test requires 4GB of disk space
2024-12-18T15:43:03.430000Z TestFramework (INFO): Mining a big blockchain of 995 blocks
2024-12-18T15:44:06.404000Z TestFramework (INFO): Check that we haven't started pruning yet because we're below PruneAfterHeight
2024-12-18T15:44:06.404000Z TestFramework (INFO): Success
2024-12-18T15:44:06.405000Z TestFramework (INFO): Though we're already using more than 550MiB, current usage: 592.1861515045166
2024-12-18T15:44:06.405000Z TestFramework (INFO): Mining 25 more blocks should cause the first block file to be pruned
2024-12-18T15:44:08.797000Z TestFramework (INFO): Success
2024-12-18T15:44:08.798000Z TestFramework (INFO): Usage should be below target: 496.3139057159424
2024-12-18T15:44:08.799000Z TestFramework (INFO): Check that we'll exceed disk space target if we have a very high stale block rate
2024-12-18T15:44:08.799000Z TestFramework (INFO): Mine 24 (stale) blocks on Node 1, followed by 25 (main chain) block reorg from Node 0, for 12 rounds
2024-12-18T15:45:03.671000Z TestFramework (INFO): Usage can be over target because of high stale rate: 512.3139057159424
2024-12-18T15:45:03.673000Z TestFramework (INFO): Check that we can survive a 288 block reorg still
2024-12-18T15:45:03.674000Z TestFramework (INFO): Current block height: 1320
2024-12-18T15:45:03.674000Z TestFramework (INFO): Invalidating block 0c24dade6348580616b36943a607e63d022e2f0c1295016767e2a55155349df0 at height 1033
2024-12-18T15:45:07.251000Z TestFramework (INFO): New best height: 1032
2024-12-18T15:45:07.365000Z TestFramework (INFO): Generating new longer chain of 300 more blocks
2024-12-18T15:45:07.989000Z TestFramework (INFO): Reconnect nodes
2024-12-18T15:45:14.252000Z TestFramework (INFO): Verify height on node 2: 1332
2024-12-18T15:45:14.254000Z TestFramework (INFO): Usage possibly still high because of stale blocks in block files: 512.3139057159424
2024-12-18T15:45:14.254000Z TestFramework (INFO): Mine 220 more large blocks so we have requisite history
2024-12-18T15:45:23.828000Z TestFramework (ERROR): JSONRPC error
Traceback (most recent call last):
  File "/home/hebasto/dev/bitcoin/test/functional/test_framework/test_framework.py", line 135, in main
    self.run_test()
  File "/home/hebasto/dev/bitcoin/./build/test/functional/feature_pruning.py", line 415, in run_test
    self.reorg_test()  # (1033, )
    ^^^^^^^^^^^^^^^^^
  File "/home/hebasto/dev/bitcoin/./build/test/functional/feature_pruning.py", line 221, in reorg_test
    mine_large_blocks(self.nodes[0], 220)
  File "/home/hebasto/dev/bitcoin/./build/test/functional/feature_pruning.py", line 59, in mine_large_blocks
    node.submitblock(block.serialize().hex())
  File "/home/hebasto/dev/bitcoin/test/functional/test_framework/coverage.py", line 50, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
                 ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/hebasto/dev/bitcoin/test/functional/test_framework/authproxy.py", line 146, in __call__
    raise JSONRPCException(response['error'], status)
test_framework.authproxy.JSONRPCException: AcceptBlock: Failed to find position to write new block to disk (-25)
2024-12-18T15:45:23.885000Z TestFramework (INFO): Stopping nodes
```

**Comment by hebasto** [comment]
My apologies for the false alarm.

It was a free disk space issue.
