### ISSUE TITLE
failure in wallet_sendall.py --descriptors

### ISSUE THREAD

**Issue by SwimmingRieux** [bitcoin/bitcoin#31571]
### Is there an existing issue for this?

- [X] I have searched the existing issues

### Current behaviour

When I try to run functional tests using `build/test/functional/test_runner.py`, only 1 test gets failed:

![Screenshot from 2024-12-27 10-45-53](https://github.com/user-attachments/assets/dd54a5a5-e214-4a2d-9359-145f314eddfd)

error : 
`Temporary test directory at /tmp/test_runner_₿_🏃_20241227_142837
usage: create_cache.py [options]
create_cache.py: error: unrecognized arguments: --descriptors
Traceback (most recent call last):
  File "/path/to/bitcoin/build/test/functional/test_runner.py", line 954, in <module>
    main()
  File "/path/to/bitcoin/build/test/functional/test_runner.py", line 576, in main
    run_tests(
  File "/path/to/bitcoin/build/test/functional/test_runner.py", line 629, in run_tests
    subprocess.check_output([sys.executable, tests_dir + 'create_cache.py'] + flags + ["--tmpdir=%s/cache" % tmpdir])
  File "/usr/lib/python3.10/subprocess.py", line 421, in check_output
    return run(*popenargs, stdout=PIPE, timeout=timeout, check=True,
  File "/usr/lib/python3.10/subprocess.py", line 526, in run
    raise CalledProcessError(retcode, process.args,
subprocess.CalledProcessError: Command '['/usr/bin/python3', '/path/to/bitcoin/build/test/functional/create_cache.py', '--cachedir=/path/to/bitcoin/build/test/cache', '--descriptors', '--configfile=/path/to/bitcoin/build/test/functional/../config.ini', '--tmpdir=/tmp/test_runner_₿_🏃_20241227_142837/cache']' returned non-zero exit status 2.
`

But when i run that very test using `build/test/functional/test_runner.py wallet_sendall.py`, it gets passed:

![Screenshot from 2024-12-27 10-50-39](https://github.com/user-attachments/assets/37d1a1da-7708-4813-8adf-6f573e1a4495)

### Expected behaviour

I expect that 1 test to get passed when I run all the tests in parallel.

### Steps to reproduce

I just built using:

`
cmake -B build \
    -DBUILD_GUI=OFF \
    -DWITH_BDB=OFF  \
    -DBUILD_BENCH=OFF  \
    -DBUILD_FOR_FUZZING=OFF \
    -DBUILD_KERNEL_LIB=OFF \
    -DBUILD_SHARED_LIBS=OFF \
    -DBUILD_TESTS=OFF \
    -DBUILD_TX=OFF \
    -DBUILD_UTIL=OFF \
    -DBUILD_WALLET_TOOL=OFF

# Compile!
cmake --build build -j$(nproc)
`

And then ran the functional tests using `build/test/functional/test_runner.py`

### How did you obtain Bitcoin Core

Compiled from source

### What version of Bitcoin Core are you using?

v28.0

### Operating system and version

Ubuntu 22.04.5 LTS

**Comment by brunoerg** [comment]
I can't reproduce with the provided steps on Ubuntu 22.04 as well. Just tried it on MacOS 14.3 and worked.

```sh
...
wallet_resendwallettransactions.py --descriptors         | ✓ Passed  | 3 s
wallet_send.py --descriptors                             | ✓ Passed  | 16 s
wallet_sendall.py --descriptors                          | ✓ Passed  | 2 s
wallet_sendmany.py --descriptors                         | ✓ Passed  | 1 s
wallet_signer.py --descriptors                           | ✓ Passed  | 3 s
wallet_signmessagewithaddress.py                         | ✓ Passed  | 1 s
wallet_signrawtransactionwithwallet.py --descriptors     | ✓ Passed  | 2 s
wallet_simulaterawtx.py --descriptors                    | ✓ Passed  | 1 s
wallet_spend_unconfirmed.py                              | ✓ Passed  | 1 s
wallet_startup.py                                        | ✓ Passed  | 2 s
wallet_taproot.py --descriptors                          | ✓ Passed  | 14 s
wallet_timelock.py                                       | ✓ Passed  | 1 s
wallet_transactiontime_rescan.py --descriptors           | ✓ Passed  | 5 s
wallet_txn_clone.py                                      | ✓ Passed  | 1 s
wallet_txn_clone.py --mineblock                          | ✓ Passed  | 4 s
wallet_txn_clone.py --segwit                             | ✓ Passed  | 1 s
wallet_txn_doublespend.py --descriptors                  | ✓ Passed  | 1 s
wallet_txn_doublespend.py --mineblock                    | ✓ Passed  | 3 s
...
```
