### ISSUE TITLE
[RPC Tests] getblocktemplate_longpoll test is crashing

### ISSUE THREAD

**Issue by fanquake** [bitcoin/bitcoin#6651]
```
Stopping nodes
DEBUG:BitcoinRPC:-49-> stop []
Traceback (most recent call last):
  File "bitcoin/qa/rpc-tests/getblocktemplate_longpoll.py", line 90, in <module>
    GetBlockTemplateLPTest().main()
  File "bitcoin/qa/rpc-tests/test_framework/test_framework.py", line 134, in main
    stop_nodes(self.nodes)
  File "/bitcoin/qa/rpc-tests/test_framework/util.py", line 218, in stop_nodes
    node.stop()
  File "bitcoin/qa/rpc-tests/test_framework/authproxy.py", line 124, in __call__
    response = self._get_response()
  File "bitcoin/qa/rpc-tests/test_framework/authproxy.py", line 145, in _get_response
    http_response = self.__conn.getresponse()
  File "python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
```

**Comment by luke-jr** [comment]
Seems to work fine on master as of 9de541a9c95a47c3f5c9e443a0ad3040b9791a2f?

**Comment by laanwj** [comment]
Unable to reproduce this
```
$  ./getblocktemplate_longpoll.py 
Initializing test directory /tmp/testt4tnQ4
Warning: this test will take about 70 seconds in the best case. Be patient.
Stopping nodes
Cleaning up
Tests successful
```

**Comment by paveljanik** [comment]
Reproduced now on the current master + #7688 patchset, OS X. Not always, but reproducible:

```
$ date; ./getblocktemplate_longpoll.py ; date
Wed Mar 30 16:15:45 CEST 2016
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testZxSS7P
Warning: this test will take about 70 seconds in the best case. Be patient.
Stopping nodes
Cleaning up
Tests successful
Wed Mar 30 16:16:53 CEST 2016
$ date; ./getblocktemplate_longpoll.py ; date
Wed Mar 30 16:18:40 CEST 2016
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testEBdhZq
Warning: this test will take about 70 seconds in the best case. Be patient.
Stopping nodes
Traceback (most recent call last):
  File "./getblocktemplate_longpoll.py", line 90, in <module>
    GetBlockTemplateLPTest().main()
  File "/private/tmp/bitcoin-7688/qa/rpc-tests/test_framework/test_framework.py", line 151, in main
    stop_nodes(self.nodes)
  File "/private/tmp/bitcoin-7688/qa/rpc-tests/test_framework/util.py", line 302, in stop_nodes
    node.stop()
  File "/private/tmp/bitcoin-7688/qa/rpc-tests/test_framework/coverage.py", line 50, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/private/tmp/bitcoin-7688/qa/rpc-tests/test_framework/authproxy.py", line 137, in __call__
    response = self._request('POST', self.__url.path, postdata)
  File "/private/tmp/bitcoin-7688/qa/rpc-tests/test_framework/authproxy.py", line 119, in _request
    return self._get_response()
  File "/private/tmp/bitcoin-7688/qa/rpc-tests/test_framework/authproxy.py", line 152, in _get_response
    http_response = self.__conn.getresponse()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 1132, in getresponse
    response.begin()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 453, in begin
    version, status, reason = self._read_status()
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/httplib.py", line 409, in _read_status
    line = self.fp.readline(_MAXLINE + 1)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/socket.py", line 480, in readline
    data = self._sock.recv(self._rbufsize)
socket.error: [Errno 54] Connection reset by peer
Wed Mar 30 16:19:48 CEST 2016
$ 
```

**Comment by paveljanik** [comment]
Reproducible with 1:10 probability here:
```
-rw-r--r--  1 pavel  wheel   268 Mar 30 16:29 log.1
-rw-r--r--  1 pavel  wheel   268 Mar 30 16:39 log.10
-rw-r--r--  1 pavel  wheel   268 Mar 30 16:30 log.2
-rw-r--r--  1 pavel  wheel   268 Mar 30 16:31 log.3
-rw-r--r--  1 pavel  wheel   268 Mar 30 16:32 log.4
-rw-r--r--  1 pavel  wheel   268 Mar 30 16:33 log.5
-rw-r--r--  1 pavel  wheel   268 Mar 30 16:34 log.6
-rw-r--r--  1 pavel  wheel   268 Mar 30 16:36 log.7
-rw-r--r--  1 pavel  wheel   268 Mar 30 16:37 log.8
-rw-r--r--  1 pavel  wheel  1894 Mar 30 16:38 log.9
```

**Comment by fanquake** [comment]
Closing. No longer able to reproduce this.
