### ISSUE TITLE
IndexError when running make deploy in OS X

### ISSUE THREAD

**Issue by federicobond** [bitcoin/bitcoin#6802]
````
/Applications/Xcode.app/Contents/Developer/usr/bin/make -C src qt/bitcoin-qt
make[1]: Circular univalue/lib/libunivalue.la <- univalue/lib/libunivalue.la dependency dropped.
./contrib/macdeploy/macdeployqtplus Bitcoin-Qt.app -add-qt-tr da,de,es,hu,ru,uk,zh_CN,zh_TW -translations-dir= -dmg -fancy ./contrib/macdeploy/fancy.plist -verbose 2
+ Removing old dist folder +
+ Copying source bundle +
+ Deploying frameworks +
Processing libboost_system.dylib ...
Processing libboost_filesystem.dylib ...
Processing libboost_program_options-mt.dylib ...
Processing libboost_thread-mt.dylib ...
Processing libboost_chrono-mt.dylib ...
Processing QtNetwork.framework ...
Linked: dist/Bitcoin-Qt.app/Contents/Frameworks/QtNetwork.framework/Versions/Current -> 5
Traceback (most recent call last):
  File "./contrib/macdeploy/macdeployqtplus", line 617, in <module>
    deploymentInfo = deployFrameworksForAppBundle(applicationBundle, config.strip, verbose)
  File "./contrib/macdeploy/macdeployqtplus", line 372, in deployFrameworksForAppBundle
    return deployFrameworks(frameworks, applicationBundle.path, applicationBundle.binaryPath, strip, verbose)
  File "./contrib/macdeploy/macdeployqtplus", line 355, in deployFrameworks
    dependencies = getFrameworks(deployedBinaryPath, verbose)
  File "./contrib/macdeploy/macdeployqtplus", line 222, in getFrameworks
    info = FrameworkInfo.fromOtoolLibraryLine(line.strip())
  File "./contrib/macdeploy/macdeployqtplus", line 138, in fromOtoolLibraryLine
    info.binaryName = parts[i+3]
IndexError: list index out of range
make: *** [Bitcoin-Core.dmg] Error 1
````

The value of `line` there is:
````python
'/usr/local/Cellar/qt5/5.5.0_1/lib/QtCore.framework/QtCore (compatibility version 5.5.0, current version 5.5.0)'
````

But it seems to expect something with the shape of this:
````python
'/usr/local/opt/qt5/lib/QtNetwork.framework/Versions/5/QtNetwork (compatibility version 5.5.0, current version 5.5.0)'
````
Note the `Versions/5/{binaryName}` format after `.framework` in the second line.

I'd be happy to contribute a patch if I can understand how it should handle these cases.

**Comment by paveljanik** [comment]
Can't reproduce here.
@jonasschnelli Can you reproduce?
@federicobond How do you have Qt installed?

**Comment by jonasschnelli** [comment]
Keep in mind that the "official" OSX binaries are cross compiles which results in osx based `make deploy` is relatively untested.
Will test soon.

**Comment by federicobond** [comment]
I have Qt 5 installed via Homebrew.

**Comment by federicobond** [comment]
I just tried a clean installation and couldn't reproduce this error anymore.
