### ISSUE TITLE
bitcoin-util-test.py fails with python3.2

### ISSUE THREAD

**Issue by MarcoFalke** [bitcoin/bitcoin#7893]
Steps to reproduce:

```sh
$ cd src/
$ srcdir=. PYTHONPATH=`pwd`/test python3.2 `pwd`/test/bitcoin-util-test.py

Traceback (most recent call last):
  File "/home/marco/bitcoin/src/test/bitcoin-util-test.py", line 12, in <module>
    "bitcoin-util-test.json",buildenv)
  File "/home/marco/bitcoin/src/test/bctest.py", line 51, in bctester
    bctest(testDir, testObj, buildenv.exeext)
  File "/home/marco/bitcoin/src/test/bctest.py", line 29, in bctest
    outs = proc.communicate(input=inputData)
  File "/usr/lib/python3.2/subprocess.py", line 819, in communicate
    return self._communicate(input)
  File "/usr/lib/python3.2/subprocess.py", line 1425, in _communicate
    stdout, stderr = self._communicate_with_poll(input)
  File "/usr/lib/python3.2/subprocess.py", line 1492, in _communicate_with_poll
    input_offset += os.write(fd, chunk)
TypeError: 'str' does not support the buffer interface
```

This works with python3.4 and python2.7 as described in https://github.com/bitcoin/bitcoin/pull/7878#issue-148438568. This also *should* work with python 3.2, but maybe I am missing something obvious...

**Comment by laanwj** [comment]
Yes, Python 3 went through some trouble in their initial releases. We should set a minimum version of Python 3 that we support.
What versions of distributions ship with Python 3.2?
Ubuntu stable (14.04) uses 3.4.3 at least.

**Comment by MarcoFalke** [comment]
>What versions of distributions ship with Python 3.2?
Ubuntu LTS (14.04) uses 3.4.3 at least.


Ubuntu 12.04 which we still use in travis

http://packages.ubuntu.com/precise/python/python3

**Comment by laanwj** [comment]
Closing this, travis has switched to Trusty so Python 3.2 is none of our concern.
