### ISSUE TITLE
rpc-tests.py: Too many "Error: Unable to start HTTP server. See debug log for details."

### ISSUE THREAD

**Issue by paveljanik** [bitcoin/bitcoin#9317]
After long time, I'm trying to pass all the tests. Using current master:

```
for par in 1 2 4
do
   for round in 1 2 3 4 5 6 7 8 9 10
   do
      echo Par: $par, round: $round
      rm -rf qa/cache/; qa/pull-tester/rpc-tests.py -parallel=$par > round-$par-$round.log 2>&1
   done
done
```

And I'm not able to pass the testsuite completely.

On OS X, the testsuite fails randomly with:

```
Error: Unable to start HTTP server. See debug log for details.
```

The `debug.log` of one node then contains something like:

```
2016-12-10 21:21:34 Binding RPC on address ::1 port 17082 failed.
2016-12-10 21:21:34 Binding RPC on address 127.0.0.1 port 17082 failed.
```

I have read in other issues (https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-238127542), that the default to run 4 tests in parallel can cause some issues, so I have tried to isolate this issue by removing the parallelisation. But it did not helped completely, but the frequency of such failures is definitely small with less parallelism...

I will post detailed results and analyse of the above script tomorrow.

Similar issue was reported by @fanquake at https://github.com/bitcoin/bitcoin/issues/8425#issuecomment-236474724

One of my favourite failure is:

```
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testye4vq40s/424
Mining blocks...
Assertion failed: 0E-8 != 53.99954800
Stopping nodes
Not cleaning up dir /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testye4vq40s/424
Failed

stderr:
Error: Unable to start HTTP server. See debug log for details.
  File "/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/test_framework.py", line 145, in main
    self.run_test()
  File "/tmp/bitcoin-master/qa/rpc-tests/wallet.py", line 212, in run_test
    assert_equal(self.nodes[2].getbalance(), node_2_bal) #should not be changed because tx was not broadcasted
  File "/private/tmp/bitcoin-master/qa/rpc-tests/test_framework/util.py", line 529, in assert_equal
    raise AssertionError("%s != %s"%(str(thing1),str(thing2)))
```

**Comment by sdaftuar** [comment]
Usually when I see the unable to start http server message its because there's another bitcoind process running (maybe a process didn't die on a prior test run?).

**Comment by paveljanik** [comment]
After few runs, I see a lot of abandoned bitcoinds:
```
54330 ttys015    0:42.74 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testbeb8teom/634/node2 -server -keypool=1 -discover=0 -rest -mocktime=0 -usehd=1
54600 ttys015    0:42.21 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testzoocmv6s/197/node1 -server -keypool=1 -discover=0 -rest -mocktime=0 -rescan
54657 ttys015    0:41.42 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testh5dwxvud/184/node1 -server -keypool=1 -discover=0 -rest -mocktime=0
55363 ttys015    0:39.90 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testsiic47qw/228/node2 -server -keypool=1 -discover=0 -rest -mocktime=0 -reindex
55396 ttys015    0:39.44 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testc5lyvy8h/222/node0 -server -keypool=1 -discover=0 -rest -mocktime=0
55582 ttys015    0:40.21 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testjdsw6pvu/287/node1 -server -keypool=1 -discover=0 -rest -mocktime=0 -debug -logtimemicros -txindex
55881 ttys015    0:39.30 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/test5hnkksae/506/node1 -server -keypool=1 -discover=0 -rest -mocktime=0 -logtimemicros -debug -blockversion=4 -promiscuousmempoolflags=517 -prematurewitness -walletprematurewitness -rpcserialversion=2
56131 ttys015    0:38.86 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/test9dttnslb/159/node0 -server -keypool=1 -discover=0 -rest -mocktime=0 -debug -logtimemicros=1 -bip9params=segwit:0:0
56241 ttys015    0:37.26 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testijsd3oq7/141/node0 -server -keypool=1 -discover=0 -rest -mocktime=0
56332 ttys015    0:36.63 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testel2coylo/120/node1 -server -keypool=1 -discover=0 -rest -mocktime=0
56366 ttys015    0:37.15 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/test6alaldly/590/node3 -server -keypool=1 -discover=0 -rest -mocktime=0
56444 ttys015    0:36.08 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testzm4zo5qk/585/node2 -server -keypool=1 -discover=0 -rest -mocktime=0 -reindex
56569 ttys015    0:35.85 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/test7e5jbrka/557/node0 -server -keypool=1 -discover=0 -rest -mocktime=0
56572 ttys015    0:33.64 /tmp/bitcoin-master/src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testcunrdkfi/556/node0 -server -keypool=1 -discover=0 -rest -mocktime=0 -disablewallet
56608 ttys015    0:35.52 /tmp/bitcoin-master/src/bitcoind -server -keypool=1 -datadir=/tmp/bitcoin-master/qa/cache/node0 -discover=0
```

Hmm.

**Comment by MarcoFalke** [comment]
@paveljanik Is this still an issue?

"Did you try turning it off and on again?"

**Comment by paveljanik** [comment]
I will make another round of tests today and will report here.

**Comment by paveljanik** [comment]
Just one run before the breakfast, and this one is still running afterwards:

```
bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testsv7jupo0/110/node1 -server -keypool=1 -discover=0 -rest -mocktime=1388655000
```

**Comment by paveljanik** [comment]
These tests failed:

```
wallet-hd.py                   | False  | 39 s
receivedby.py                  | False  | 33 s
bumpfee.py                     | False  | 39 s
```

**Comment by paveljanik** [comment]
Second run:
```
listtransactions.py            | False  | 33 s
wallet.py                      | False  | 75 s
sendheaders.py                 | False  | 33 s
merkle_blocks.py               | False  | 39 s
...
src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/tests0skjf1z/290/node3 -server -keypool=1 -discover=0 -rest -mocktime=0 -debug -txindex
src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testpdmuqpec/294/node1 -server -keypool=1 -discover=0 -rest -mocktime=0 -debug -logtimemicros=1
src/bitcoind -datadir=/var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testrm71tbc1/295/node1 -server -keypool=1 -discover=0 -rest -mocktime=1388655000
```

**Comment by paveljanik** [comment]
Failures were:
```
listtransactions.py:
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testrm71tbc1/295
Assertion failed: 
Stopping nodes

wallet.py:
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testin48jpvu/299
Mining blocks...
check -rescan
Assertion failed: 
Stopping nodes

sendheaders.py:
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testpdmuqpec/294
Assertion failed: 
Stopping nodes

merkle_blocks.py:
Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/tests0skjf1z/290
Unexpected exception caught during testing: timeout('timed out',)
Stopping nodes
```

**Comment by paveljanik** [comment]
BTW - this is all on OS X. It works OK on openSUSE...

**Comment by jnewbery** [comment]
Hmmm, not very helpful output! You could try running with my logging branch https://github.com/bitcoin/bitcoin/pull/9768 to see if you get any useful output in test_framework.log

**Comment by paveljanik** [comment]
The log is more verbose :-)

```
walletbackup.py:
2017-03-08 07:38:50.290000 TestFramework (INFO): Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testjj4d1666/253
2017-03-08 07:39:39.155000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/util.py", line 360, in start_nodes
    rpcs.append(start_node(i, dirname, extra_args[i], rpchost, timewait=timewait, binary=binary[i]))
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/util.py", line 323, in start_node
    wait_for_bitcoind_start(bitcoind_processes[i], url, i)
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/util.py", line 219, in wait_for_bitcoind_start
    blocks = rpc.getblockcount()
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/authproxy.py", line 151, in __call__
    response = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/authproxy.py", line 124, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1083, in request
    self._send_request(method, url, body, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1128, in _send_request
    self.endheaders(body)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1079, in endheaders
    self._send_output(message_body)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 911, in _send_output
    self.send(msg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 854, in send
    self.connect()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 826, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 711, in create_connection
    raise err
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 702, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/test_framework.py", line 146, in main
    self.setup_network()
  File "/tmp/bitcoin-9768/qa/rpc-tests/walletbackup.py", line 49, in setup_network
    self.nodes = start_nodes(self.num_nodes, self.options.tmpdir, self.extra_args)
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/util.py", line 362, in start_nodes
    stop_nodes(rpcs)
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/util.py", line 382, in stop_nodes
    assert not bitcoind_processes.values() # All connections must be gone now
AssertionError
2017-03-08 07:39:39.202000 TestFramework (INFO): Stopping nodes

stderr:
Traceback (most recent call last):
  File "/tmp/bitcoin-9768/qa/rpc-tests/walletbackup.py", line 198, in <module>
    WalletBackupTest().main()
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/test_framework.py", line 162, in main
    stop_nodes(self.nodes)
  File "/private/tmp/bitcoin-9768/qa/rpc-tests/test_framework/util.py", line 380, in stop_nodes
    for i, node in enumerate(nodes):
TypeError: 'NoneType' object is not iterable

Pass: False, Duration: 49 s
```

**Comment by jnewbery** [comment]
@paveljanik can you try running again with this branch: https://github.com/jnewbery/bitcoin/tree/check_port_conflict

I've modified test_runner.py to check that the all ports in the range that the test could use are free prior to launching the test. It's not completely watertight - another process could bind to the port between test_runner checking it and the test itself trying to bind, but it should reduce instances of port collisions to almost zero.

**Comment by paveljanik** [comment]
Tried. Three different failures:

```
wallet.py failed, Duration: 104 s

stdout:
2017-05-10 17:43:44.811000 TestFramework (INFO): Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/tests5a2cuzc/652
2017-05-10 17:43:47.237000 TestFramework (INFO): Mining blocks...
2017-05-10 17:43:47.824000 TestFramework (INFO): test gettxout
2017-05-10 17:44:23.102000 TestFramework (INFO): check -rescan
2017-05-10 17:44:31.116000 TestFramework (INFO): check -reindex
2017-05-10 17:44:39.280000 TestFramework (INFO): check -zapwallettxes=1
2017-05-10 17:44:47.446000 TestFramework (INFO): check -zapwallettxes=2
2017-05-10 17:45:29.047000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 281, in start_nodes
    rpcs.append(start_node(i, dirname, extra_args[i], rpchost, timewait=timewait, binary=binary[i]))
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 242, in start_node
    wait_for_bitcoind_start(bitcoind_processes[i], url, i)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 219, in wait_for_bitcoind_start
    blocks = rpc.getblockcount()
  File "/private/tmp/bitcoin-master/test/functional/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/authproxy.py", line 152, in __call__
    response = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/private/tmp/bitcoin-master/test/functional/test_framework/authproxy.py", line 125, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/bitcoin-master/test/functional/test_framework/test_framework.py", line 148, in main
    self.run_test()
  File "/tmp/bitcoin-master/test/functional/wallet.py", line 349, in run_test
    self.nodes = start_nodes(3, self.options.tmpdir, [[m, "-limitancestorcount="+str(chainlimit)]] * 3)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 283, in start_nodes
    stop_nodes(rpcs)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 303, in stop_nodes
    assert not bitcoind_processes.values() # All connections must be gone now
AssertionError
2017-05-10 17:45:29.049000 TestFramework (INFO): Stopping nodes


stderr:
Traceback (most recent call last):
  File "/private/tmp/bitcoin-master/test/functional/test_framework/authproxy.py", line 126, in _request
    return self._get_response()
  File "/private/tmp/bitcoin-master/test/functional/test_framework/authproxy.py", line 169, in _get_response
    http_response = self.__conn.getresponse()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1198, in getresponse
    response.begin()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 297, in begin
    version, status, reason = self._read_status()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 258, in _read_status
    line = str(self.fp.readline(_MAXLINE + 1), "iso-8859-1")
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 576, in readinto
    return self._sock.recv_into(b)
ConnectionResetError: [Errno 54] Connection reset by peer

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/tmp/bitcoin-master/test/functional/wallet.py", line 414, in <module>
    WalletTest().main()
  File "/private/tmp/bitcoin-master/test/functional/test_framework/test_framework.py", line 163, in main
    self.stop_nodes()
  File "/private/tmp/bitcoin-master/test/functional/test_framework/test_framework.py", line 209, in stop_nodes
    stop_nodes(self.nodes)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 302, in stop_nodes
    stop_node(node, i)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 293, in stop_node
    node.stop()
  File "/private/tmp/bitcoin-master/test/functional/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/authproxy.py", line 152, in __call__
    response = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/private/tmp/bitcoin-master/test/functional/test_framework/authproxy.py", line 138, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
ConnectionRefusedError: [Errno 61] Connection refused


.
...
import-rescan.py failed, Duration: 43 s

stdout:
2017-05-10 17:47:17.353000 TestFramework (INFO): Initializing test directory /var/folders/65/fn0h49r55k7779vg1b_h461r0000gn/T/testu5hiwcwh/609
2017-05-10 17:48:00.419000 TestFramework (ERROR): Assertion failed
Traceback (most recent call last):
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 281, in start_nodes
    rpcs.append(start_node(i, dirname, extra_args[i], rpchost, timewait=timewait, binary=binary[i]))
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 242, in start_node
    wait_for_bitcoind_start(bitcoind_processes[i], url, i)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 219, in wait_for_bitcoind_start
    blocks = rpc.getblockcount()
  File "/private/tmp/bitcoin-master/test/functional/test_framework/coverage.py", line 46, in __call__
    return_val = self.auth_service_proxy_instance.__call__(*args, **kwargs)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/authproxy.py", line 152, in __call__
    response = self._request('POST', self.__url.path, postdata.encode('utf-8'))
  File "/private/tmp/bitcoin-master/test/functional/test_framework/authproxy.py", line 125, in _request
    self.__conn.request(method, path, postdata, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1107, in request
    self._send_request(method, url, body, headers)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1152, in _send_request
    self.endheaders(body)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 1103, in endheaders
    self._send_output(message_body)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 934, in _send_output
    self.send(msg)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 877, in send
    self.connect()
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/http/client.py", line 849, in connect
    (self.host,self.port), self.timeout, self.source_address)
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 712, in create_connection
    raise err
  File "/opt/local/Library/Frameworks/Python.framework/Versions/3.5/lib/python3.5/socket.py", line 703, in create_connection
    sock.connect(sa)
socket.timeout: timed out

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/private/tmp/bitcoin-master/test/functional/test_framework/test_framework.py", line 147, in main
    self.setup_network()
  File "/tmp/bitcoin-master/test/functional/import-rescan.py", line 124, in setup_network
    self.nodes = start_nodes(self.num_nodes, self.options.tmpdir, extra_args)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 283, in start_nodes
    stop_nodes(rpcs)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 303, in stop_nodes
    assert not bitcoind_processes.values() # All connections must be gone now
AssertionError
2017-05-10 17:48:00.422000 TestFramework (INFO): Stopping nodes


stderr:
Traceback (most recent call last):
  File "/tmp/bitcoin-master/test/functional/import-rescan.py", line 192, in <module>
    ImportRescanTest().main()
  File "/private/tmp/bitcoin-master/test/functional/test_framework/test_framework.py", line 163, in main
    self.stop_nodes()
  File "/private/tmp/bitcoin-master/test/functional/test_framework/test_framework.py", line 209, in stop_nodes
    stop_nodes(self.nodes)
  File "/private/tmp/bitcoin-master/test/functional/test_framework/util.py", line 301, in stop_nodes
    for i, node in enumerate(nodes):
TypeError: 'NoneType' object is not iterable


```

**Comment by jnewbery** [comment]
Are you sure this is the same problem as first described in this issue (`Error: Unable to start HTTP server. See debug log for details.`) Does that error message appear in bitcoind's log?

These failures are because the socket is timing out when the test framework is sending a `getblockcount` RPC to the bitcoind node at startup (test framework does this to check that the node is fully started and ready for the test). Is there anything in the bitcoind log when this happens?

**Comment by paveljanik** [comment]
I wrote: "Tried. Three different failures:". So I'm sure these are not the same issue 8)

**Comment by paveljanik** [comment]
But I can't reproduce the original issue now.

So closing.

I'll do a few more complete test runs to see, what can I see now.
