### ISSUE TITLE
Node crashed with assertion failure in network code

### ISSUE THREAD

**Issue by laanwj** [bitcoin/bitcoin#9348]
```
bitcoind: net.h:775: int CNode::GetSendVersion() const: Assertion `nSendVersion != 0' failed.
```
It was running last week master (9851a84) with #9289 #9288 #9283 #8589 on top.

Traceback:
```
#5  0x7f57b35c in CNode::GetSendVersion (this=<optimized out>) at net.h:775
#6  0x7f5fde28 in GetSendVersion (this=0xb6ed70a4 <lock>)
    at /home/user/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/include/c++/5.3.0/bits/basic_string.h:179
#7  SendMessages (pto=0xb6ed70a4 <lock>, connman=...)
    at net_processing.cpp:2548
#8  0x7f5ec4bc in operator() (a1=..., a0=<optimized out>, this=<optimized out>)
    at /data/src/bitcoin-arm/depends/arm-unknown-linux-gnueabihf/share/../include/boost/function/function_template.hpp:771
#9  m_invoke<boost::function<bool(CNode*, CConnman&)>, 0u, 1u, CNode*&, CConnman&> (args=..., func=..., this=<optimized out>)
    at /data/src/bitcoin-arm/depends/arm-unknown-linux-gnueabihf/share/../include/boost/signals2/detail/variadic_slot_invoker.hpp:88
#10 operator()<boost::function<bool(CNode*, CConnman&)>, CNode*&, CConnman&, 2u> (args=..., func=..., this=<optimized out>)
    at /data/src/bitcoin-arm/depends/arm-unknown-linux-gnueabihf/share/../include/boost/signals2/detail/variadic_slot_invoker.hpp:80
#11 operator()<boost::shared_ptr<boost::signals2::detail::connection_body<std::pair<boost::signals2::detail::slot_meta_group, boost::optional<int> >, boost::signals2::slot<bool(CNode*, CConnman&), boost::function<bool(CNode*, CConnman&)> >, boost::signals2::mutex> > > (connectionBody=..., this=0xadefed28)
    at /data/src/bitcoin-arm/depends/arm-unknown-linux-gnueabihf/share/../include/boost/signals2/detail/variadic_slot_invoker.hpp:124
#12 dereference (this=0xadefec28)
...
    at /data/src/bitcoin-arm/depends/arm-unknown-linux-gnueabihf/share/../include/boost/signals2/detail/signal_template.hpp:247
#18 0x7f5d057c in operator() (args#1=..., args#0=0x8e5a3fe0, 
    this=0x7fb3dfbc <g_signals+12>)
    at /data/src/bitcoin-arm/depends/arm-unknown-linux-gnueabihf/share/../include/boost/signals2/detail/signal_template.hpp:723
#19 CConnman::ThreadMessageHandler (this=0xb5b0f008) at net.cpp:1896
#20 0x7f5dc9f0 in operator() (this=0xadefee14)
    at /home/user/x-tools/arm-unknown-linux-gnueabihf/arm-unknown-linux-gnueabihf/include/c++/5.3.0/functional:2271
#21 TraceThread<std::function<void ()> >(char const*, std::function<void ()>) (
    name=0x7fa0976c "msghand", func=...) at util.h:207
```
@cfields I'm not sure if it useful to report this as I was testing various pulls, but an assert crash issue is serious so here it goes anyway.

**Comment by paveljanik** [comment]
https://github.com/bitcoin/bitcoin/issues/9212 ?

**Comment by laanwj** [comment]
Ok, closing
